<?php

/*
 * Documento   : consultar Panel Alquilado
 * Creado      : 17-09-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$codigoCoti = Formulario::getParam('_numeroCotizacion');
?>
<form id="<?php echo COXVE; ?>formTICO" name="<?php echo COXVE; ?>formTICO" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:80%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo COXVE_2.' | '.$codigoCoti;?></h4>
            </div>
            <br />
            <table id="<?php echo COXVE; ?>gridTICO" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>