<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-08-2014 08:08:50 
* Descripcion : formNewCliente.phtml
* ---------------------------------------
*/

/*prefijo: CLIT debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("CLITGR");
?>
<form id="<?php echo CLIT; ?>formNewCliente" name="<?php echo CLIT; ?>formNewCliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">TITULO DE FORMULARIO</h4>
            </div>
            <div class="modal-body smart-form"> 
                CONTENIDO DEL FORM (utilizar constantes en Labels.php)
            </div>
            <div class="modal-footer">
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo CLIT; ?>btnGrCliente" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-save"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> Cerrar
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CLIT; ?>formNewCliente");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo CLIT; ?>formNewCliente").validate({
    // Rules for form validation
    rules : {
        <?php echo CLIT; ?>txt_campo : {
            required : true,
            regular: true,
            minlength: 3
        }
    },

    // Msn para validacion -- es opcional -- se puede eliminar, validate tiene los msn configurados por defecto
    messages : {
        <?php echo CLIT; ?>txt_campo : {
            required : "Campo requerido",
            regular: "No se permite caracteres inválidos"
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        cliente.postNewCliente();
    }   
});
</script>