<?php
/*
 * Documento   : nuevoUsuario
 * Creado      : 28-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('SEGCOGR');
$ncoti = Formulario::getParam('_ncoti');
?>
<form id="<?php echo SEGCO; ?>formObservacion" name="<?php echo SEGCO; ?>formObservacion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true" onclick="seguimientoCotizacion.cancelEstado();">
                    &times;
                </button>
                <h4 class="modal-title"><?php  echo SEGCO_2.$ncoti; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo SEGCO_10; ?></label>
                        <div class="col col-8">
                            <label class="textarea"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <textarea id="<?php echo SEGCO; ?>txt_obs" name="<?php echo SEGCO; ?>txt_obs"></textarea>
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo SEGCO_3; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if ($grabar['permiso']): ?>
                <button id="<?php echo SEGCO; ?>btnGrSeguimientoCotizacion" type="submit" class="btn txt-color-white bg-color-blueDark">
                        <i class="fa fa-save"></i> <?php echo $grabar['accion']; ?>
                    </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose" onclick="seguimientoCotizacion.cancelEstado();">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$grabar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo SEGCO; ?>formObservacion');
    </script>
<?php endif; ?>
<script>
    $('#<?php echo SEGCO; ?>formObservacion').validate({
        rules: {
            <?php echo SEGCO; ?>txt_obs: {
                required: true,
                minlength: 2
            }
        },
        
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function() {
            seguimientoCotizacion.postObservacion();
        }
    });
    /*para hacer evento invisible*/
simpleScript.removeAttr.click({
    container: '#<?php echo SEGCO; ?>formObservacion',
    typeElement: 'button'
});
</script>