<?php
/*
 * Documento   : buscarEmpleado
 * Creado      : 03-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */

$buscar = Session::getPermiso('REGVEBS');

?>
<form id="<?php echo T8; ?>formBuscarProducto" name="<?php echo T8; ?>formBuscarProducto" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 70%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_GNC8; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_GNC7; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <input type="text" id="<?php echo T8; ?>txt_search" name="<?php echo T8; ?>txt_search" placeholder="<?php echo LABEL_GNC9; ?>" onkeypress="simpleScript.triggerSearch(this,'#<?php echo T8; ?>gridProductosFound',3);"></input>
                            </label>
                        </div>
<!--                        <div class="col col-8 hide">
                            <label class="input"> 
                                <input type="text" id="<?php echo T8; ?>txt_search" name="<?php echo T8; ?>txt_search" placeholder="<?php echo LABEL_GNC9; ?>" onkeypress="simpleScript.triggerPress('<?php echo T8; ?>btnSubSearchPro',event);"></input>
                            </label>
                        </div>-->
                    </div>
                </section>
                <div class="well" style="overflow: auto;height: 300px;overflow-x: hidden">
                    <table id="<?php echo T8; ?>gridProductosFound" class="table table-bordered table-striped table-condensed smart-form table-hover has-tickbox" style="width:100%">
                        <thead>
                            <th>Nro</th>
                            <th style="width: 3%">
                                <label class="checkbox">
                                    <input type="checkbox" id="<?php echo T8; ?>chk_all" name="<?php echo T8; ?>chk_all" onclick="simpleScript.checkAll(this,'#<?php echo T8; ?>gridProductosFound');"><i></i>
                                </label>
                            </th>
                            <th class="center">Cod.</th>
                            <th class="center">Ubicación</th>
                            <th class="center">Ciudad</th>
                            <th class="center">Iluminado</th>
                            <th class="center">Precio</th>
                        </thead>
                        <tbody>
                            <?php 
                                $f = 0;
                                $datap = generarCotizacionController::getMisProductos(); 
                                $rows = sizeof($datap);
                                foreach ($datap as $value):
                                    $f++;
                                    $iluminado = '<span class="label label-danger center" style="color:#fff;text-align:center"><b>No</b></span>';
                                    if($value['iluminado'] == 1){
                                        $iluminado = '<span class="label label-success" style="color:#fff;text-align:center"><b>Si</b></span>';
                                    }
                                    $prod = AesCtr::en($value['id_caratula']).'~'.$value['descripcion'].' '.$value['ubicacion'].'~'.$value['precio'].'~'.$value['dimesion_area'].'~'.$value['id_ubigeo'];
                            ?>
                            <tr>
                                <td><?php echo $f; ?></td>
                                <td>
                                    <label class="checkbox">
                                        <input type="checkbox" id="<?php echo $f.T8; ?>chk_prod" name="<?php echo T8; ?>chk_prod[]" value="<?php echo $prod; ?>"><i></i>
                                    </label>
                                </td>
                                <td><?php echo $value['codigo']; ?></td>
                                <td><?php echo $value['ubicacion'].' - '.$value['descripcion'].' ('.$value['ancho'].' x '.$value['alto'].' mt)'; ?></td>
                                <td><?php echo $value['distrito']; ?></td>
                                <td><?php echo $iluminado; ?></td>
                                <td style="text-align: right"><?php echo number_format($value['precio'],2); ?></td>
                            </tr>
                            <?php endforeach; ?> 
                            <?php 
                            $diff = 0;
                            if($rows < 7 && $rows > 0){
                                $diff = 7 - $rows;
                                echo Functions::createCell(array('row'=>($diff),'cols'=>7)); 
                            }elseif($rows == 0){
                            ?>  
                            <tr>
                                <td colspan="7">
                                    <div class="alert alert-block alert-warning">
                                        <h4 class="alert-heading"><?php echo LABEL_ADV?></h4>
                                        <?php echo LABEL_ADVMSN?>
                                    </div>
                                </td>
                            </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button id="<?php echo T8; ?>btnSubSearchPro" type="submit" class="hide">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
                
                <button id="<?php echo T8; ?>btnAddProd" type="button" class="btn txt-color-white bg-color-blueDark" onclick="generarCotizacionScript.addProducto();">
                    <i class="fa fa-plus-circle"></i> <?php echo BTN_ADD; ?>
                </button>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php // if (!$buscar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo T8; ?>formBuscarProducto');
    </script>
<?php // endif; ?>
<script>

         
simpleScript.removeAttr.click({
    container: '#<?php echo T8; ?>formBuscarProducto',
    typeElement: 'button'
});
</script>