<?php 
$grabar = Session::getPermiso('GNCOTGR');
$anular = Session::getPermiso('GNCOTAN');
        
echo Functions::widgetOpen(array(
        'id'=>T8,
        'title'=>LABEL_GNC1
    ));
?>
<button id="<?php echo T8; ?>btnDowPDF" type="button" class="hide" onclick="window.open('<?php echo 'public/files/cotizacion.pdf'?>','_blank');">Descargar</button>
<button id="<?php echo T8; ?>btnDowExcel" type="button" class="hide" onclick="window.open('<?php echo 'public/files/cotizacion.xls'?>','_self');">Descargar</button>
                
<div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T8; ?>btnNew" type="button" onclick="generarCotizacion.getNuevoGenerarCotizacion(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <?php if($anular['permiso']): ?>
                <button id="<?php echo T8; ?>btnNew" type="button" onclick="generarCotizacion.postDeleteGenerarCotizacionAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-ban"></i> <?php echo $anular['accion']; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T8; ?>formGridGenerarCotizacion" name="<?php echo T8; ?>formGridGenerarCotizacion">
        <table id="<?php echo T8; ?>gridGenerarCotizacion" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>
