<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-08-2014 08:08:50 
* Descripcion : indexCliente.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("CLITGR");
$eliminar = Session::getPermiso("CLITDE");
echo Functions::widgetOpen(array(
        "id"=>CLIT,
        "title"=>"Cliente"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo CLIT; ?>btnNewCliente" type="button" onclick="cliente.getFormNewCliente(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo CLIT; ?>btnDeleteCliente" type="button" onclick="cliente.postDeleteClienteAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo CLIT; ?>formGridCliente" name="<?php echo T5; ?>formGridCliente">
        <table id="<?php echo CLIT; ?>gridCliente" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>