<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-09-2014 23:09:13 
* Descripcion : indexMisCotizaciones.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("MISCONEW");
$eliminar = Session::getPermiso("MISCODE");
echo Functions::widgetOpen(array(
        "id"=>MISCO,
        "title"=>MISCO_1
    )); 
?>
<button id="<?php echo MISCO; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 400px;top:5px">
        <label class="label col col-7"><?php echo SEGCO_9; ?></label>
        <label class="select pull-left">
            <select id="<?php echo MISCO; ?>lst_estadosearch" name="<?php echo MISCO; ?>lst_estadosearch" onchange="misCotizaciones.getGridMisCotizaciones();">
                <option value="T"><?php echo SEGCO_4; ?></option>
                <option value="A"><?php echo SEGCO_11; ?></option>
                <option value="E"><?php echo SEGCO_5; ?></option>
                <option value="P"><?php echo SEGCO_6; ?></option>
                <option value="R"><?php echo SEGCO_8; ?></option>
            </select>
        </label>
        
    </div>
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">              
            </div>
        </div>

    </div>
<form id="<?php echo MISCO; ?>formGridMisCotizaciones" name="<?php echo MISCO; ?>formGridMisCotizaciones" onsubmit="return false" >
        <table id="<?php echo MISCO; ?>gridMisCotizaciones" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>