<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 22-09-2014 16:09:42 
* Descripcion : indexCotizacionVendedor.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>COXVE,
        "title"=>COXVE_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">              
            </div>
        </div>

    </div>
    <form id="<?php echo COXVE; ?>formGridCotizacionVendedor" name="<?php echo COXVE; ?>formGridCotizacionVendedor">
        <table id="<?php echo COXVE; ?>gridCotizacionVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>