<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 04-09-2014 07:09:53 
* Descripcion : indexSeguimientoCotizacion.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("SEGCONEW");
$eliminar = Session::getPermiso("SEGCODE");
echo Functions::widgetOpen(array(
        "id"=>SEGCO,
        "title"=>SEGCO_1
    )); 
?>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 400px;top:5px">
        <label class="label col col-7"><?php echo SEGCO_9; ?></label>
        <label class="select pull-left">
            <select id="<?php echo SEGCO; ?>lst_estadosearch" name="<?php echo SEGCO; ?>lst_estadosearch" onchange="seguimientoCotizacion.getGridSeguimientoCotizacion();">
                <option value="A"><?php echo SEGCO_4; ?></option>
                <option value="E"><?php echo SEGCO_5; ?></option>
                <option value="P"><?php echo SEGCO_6; ?></option>
                <option value="O"><?php echo SEGCO_7; ?></option>
                <option value="R"><?php echo SEGCO_8; ?></option>
            </select>
        </label>
        
    </div>
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                
            </div>
        </div>

    </div>
    <table id="<?php echo SEGCO; ?>gridSeguimientoCotizacion" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>