<?php
$tab = $this->tab;
$datap = generarCotizacionController::getMisProductos();
$f = 0;
$rows = sizeof($datap);

foreach ($datap as $value):
    $f++;
    $iluminado = '<span class="label label-danger center" style="color:#fff"><b>No</b></span>';
    if($value['iluminado'] == 1){
        $iluminado = '<span class="label label-success" style="color:#fff;text-align:center"><b>Si</b></span>';
    }
    $prod = AesCtr::en($value['id_caratula']).'~'.$value['descripcion'].' '.$value['ubicacion'].'~'.$value['precio'].'~'.$value['costo_produccion'];
?>
<tr>
    <td><?php echo $f; ?></td>
    <td>
        <label class="checkbox">
            <input type="checkbox" id="<?php echo $f.$tab; ?>chk_prod" name="<?php echo $tab; ?>chk_prod[]" value="<?php echo $prod; ?>"><i></i>
        </label>
    </td>
    <td><?php echo $value['codigo']; ?></td>
    <td><?php echo $value['descripcion']; ?></td>
    <td><?php echo $value['ubicacion']; ?></td>
    <td><?php echo $iluminado; ?></td>
    <td><?php echo $value['aarea']; ?></td>
    <td style="text-align: right"><?php echo number_format($value['precio'],2); ?></td>
    <td style="text-align: right"><?php echo number_format($value['costo_produccion'],2); ?></td>
</tr>
<?php endforeach; ?>

<?php 
$diff = 0;
if($rows < 7){
    $diff = 7 - $rows;
    echo Functions::createCell(array('row'=>($diff),'cols'=>9)); 
}
?>
