<?php
/*
 * Documento   : buscarEmpleado
 * Creado      : 03-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */

$buscar = Session::getPermiso('CUSBS');

?>
<form id="<?php echo T4; ?>formBuscarEmpleado" name="<?php echo T4; ?>formBuscarEmpleado" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_2; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <input type="text" id="<?php echo T4; ?>txt_search" name="<?php echo T4; ?>txt_search" placeholder="Escriba y presione enter para buscar" onkeypress="simpleScript.triggerPress('#<?php echo T4; ?>btnSubSearchEm',event);"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <div class="well">
                    <table id="<?php echo T4; ?>gridEmpleadosFound" class="table table-striped table-bordered table-hover" style="width:100%"></table>
                </div>
            </div>
            <div class="modal-footer">
                <button id="<?php echo T4; ?>btnSubSearchEm" type="submit" class="hide">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php //if (!$buscar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo T4; ?>formBuscarEmpleado');
    </script>
<?php //endif; ?>
<script>
    $('#<?php echo T4; ?>formBuscarEmpleado').validate({
            rules : {
                    <?php echo T4; ?>txt_search : {
                            regular2: true                            
                    }
            },            
            errorPlacement : function(error, element) {
                    error.insertAfter(element.parent());
            },
                    
            submitHandler: function(){
                configurarUsuarios.getEmpleados();
            }   
        });
</script>