<?php 
$grabar = Session::getPermiso('CUSGR');
echo Functions::widgetOpen(array(
        'id'=>T4.'usuarios',
        'title'=>M_TITLTE_USU
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T5; ?>btnNew" type="button" onclick="configurarUsuarios.getNuevoUsuario(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T4; ?>formGridUsuariosx" name="<?php echo T4; ?>formGridUsuariosx" onsubmit="return false;">
        <table id="<?php echo T4; ?>gridUsuariosx" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>