<!-- possible classes: minified, no-right-panel, fixed-ribbon, fixed-header, fixed-width-->
<header id="header">
        <!--<span id="logo"></span>-->

       <div id="logo-group">
        <span id="logo"> <img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt="<?php echo APP_NAME; ?>"> </span>

        <!-- END AJAX-DROPDOWN -->
    </div>

</header>

<div id="main" role="main">

        <!-- MAIN CONTENT -->
        <div id="content" class="container">

                <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
                                <h1 class="txt-color-red login-header-big"><?php echo RC_TITULO ;?></h1>
                                <div class="hero">

                                        <div class="pull-left login-desc-box-l">
                                            <h4 class="paragraph-header"><?php echo RC_BIENVENIDA; ?></h4>                                                
                                            <div class="login-app-icons">                             
                                                <a href="<?php echo URL_WEBSITE; ?>" target="_blank" class="btn btn-danger btn-sm"><?php echo LABEL_URL; ?></a>                            
                                            </div>
                                        </div>

                                        <img src="<?php echo $rutaLayout['_img']; ?>demo/iphoneview.png" class="pull-right display-image" alt="" style="width:210px">

                                </div>
                               

                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
                                <div class="well no-padding">
                                        <form action="" id="login-form-password" class="smart-form client-form">
                                                <header>
                                                        <?php echo RC_TITLE; ?>
                                                </header>
                                                <fieldset>
                                                        <section>
                                                                <label class="label"><?php echo L_EMAIL; ?></label>
                                                                <label class="input"> <i class="icon-append fa fa-envelope"></i>
                                                                        <input type="email" name="txtUser" id="txtUser">
                                                                        <b class="tooltip tooltip-top-right"><i class="fa fa-envelope txt-color-teal"></i> <?php echo L_L_EMAIL; ?></b></label>
                                                                <div class="note">
                                                                        <a href="<?php echo BASE_URL;?>"><?php echo RC_RECLAVE; ?></a>
                                                                </div>                                                                        
                                                        </section>
                                                                                                            
                                                </fieldset>
                                                <footer>
                                                        <button id="btnClave" type="submit" class="btn btn-primary">
                                                                <i class="fa fa-refresh"></i> <?php echo RC_SOLCLAVE; ?>
                                                        </button>
                                                </footer>
                                        </form>

                                </div>

                                <h5 class="text-center"><?php echo LABEL_REDSOCIAL; ?></h5>

                                    <ul class="list-inline text-center">
                                        <li>
                                            <a href="<?php echo URL_FACEBOOK; ?>" target="_blank" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                                        </li>
                                        <li>
                                            <a href="<?php echo URL_TWITTER; ?>" target="_blank" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                                        </li>
                                       <!-- <li>
                                            <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                                        </li>-->
                                    </ul>

                        </div>
                </div>
        </div>

</div>
<script>
    function noneEvtMenu(){}
</script>