
<!-- possible classes: minified, no-right-panel, fixed-ribbon, fixed-header, fixed-width-->
<header id="header">
        <!--<span id="logo"></span>-->

    <div id="logo-group">
        <span id="logo"> <img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt="<?php echo APP_NAME; ?>"> </span>

        <!-- END AJAX-DROPDOWN -->
    </div>

  <!--  <span id="login-header-space"> <span class="hidden-mobile">Need an account?</span> <a href="register.html" class="btn btn-danger">Creat account</a> </span>
-->
</header>

<div id="main" role="main">

    <!-- MAIN CONTENT -->
    <div id="content" class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
                <h1 class="txt-color-red login-header-big"><?php echo LOGIN_TITULO;?></h1>
                <div class="hero">

                    <div class="pull-left login-desc-box-l">
                        <h4 class="paragraph-header"><?php echo LOGIN_BIENVENIDA; ?></h4>                                                
                        <div class="login-app-icons">                             
                            <a href="<?php echo URL_WEBSITE; ?>" target="_blank" class="btn btn-danger btn-sm"><?php echo LABEL_URL; ?></a>                            
                        </div>
                    </div>

                    <img src="<?php echo $rutaLayout['_img']; ?>demo/iphoneview.png" class="pull-right display-image" alt="" style="width:210px">

                </div>
                 <!--
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                        <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
                        <p>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
                        </p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                        <h5 class="about-heading">Not just your average template!</h5>
                        <p>
                            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
                        </p>
                    </div>
                </div>
                -->
            </div>
            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
                <div class="well no-padding">
                    <form id="login-form" class="smart-form client-form" onsubmit="return false;">
                        <header>
                            <?php echo L_TITLE; ?>
                        </header>

                        <fieldset>

                            <section>
                                <label class="label"><?php echo L_EMAIL; ?></label>
                                <label class="input"> <i class="icon-append fa fa-user"></i>
                                    <input type="text" name="txtUser" id="txtUser" value="">
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo L_L_EMAIL; ?></b></label>
                            </section>

                            <section>
                                <label class="label"><?php echo L_PASS; ?></label>
                                <label class="input"> <i class="icon-append fa fa-lock"></i>
                                    <input type="password" name="txtClave" id="txtClave" value="">
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> <?php echo L_L_PASS; ?></b> </label>
                                <div class="note">
                                    <a href="<?php echo BASE_URL; ?>index/index/forgotpassword"><?php echo L_OLVIDE; ?></a>
                                </div>
                            </section>
                        </fieldset>
                        <footer>
                            <button id="btnEntrar" type="submit" class="btn bg-color-blueDark txt-color-white">
                                <i class="fa fa-sign-in"></i>
                                <?php echo L_ENTRAR; ?>
                            </button>
                        </footer>
                    </form>

                </div>

                <h5 class="text-center"> <?php echo LABEL_REDSOCIAL; ?></h5>

                <ul class="list-inline text-center">
                    <li>
                        <a href="<?php echo URL_FACEBOOK; ?>" target="_blank" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href="<?php echo URL_TWITTER; ?>" target="_blank" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                    </li>
                   <!-- <li>
                        <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                    </li>-->
                </ul>

            </div>
        </div>
    </div>

</div>
<script>
    function noneEvtMenu(){}
</script>