<?php
/*
 * Documento   : menu
 * Creado      : 04-feb-2014, 9:40:21
 * Autor       : RDCC
 * Descripcion :
 */
$dominioTMP = '';
$menuPrincipalTMP = '';
?>
<?php    
if (Session::get('sys_menu')):
    $dominioTMP = '';
    $permisos = array();
    foreach (Session::get('sys_menu') as $value) :

        /* acciones de una opcion */
        $acciones = indexController::getAccionesOpcion($value['id_rolopciones']);
        
        $aliasopcion = $value['aliasopcion'];

        /* creando array de permisos */

        foreach ($acciones as $val) {
            $permisos[] = array(
                'opcion' => $aliasopcion . $val['aliasaccion'],
                'accion' => $val['accion'],
                'icono' => $val['icono'],
                'theme' => $val['theme'],
                'permiso' => $val['activo']
            );
        }

    endforeach;
endif;
/* crear sesion de permisos */
Session::set('sys_permisos', $permisos);

?>
                    

<?php foreach (Session::get('sys_menu') as $menu): 
        /*tiene que ser del mismo dominio*/
            /*modulo no debe repetirse*/
            if($menu['id_dominio'] != $dominioTMP):
?> 
    <li>
        <a href="javascript:;"><i class="<?php echo $menu['icon']?>"></i> <span class="menu-item-parent"><?php echo $menu['dominio']; ?></span></a>
        <ul>
            <?php
                /*menu principal del modulo*/
                foreach (Session::get('sys_menu') as $menuprincipal):
                    
                    
                    if($menuprincipal['id_dominio'] == $menu['id_dominio']):
                        
                        /*verificar q no se repitan*/
                        if($menuprincipal['id_modulo'] !== $menuPrincipalTMP):
                            
            ?>
                    <li>
                        <a href="javascript:;"><?php echo $menuprincipal['modulo'];?></a>
                        <ul>
                            <?php
                                /*las opciones de menu principal*/
                                foreach (Session::get('sys_menu') as $opciones):
                                    if($opciones['id_dominio'] == $menu['id_dominio'] && $opciones['id_modulo'] == $menuprincipal['id_modulo']):
                            ?>
                                    <li style="margin-left: -28px;">
                                        <a href="javascript:;" class="cortar" title="<?php echo $opciones['menuprincipal']; ?>" onclick="<?php echo $opciones['url']; ?>"><?php echo $opciones['menuprincipal']; ?></a>
                                    </li>
                            <?php
                                    endif;
                                endforeach;
                            ?>
                        </ul>
                    </li>
            <?php
                        endif;
                        $menuPrincipalTMP = $menuprincipal['id_modulo'];
                    endif;
                endforeach;
            ?>
        </ul>
    </li>
<?php 
        endif;
        $dominioTMP = $menu['id_dominio'];
endforeach;

 /*
    * Verifico si es SUPER ADMINISTRADOR (001) o ADMINISTRADOR (002)
    * esto servira para los reportes, si es super o adm tendra acceso a toda la informacion
 */
    Session::set('sys_all','N');
        if(Session::get('sys_defaultRol') == APP_COD_SADM || Session::get('sys_defaultRol') == APP_COD_ADM){
            Session::set('sys_all','S');
       }       

?>
<script>
    function noneEvtMenu(){
        if($('#nav_modulos').length > 0){
            /*para hacer evento invisible*/
            simpleScript.removeAttr.click({
                container: '#nav_modulos',
                typeElement: 'a'
            });
            $('nav ul').jarvismenu({
                    accordion : true,
                    speed : $.menu_speed,
                    closedSign : '<em class="fa fa-expand-o"></em>',
                    openedSign : '<em class="fa fa-collapse-o"></em>'
            });
            
            <?php
              switch (Session::get('sys_defaultRol')){
                        case APP_COD_SADM:
                        case APP_COD_ADM:
             ?>                           
                        setTimeout(function() {generatePageGraphs();}, 1000);
                        setTimeout(function(){ panelesAlquilados.getGridIndexPA();},1500);
                        setTimeout(function(){ saldoCliente.getGridIndexSaldoCliente();},2000);
                        setTimeout(function(){ alquilerCulminar.getGridIndexAlquilerCulminar();},2500);
                        setTimeout(function(){ consultaPermisos.getGridIndexPermisos();},3000);                                                
             <?php      break;
                        case APP_COD_VEND: ?>                           
                        setTimeout(function(){ panelesAlquilados.getGridIndexPA();},100);
                        setTimeout(function(){ saldoCliente.getGridIndexSaldoCliente();},800);
                        setTimeout(function(){ alquilerCulminar.getGridIndexAlquilerCulminar();},1500);
                        setTimeout(function(){ saldoCobrar.getGridIndexSaldoCobrar();},2200);                                                                        
             <?php      break;
                        case APP_COD_CLIE: ?>
                        setTimeout(function(){ contratos.getGridIndexContratos();},100);    
                        setTimeout(function(){ saldoCliente.getGridIndexSaldoClienteProximo();},800);
                        setTimeout(function(){ alquilerCulminar.getGridIndexAlquilerCulminar();},1500);
                        setTimeout(function(){ panelesAlquilados.getGridIndexPA();},2200);
             <?php      break;
                        case APP_COD_SOCIO: ?>
                        setTimeout(function() {generatePageGraphs();}, 1000);
                        setTimeout(function(){ saldoCobrar.getGridIndexSaldoCobrar();},1500);                                                                            
                        setTimeout(function(){ panelesAlquilados.getGridIndexPAS();},2000);                        
             <?php      break;
                        case APP_COD_CAJERO: ?>                           
                        setTimeout(function(){ vConsultaSaldo.getGridIndexVConsultaSaldo();},100);
                        setTimeout(function(){ reporteVentaFecha.getGridIndexVentaFecha();},800);
              <?php      break;
                    }
            ?>
            setup_widgets_desktop();  
             
            /*anular cotizaciones vencidas*/
            index.postAnulaCotizacionesVencidas();
        }
    }

</script>