<div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom sortable-grid ui-sortable" aria-labelledby="ui-id-1" id="<?php echo PANP ?>_CONTAINER">



    <?php
    $obj = array(
        'id' => PANP . 'est1',
        'title' => LABEL_GRAF1,
        'height' => 'auto',
        'padding' => true
    );
    echo Functions::widgetOpen($obj);
    
    $dataG = Obj::run()->indexController->getIndexGraficoIngreso();
    ?>
<!--    <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
        <span class="demo-liveupdate-1"> <span class="onoffswitch-title">Animación</span> <span class="onoffswitch">
                </span> </span>-->
        <div id="chartdiv" style="width: 100%; height: 400px;"></div>

    <!--</div>-->    



    <?php echo Functions::widgetClose(); ?>

    <script>

        var mes = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
        
        function generatePageGraphs() {
            var dataServer = <?php echo json_encode($dataG)?>;
            var color = '',mees='',monto=0;
            var datos = '[';
            
            for(var m = 0;m<12;m++){
                color = simpleScript.getRandomColor();
                
                mees = mes[m];
                
                for(var i in dataServer){
                    if((m+1) == dataServer[i].mes){
                        monto = dataServer[i].monto;
                    }
                }
                
                datos += '{\n\
                    mes: "'+mees+'",\n\
                    monto: '+monto+',\n\
                    color: "'+color+'"\n\
                },';
               
            }
          
            datos = datos.substring(0, datos.length-1);
            datos += '];';
            var chart;

            var chartData = eval(datos);
//            [
//                {
//                    "country": "USA",
//                    "visits": 4025,
//                    "color": "#FF0F00"
//                },
//                {
//                    "country": "China",
//                    "visits": 1882,
//                    "color": "#FF6600"
//                },
//                {
//                    "country": "Japan",
//                    "visits": 1809,
//                    "color": "#FF9E01"
//                },
//                {
//                    "country": "Germany",
//                    "visits": 1322,
//                    "color": "#FCD202"
//                },
//                {
//                    "country": "UK",
//                    "visits": 1122,
//                    "color": "#F8FF01"
//                },
//                {
//                    "country": "France",
//                    "visits": 1114,
//                    "color": "#B0DE09"
//                },
//                {
//                    "country": "India",
//                    "visits": 984,
//                    "color": "#04D215"
//                },
//                {
//                    "country": "Spain",
//                    "visits": 711,
//                    "color": "#0D8ECF"
//                },
//                {
//                    "country": "Netherlands",
//                    "visits": 665,
//                    "color": "#0D52D1"
//                },
//                {
//                    "country": "Russia",
//                    "visits": 580,
//                    "color": "#2A0CD0"
//                },
//                {
//                    "country": "South Korea",
//                    "visits": 443,
//                    "color": "#8A0CCF"
//                },
//                {
//                    "country": "Canada",
//                    "visits": 441,
//                    "color": "#CD0D74"
//                },
//                {
//                    "country": "Brazil",
//                    "visits": 395,
//                    "color": "#754DEB"
//                },
//                {
//                    "country": "Italy",
//                    "visits": 386,
//                    "color": "#DDDDDD"
//                },
//                {
//                    "country": "Australia",
//                    "visits": 384,
//                    "color": "#999999"
//                },
//                {
//                    "country": "Taiwan",
//                    "visits": 338,
//                    "color": "#333333"
//                },
//                {
//                    "country": "Poland",
//                    "visits": 328,
//                    "color": "#000000"
//                }
//            ];


                // SERIAL CHART
                chart = new AmCharts.AmSerialChart();
                chart.dataProvider = chartData;
                chart.categoryField = "mes";
                // the following two lines makes chart 3D
                chart.depth3D = 20;
                chart.angle = 30;

                // AXES
                // category
                var categoryAxis = chart.categoryAxis;
                categoryAxis.labelRotation = 90;
                categoryAxis.dashLength = 5;
                categoryAxis.gridPosition = "start";

                // value
                var valueAxis = new AmCharts.ValueAxis();
                valueAxis.title = "Montos";
                valueAxis.dashLength = 5;
                chart.addValueAxis(valueAxis);

                // GRAPH
                var graph = new AmCharts.AmGraph();
                graph.valueField = "monto";
                graph.colorField = "color";
                graph.balloonText = "<span style='font-size:14px'>[[category]]: <b>[[value]]</b></span>";
                graph.type = "column";
                graph.lineAlpha = 0;
                graph.fillAlphas = 1;
                chart.addGraph(graph);

                // CURSOR
                var chartCursor = new AmCharts.ChartCursor();
                chartCursor.cursorAlpha = 0;
                chartCursor.zoomable = false;
                chartCursor.categoryBalloonEnabled = false;
                chart.addChartCursor(chartCursor);

                chart.creditsPosition = "top-right";


                // WRITE
                chart.write("chartdiv");

        }
        setTimeout(function() {
            generatePageGraphs();
        }, 3000);
    </script>


    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'a1',
            'title' => LABEL_A121,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnPA',
                    'label' => LABEL_MAS,
                    'title' => LABEL_A121,
                    'click' => 'panelesAlquilados.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridPanelAlquilado" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

        <?php
        $obj = array(
            'id' => PANP . 'a3',
            'title' => INDEX_P1,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnAC',
                    'label' => LABEL_MAS,
                    'title' => INDEX_P3,
                    'click' => 'alquilerCulminar.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridAlquilerCulmina" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
    </article>

    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'a2',
            'title' => SACOB_1 . ' - ' . ucwords(Functions::nombremes(date("m"))),
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnSC',
                    'label' => LABEL_MAS,
                    'title' => SACLI_1,
                    'click' => 'saldoCliente.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridSaldoCliente" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

        <?php
        $obj = array(
            'id' => PANP . 'a4',
            'title' => INDEX_P2,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnPM',
                    'label' => LABEL_MAS,
                    'title' => LABEL_A61,
                    'click' => 'consultaPermisos.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridPermisoMunicipal" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
    </article>

    <div class="clearfix">
    </div>

</div>
