<div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom sortable-grid ui-sortable" aria-labelledby="ui-id-1" id="<?php echo PANP ?>_CONTAINER">
    <article class="col-lg-12">
        <?php
        $obj = array(
            'id' => PANP . 'ca1',
            'title' => VCSCL_5,
            'height' => '220px',
            'padding' => true,
             'actions' => array(
                array(
                    'id' => PANP . 'btnPA',
                    'label' => LABEL_MAS,
                    'title' => VCSCL_1,
                    'click' => 'vConsultaSaldo.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridConsultaSaldo" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>


    </article>

    <article class="col-lg-12">
        <?php
        $obj = array(
            'id' => PANP . 'v2',
            'title' => VRPT2_3,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnSC',
                    'label' => LABEL_MAS,
                    'title' => VRPT2_1,
                    'click' => 'reporteVentaFecha.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridVentaFecha" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
                                    
        <?php echo Functions::widgetClose(); ?> 
    </article>
    
    <div class="clearfix">
    </div>

</div>