<div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom sortable-grid ui-sortable" aria-labelledby="ui-id-1" id="<?php echo PANP ?>_CONTAINER">
    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'x1',
            'title' => LABEL_A121,
            'height' => '210px',
            'padding' => true,
             'actions' => array(
                array(
                    'id' => PANP . 'btnPA',
                    'label' => LABEL_MAS,
                    'title' => LABEL_A121,
                    'click' => 'panelesAlquilados.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridPanelAlquilado" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

         <?php
        $obj = array(
            'id' => PANP . 'x3',
            'title' => INDEX_P1,
            'height' => '210px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnAC',
                    'label' => LABEL_MAS,
                    'title' => CALCU_1,
                    'click' => 'alquilerCulminar.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridAlquilerCulmina" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
    </article>

    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'x2',
            'title' => SACOB_1.' - '.ucwords(Functions::nombremes(date("m"))),
            'height' => '210px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnSC',
                    'label' => LABEL_MAS,
                    'title' => SACLI_1,
                    'click' => 'saldoCliente.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridSaldoCliente" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

        <?php
        $obj = array(
            'id' => PANP . '4',
            'title' => 'PAN 4',
            'height' => '200px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => T5 . 'btnNew',
                    'label' => BTN_NUEVO,
                    'click' => 'configurarMenu.getNuevoDominio()'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        AQUI CONTENIDO
        <?php echo Functions::widgetClose(); ?>
    </article>
    
    <div class="clearfix">
    </div>

</div>
<script>
    //setup_widgets_desktop(); 
</script>