<div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom sortable-grid ui-sortable" aria-labelledby="ui-id-1" id="<?php echo PANP ?>_CONTAINER">
    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'v1',
            'title' => LABEL_A121,
            'height' => '220px',
            'padding' => true,
             'actions' => array(
                array(
                    'id' => PANP . 'btnPA',
                    'label' => LABEL_MAS,
                    'title' => LABEL_A121,
                    'click' => 'panelesAlquilados.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridPanelAlquilado" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

         <?php
        $obj = array(
            'id' => PANP . 'v3',
            'title' => INDEX_P1,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnAC',
                    'label' => LABEL_MAS,
                    'title' => INDEX_P3,
                    'click' => 'alquilerCulminar.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridAlquilerCulmina" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
    </article>

    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'v2',
            'title' => SACOB_1.' - '.ucwords(Functions::nombremes(date("m"))),
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnSC',
                    'label' => LABEL_MAS,
                    'title' => SACLI_1,
                    'click' => 'saldoCliente.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridSaldoCliente" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

        <?php
        $obj = array(
            'id' => PANP . 'v4',
            'title' => INDEX_P4,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                   'id' => PANP . 'btnSCO',
                    'label' => LABEL_MAS,
                    'title' => SACOB_1,
                    'click' => 'saldoCobrar.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridSaldoCobrar" class="table table-striped table-hover table-condensed" style="width:100%;"></table>                                
        <?php echo Functions::widgetClose(); ?>
    </article>
    
    <div class="clearfix">
    </div>

</div>