<div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom sortable-grid ui-sortable" aria-labelledby="ui-id-1" id="<?php echo PANP ?>_CONTAINER">
    <article class="col-lg-6">
      <?php
        $obj = array(
            'id' => PANP . 's1',
            'title' => LABEL_A121,
            'height' => '220px',
            'padding' => true,
             'actions' => array(
                array(
                    'id' => PANP . 'btnPA',
                    'label' => LABEL_MAS,
                    'title' => LABEL_A121,
                    'click' => 'panelesAlquilados.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridPanelAlquilado" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

      
    </article>

    <article class="col-lg-6">
      <?php
        $obj = array(
            'id' => PANP . 's2',
            'title' => SACOB_1.' - '.ucwords(Functions::nombremes(date("m"))),
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnSC',
                    'label' => LABEL_MAS,
                    'title' => SACLI_1,
                    'click' => 'saldoCliente.main(this)'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridSaldoCliente" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
   
    </article>
    
    <div class="clearfix">
    </div>

</div>
