<button id="<?php echo PANP; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom sortable-grid ui-sortable" aria-labelledby="ui-id-1" id="<?php echo PANP ?>_CONTAINER">    
    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'c1',
            'title' => INDEX_P5,
            'height' => '220px',
            'padding' => true,
             'actions' => array(
                array(
                    'id' => PANP . 'btnCon',
                    'label' => LABEL_MAS,
                    'title' => INDEX_P5,
                    'click' => 'contratos.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridContratos" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

        <?php
        $obj = array(
            'id' => PANP . 'c3',
            'title' => INDEX_P1,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnAC',
                    'label' => LABEL_MAS,
                    'title' => CALCU_1,
                    'click' => 'alquilerCulminar.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridAlquilerCulmina" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
    </article>

    <article class="col-lg-6">
        <?php
        $obj = array(
            'id' => PANP . 'c2',
            'title' => INDEX_P6,
            'height' => '220px',
            'padding' => true,
            'actions' => array(
                array(
                    'id' => PANP . 'btnCP',
                    'label' => LABEL_MAS,
                    'title' => INDEX_P7,
                    'click' => 'cronogramaCliente.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridSaldoCliente" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>

       <?php
        $obj = array(
            'id' => PANP . 'c4',
            'title' => MIPAL_1,
            'height' => '220px',
            'padding' => true,
             'actions' => array(
                array(
                    'id' => PANP . 'btnPA',
                    'label' => LABEL_MAS,
                    'title' => MIPAL_1,
                    'click' => 'panelcliente.main(this);'
                )
            )
        );
        echo Functions::widgetOpen($obj);
        ?>
        <table id="<?php echo PANP; ?>gridPanelAlquilado" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
        <?php echo Functions::widgetClose(); ?>
    </article>
    
    <div class="clearfix">
    </div>

</div>
