<?php

/*
 * Documento   : consultar ROI Orden de Servicios
 * Creado      : 02-10-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$socio = Formulario::getParam("_nom");
?>
<form id="<?php echo CREIN; ?>formRoiOs" name="<?php echo CREIN; ?>formRoiOs" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:90%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CREIN_2.' - '.strtoupper($socio)?></h4>
            </div>
            <div style="margin-top:40px"></div>
            <table id="<?php echo CREIN; ?>gridRoiOs" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>