<?php

/*
 * Documento   : consultar Detalle Inversion
 * Creado      : 01-10-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
?>
<form id="<?php echo MIINV; ?>formDetalleInversion" name="<?php echo MIINV; ?>formDetalleInversion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:70%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo MIINV_2?></h4>
            </div>
            <br />
            <table id="<?php echo MIINV; ?>gridDetalleInversion" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>