<?php

/*
 * Documento   : consultar Panel Alquilado
 * Creado      : 17-09-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$data = panelesInvertidoController::getGeografico();

if($data['imagen'] != '' or $data['imagen'] != null){
    $imagen = '<a href=\"'.BASE_URL.'public/img/uploads/'.$data['imagen'].'\" target=\"_blank\" ><img border=\"0\" src=\"'.BASE_URL.'public/img/upload/'.$data['imagen'].'\" style=\"width:300px; height:200px;\" class=\"img-circle\" /></a>';
}else{
    $imagen = '<img src=\"'.BASE_URL.'public/img/sin_foto.jpg\" style=\"width:250px; height:auto;\" class=\"img-circle\" />';
 }

$html = "<h4>Vista previa:</h4>"
        . "<center>".$imagen."</center>";

?>
<form id="<?php echo PAINV; ?>formConsultaPanelSocio" name="<?php echo PAINV; ?>formConsultaPanelSocio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:50%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo MIPAL_2?></h4>
            </div>
             <div class="modal-body smart-form">                 
             <section>
                     <div class='alert alert-warning fade in' style='margin-top:10px;'>
                        <i class='fa-fw fa fa-map-marker'></i>
                        <strong>Direccion: </strong><?php echo  $data['ubicacion'].' - '.$data['ciudad']; ?>
                    </div>                
             </section>
             <section>                      
                 <div id="<?php echo PAINV; ?>map_canvas" style="width:100%;height:350px;"></div>   
             </section>     
             </div>                        
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>

<script>

    function initialize() {
        var map;
        var bounds = new google.maps.LatLngBounds();
        var mapOptions = {
                mapTypeId: 'roadmap'
        };	
        // Display a map on the page
        map = new google.maps.Map(document.getElementById(diccionario.tabs.PAINV+"map_canvas"), mapOptions);
        map.setTilt(45);
        // Multiple Markers
         var markers = [["<?php echo $data['ubicacion']; ?>","<?php echo $data['google_latitud']; ?>","<?php echo $data['google_longitud']; ?>"]];	
        // Info Window Content
        var infoWindowContent = [["<?php echo $html; ?>"]];
        // Display multiple markers on a map
        var infoWindow = new google.maps.InfoWindow(), marker, i;
        // Loop through our array of markers & place each one on the map  
        for( i = 0; i < markers.length; i++ ) {
                var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
                bounds.extend(position);
                marker = new google.maps.Marker({
                        position: position,
                        map: map,
                        title: markers[i][0]
                });
                // Allow each marker to have an info window    
                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                        return function() {
                                infoWindow.setContent(infoWindowContent[i][0]);
                                infoWindow.open(map, marker);
                        }
                })(marker, i));
                // Automatically center the map fitting all markers on the screen
                map.fitBounds(bounds);
        }
        // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
        var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
                this.setZoom(14);
                google.maps.event.removeListener(boundsListener);
                setTimeout(function(){ resetMap(map);},500);
        });   
    }
    
     //Resetear Mapa
     function resetMap(m){
         x = m.getZoom();
         c = m.getCenter();
         google.maps.event.trigger(m, 'resize');
         m.setZoom(x);
         m.setCenter(c);
    }; 
    
    initialize();
					
</script>