<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 03-09-2014 14:09:13 
* Descripcion : formNewRegInversion.phtml
* ---------------------------------------
*/

$grabar = Session::getPermiso("REINVGR");
?>
<form id="<?php echo REINV; ?>formNewRegInversion" name="<?php echo REINV; ?>formNewRegInversion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_A102;?></h4>
            </div>
            <div class="modal-body smart-form"> 
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A104; ?></label>                        
                        <div class="col col-3">
                            <label class="input"> 
                                <i class="icon-append fa fa-calendar-o "></i>
                                <input type="text" id="<?php echo REINV; ?>txt_fecha" name="<?php echo REINV; ?>txt_fecha" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A104M; ?></b>
                            </label>
                        </div>
                        <label class="label col col-2"><?php echo LABEL_A105; ?></label>
                            <div class="col col-4">
                                <label class="input"> 
                                    <i class="icon-append fa  fa-money"></i>
                                    <input type="text" id="<?php echo REINV; ?>txt_monto" name="<?php echo REINV; ?>txt_monto"></input>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A105M; ?></b>
                                </label>
                            </div>            
                    </div>
                </section>
                
            </div>
            <div class="modal-footer">
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo REINV; ?>btnGrRegInversion" type="submit" class="<?php echo $grabar['theme'];?>">
                    <i class="<?php echo $grabar['icono'];?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo REINV; ?>formNewRegInversion");
</script>
<?php endif; ?>
<script>

simpleScript.setEvent.date({
      element: '#<?php echo REINV; ?>txt_fecha'
    });
    
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo REINV; ?>formNewRegInversion").validate({
    rules : {
        <?php echo REINV; ?>txt_monto : {
            required : true,
            number: true     
        },
        <?php echo REINV; ?>txt_fecha : {
            required : true,
            date: true     
        }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        regInversion.postNewRegInversion();
    }   
});
</script>