<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 03-09-2014 02:09:26 
* Descripcion : formNewSocio.phtml
* ---------------------------------------
*/

/*prefijo: TAB_SOCIO debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("REGSOGR");
?>
<form id="<?php echo REINV; ?>formNewSocio" name="<?php echo REINV; ?>formNewSocio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_A81;?></h4>
            </div>
            <div class="modal-body smart-form" style="height: 350px;overflow-y: auto;overflow-x: hidden;">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A83; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_nombres" name="<?php echo TAB_SOCIO; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_A83M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A84; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_apellidopaterno" name="<?php echo TAB_SOCIO; ?>txt_apellidopaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_A84M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A85; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_apellidomaterno" name="<?php echo TAB_SOCIO; ?>txt_apellidomaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_A85M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>   
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A90; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_nrodocumento" name="<?php echo TAB_SOCIO; ?>txt_nrodocumento">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A90M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A95; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_dni" name="<?php echo TAB_SOCIO; ?>txt_dni">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A95M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A91; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = socioController::getDepartamentos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>TAB_SOCIO.'lst_departamento',
                                            'name'=>TAB_SOCIO.'lst_departamento',
                                            'onchange'=>'registrarVendedor.getProvincias({
                                                            idDepartamento: $(\'#'.TAB_SOCIO.'lst_departamento\').val(),
                                                            content: \'#'.TAB_SOCIO.'cont-provincias\',
                                                            idElement: \''.TAB_SOCIO.'lst_provincia\',
                                                            nameElement: \''.TAB_SOCIO.'lst_provincia\',
                                                            contentUbigeo: \'#'.TAB_SOCIO.'cont-ubigeo\',
                                                            idUbigeo: \''.TAB_SOCIO.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A92; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo TAB_SOCIO; ?>cont-provincias"> 
                                <select id="<?php echo TAB_SOCIO; ?>lst_provincia" name="<?php echo TAB_SOCIO; ?>lst_provincia">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A93; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo TAB_SOCIO; ?>cont-ubigeo"> 
                                <select id="<?php echo TAB_SOCIO; ?>lst_ubigeo" name="<?php echo TAB_SOCIO; ?>lst_ubigeo">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A86; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_direccion" name="<?php echo TAB_SOCIO; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A86M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A87; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_email" name="<?php echo TAB_SOCIO; ?>txt_email">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A87M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A88; ?></label>
                        <div class="inline-group col col-8">
                            <label class="radio"> 
                                <input name="<?php echo TAB_SOCIO; ?>rd_sexo" id="<?php echo TAB_SOCIO; ?>rd_sexoH" checked type="radio" value="H">
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo TAB_SOCIO; ?>rd_sexo" id="<?php echo TAB_SOCIO; ?>rd_sexoM" type="radio" value="M">
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A89; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo TAB_SOCIO; ?>txt_telefonos" name="<?php echo TAB_SOCIO; ?>txt_telefonos">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A89M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
               <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A96; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $tiposoc = Array (
                                            Array ( 'id' => 'P', 'descripcion' => 'PRINCIPAL' ),
                                            Array ( 'id' => 'A', 'descripcion' => 'ASOCIADO' )
                                    );                                   
                                    echo Functions::selectHtml(array(
                                        'data'=>$tiposoc,
                                        'atributes'=>array(
                                            'id'=>TAB_SOCIO.'lst_tiposocio',
                                            'name'=>TAB_SOCIO.'lst_tiposocio'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>                                            
                
               
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo REINV; ?>btnGsocio" type="submit" class="<?php echo $grabar['theme'];?>">
                    <i class="<?php echo $grabar['icono'];?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo REINV; ?>formNewSocio');
</script>
<?php endif; ?>
<script>
    $('#<?php echo REINV; ?>formNewSocio').validate({
        rules : {
                <?php echo TAB_SOCIO; ?>txt_nombres : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo TAB_SOCIO; ?>txt_apellidopaterno : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo TAB_SOCIO; ?>txt_apellidomaterno : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo TAB_SOCIO; ?>txt_nrodocumento:{
                        number: true,
                        maxlength: 12
                },
                <?php echo TAB_SOCIO; ?>txt_dni:{
                        number: true,
                        maxlength: 8
                },        
                <?php echo TAB_SOCIO; ?>lst_departamento : {
                        required : true
                },
                <?php echo TAB_SOCIO; ?>lst_provincia : {
                        required : true
                },
                <?php echo TAB_SOCIO; ?>lst_ubigeo : {
                        required : true
                },
                <?php echo TAB_SOCIO; ?>txt_direccion : {
                        regular2: true,
                        minlength: 3
                },
                <?php echo TAB_SOCIO; ?>txt_email : {
                        required : true,
                        email: true
                }                  
        },

        
        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            regInversion.postNuevoSocio();
        }   
    });
</script>
</form>