<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 02-10-2014 23:10:16 
* Descripcion : indexRetornoInversion.phtml
* ---------------------------------------
*/

echo Functions::widgetOpen(array(
        "id"=>REINV,
        "title"=>REINV_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">             
            </div>
        </div>

    </div>
    <form id="<?php echo REINV; ?>formGridRetornoInversion" name="<?php echo REINV; ?>formGridRetornoInversion" onsubmit="return false">
        <table id="<?php echo REINV; ?>gridRetornoInversion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>