<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 30-09-2014 00:09:45 
* Descripcion : indexMisInversiones.phtml
* ---------------------------------------
*/
$buscar    = Session::getPermiso("MIINVBS");

echo Functions::widgetOpen(array(
        "id"=>MIINV,
        "title"=>MIINV_1
    )); 
?>

    <div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 0px;top:5px;width: 65% ">               
        <label class="label col col-1"><?php echo COGEN_2; ?></label>        
        <div class="col col-2" style="padding-left:5px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo MIINV;?>txt_f1" name="<?php echo MIINV;?>txt_f1" value ="01/01/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <label class="label col col-1" >&nbsp;<?php echo COGEN_3; ?></label>        
        <div class="col col-2" >
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo MIINV;?>txt_f2" name="<?php echo MIINV;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
       
        <div class="col col-1" style="padding-left:30px;">
            <div class=" ">
                <button id="<?php echo MIINV; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="misInversiones.getGridMisInversiones();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
    </div>
    
    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
            </div>
        </div>

    </div>
<form id="<?php echo MIINV; ?>formGridMisInversiones" name="<?php echo MIINV; ?>formGridMisInversiones" onsubmit="return false" >
        <table id="<?php echo MIINV; ?>gridMisInversiones" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>

<script>
    
    simpleScript.setEvent.date({
      element: '#<?php echo MIINV; ?>txt_f1, #<?php echo MIINV; ?>txt_f2' 
    });
</script>