<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 03-09-2014 14:09:13 
* Descripcion : indexRegInversion.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("REINVGR");
$eliminar = Session::getPermiso("REINVDE");
echo Functions::widgetOpen(array(
        "id"=>REINV,
        "title"=>"RegInversion"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnNewRegInversion" type="button" onclick="regInversion.getFormNewRegInversion(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnDeleteRegInversion" type="button" onclick="regInversion.postDeleteRegInversionAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REINV; ?>formGridRegInversion" name="<?php echo T5; ?>formGridRegInversion">
        <table id="<?php echo REINV; ?>gridRegInversion" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>