<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 02-10-2014 20:10:49 
* Descripcion : indexPanelesInvertido.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>PAINV,
        "title"=>PAINV_1
    )); 
?>
<button id="<?php echo PAINV; ?>btnDowPDF" type="button" class="hide" >Descargar</button>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">                
            </div>
        </div>

    </div>
    <form id="<?php echo PAINV; ?>formGridPanelesInvertido" name="<?php echo PAINV; ?>formGridPanelesInvertido" onsubmit="return false" >
        <table id="<?php echo PAINV; ?>gridPanelesInvertido" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>