<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 03-09-2014 14:09:13 
* Descripcion : indexRegInversion.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("REGSONEW");
$eliminar = Session::getPermiso("REGSODEL");
$nuevo2   = Session::getPermiso("REINVNEW");
$eliminar2 = Session::getPermiso("REINVDEL");
echo Functions::widgetOpen(array(
        "id"=>REINV,
        "title"=>LABEL_A100
    )); 
?>

  <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row pull-left" style="width: 49%">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnNewSocio" type="button" onclick="regInversion.getFormNewSocio(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnDeleteSocio" type="button" onclick="regInversion.postDeleteSocioAll(this);" class="<?php echo $eliminar['theme'];?>">
                    <i class="<?php echo $eliminar['icono'];?>"></i> <?php echo $eliminar['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>
        <div id="<?php echo REINV; ?>tollInversion" class="dt-top-row pull-right" style="width: 49%;display: none">
            <button type="button" class="btn btn-warning" style="position:absolute;margin-top:-38px">
                <?php echo LABEL_A101; ?> 
                <span id="<?php echo REINV; ?>regInversion-cont"></span>
            </button>
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo2["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnNewInv" type="button" onclick="regInversion.getFormNewRegInversion(this);" class="<?php echo $nuevo2['theme'];?>">
                    <i class="<?php echo $nuevo2['icono'];?>"></i> <?php echo $nuevo2['accion'];?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar2["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnDeleteInv" type="button" onclick="regInversion.postDeleteInversionAll(this);" class="<?php echo $eliminar2['theme'];?>">
                    <i class="<?php echo $eliminar2['icono'];?>"></i> <?php echo $eliminar2['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REINV; ?>formGridSocio" name="<?php echo REINV; ?>formGridSocio" onsubmit="return false;">
        <div class="pull-left" style="width: 49%;border-right: 1px solid #ccc">
            <table id="<?php echo REINV; ?>gridSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
        </div>
        <div id="<?php echo REINV; ?>cont-gridInversion" class="pull-right" style="width: 49%;border-left: 1px solid #ccc">
            <table id="<?php echo REINV; ?>gridInversion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
        </div>
    </form>
<?php echo Functions::widgetClose(); ?>