<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 05-09-2014 23:09:58 
* Descripcion : indexRegProduccion.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("REPRONEW");
$anular = Session::getPermiso("REPRODEL");
echo Functions::widgetOpen(array(
        "id"=>REPRO,
        "title"=>LABEL_A130
    )); 
?>
<button id="<?php echo REPRO; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo REPRO; ?>btnDowExcel" type="button" class="hide">Descargar</button>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo REPRO; ?>btnNewRegProduccion" type="button" onclick="regProduccion.getFormNewRegProduccion(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>
                <?php if($anular["permiso"]): ?>
                <button id="<?php echo REPRO; ?>btnNewRegProduccion" type="button" onclick="regProduccion.postAnularRegProduccionAll(this);" class="<?php echo $anular['theme'];?>">
                    <i class="<?php echo $anular['icono'];?>"></i> <?php echo $anular['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REPRO; ?>formGridRegProduccion" name="<?php echo REPRO; ?>formGridRegProduccion" onsubmit="return false;">
        <table id="<?php echo REPRO; ?>gridRegProduccion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>