<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 05-09-2014 23:09:58 
* Descripcion : indexRegProduccion.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("REPROGR");
$eliminar = Session::getPermiso("REPRODE");
echo Functions::widgetOpen(array(
        "id"=>REPRO,
        "title"=>"RegProduccion"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo REPRO; ?>btnNewRegProduccion" type="button" onclick="regProduccion.getFormNewRegProduccion(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REPRO; ?>btnDeleteRegProduccion" type="button" onclick="regProduccion.postDeleteRegProduccionAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REPRO; ?>formGridRegProduccion" name="<?php echo T5; ?>formGridRegProduccion">
        <table id="<?php echo REPRO; ?>gridRegProduccion" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>