<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 02-10-2014 23:10:16 
* Descripcion : indexRetornoInversion.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("REINVNEW");
$eliminar = Session::getPermiso("REINVDE");
echo Functions::widgetOpen(array(
        "id"=>REINV,
        "title"=>"RetornoInversion"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnNewRetornoInversion" type="button" onclick="retornoInversion.getFormNewRetornoInversion(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REINV; ?>btnDeleteRetornoInversion" type="button" onclick="retornoInversion.postDeleteRetornoInversionAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REINV; ?>formGridRetornoInversion" name="<?php echo REINV; ?>formGridRetornoInversion">
        <table id="<?php echo REINV; ?>gridRetornoInversion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>