<?php

/*
 * Documento   : editarTipoPanel
 * Creado      : 07-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$editar = Session::getPermiso('TIPAACT');
$tipa = tipoPanelController::getTipoPanel();

?>
<form id="<?php echo T101; ?>formTipoPanel" name="<?php echo T101; ?>formTipoPanel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_A12;?></h4>
            </div>
            <div class="modal-body smart-form">                
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A10; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T101; ?>txt_descripcion" name="<?php echo T101; ?>txt_descripcion" value="<?php echo $tipa['descripcion']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
               
<!--                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo T101; ?>chk_activo" id="<?php echo T101; ?>chk_activo" value="A" <?php echo ($tipa['estado'] == 'A')?'checked':'' ?>></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>-->
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="<?php echo T101; ?>btnACTtipa" type="submit" class="<?php echo $editar['theme']; ?>">
                    <i class="<?php echo $editar['icono']; ?>"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
                 <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$editar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T101; ?>formTipoPanel');
</script>
<?php endif; ?>
<script>
    $('#<?php echo T101; ?>formTipoPanel').validate({
        rules : {
                <?php echo T101; ?>txt_descripcion : {
                        required : true,
                        regular: true,
                        minlength: 3
                }
        },
        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            tipoPanel.postEditarTipoPanel();
        }   
    });
</script>
</form>