<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 25-08-2014 22:08:31 
* Descripcion : editarPermisoMunicipal.phtml
* ---------------------------------------
*/

/*prefijo: PERMU debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso('PERMUACT');
$data = permisoMunicipalController::getPermisoMunicipal();

?>
<form id="<?php echo PERMU; ?>formPermisoMunicipal" name="<?php echo PERMU; ?>formPermisoMunicipal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_A53;?></h4>
            </div>
            <div class="modal-body smart-form"> 
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A54; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-calendar-o "></i>
                                <input type="text" id="<?php echo PERMU; ?>txt_fi" name="<?php echo PERMU; ?>txt_fi" value="<?php echo Functions::cambiaf_a_normal($data['fecha_inicio']); ?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A54M; ?></b>
                            </label>
                        </div>
                        <label class="label col col-2"><?php echo LABEL_A55; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-calendar-o "></i>
                                <input type="text" id="<?php echo PERMU; ?>txt_ff" name="<?php echo PERMU; ?>txt_ff" value="<?php echo functions::cambiaf_a_normal($data['fecha_final']); ?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A55M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>     
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A56; ?></label>
                            <div class="col col-4">
                                <label class="input"> 
                                    <i class="icon-append fa  fa-money"></i>
                                    <input type="text" id="<?php echo PERMU; ?>txt_monto" name="<?php echo PERMU; ?>txt_monto" value="<?php echo number_format($data['monto_pago'],2); ?>"></input>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A56M; ?></b>
                                </label>
                            </div>                                                   
                    </div>
                </section>
                 <section>
                        <div class="row">
                            <label class="label col col-2"><?php echo LABEL_A57; ?></label>
                            <div class="col col-10">
                                <label class="textarea textarea-resizable"> 
                                     <i class="icon-append fa fa-align-justify"></i>
                                    <textarea id="<?php echo PERMU; ?>txt_observacion" name="<?php echo PERMU; ?>txt_observacion" class="custom-scroll" rows="3"><?php echo $data['observacion']; ?></textarea> 
                                     <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A57M; ?></b>
                                </label>

                            </div>
                        </div>
                </section>   
                
            </div>
            <div class="modal-footer">
                <?php if($editar["permiso"]):?>
                <button id="<?php echo PERMU; ?>btnAPermisoMunicipal" type="submit" class="<?php echo $editar['theme'];?>">
                    <i class="<?php echo $editar['icono'];?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                    </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<script>
    simpleScript.noSubmit("#<?php echo PERMU; ?>formPermisoMunicipal");
</script>
<script>
    
    simpleScript.setEvent.date({
      element: '#<?php echo PERMU; ?>txt_fi, #<?php echo PERMU; ?>txt_ff' 
    });
    
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo PERMU; ?>formPermisoMunicipal").validate({
    rules : {
        <?php echo PERMU; ?>txt_fi : {
            required : true,
            date: true     
        },<?php echo PERMU; ?>txt_ff : {
            required : true,
            date: true     
        },<?php echo PERMU; ?>txt_monto : {
            required: true,
            number: true       
        }
    },   
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        permisoMunicipal.postEditarPermisoMunicipal();
    }   
});
</script>