<?php
/*
 * Documento   : nuevaCaratula
 * Creado      : 21-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$editar = Session::getPermiso('FITECACT');
$data = fichaTecnicaController::getCaratula();
?>
<form id="<?php echo T102; ?>formCaratula" name="<?php echo T102; ?>formCaratula" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_A36;?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A37; ?></label>
                        <div class="col col-5">
                            <label class="input"> 
                                <i class="icon-append fa fa-code"></i>
                                <input type="text" id="<?php echo T102; ?>txt_codigo" name="<?php echo T102; ?>txt_codigo" maxlength="7" value="<?php echo $data['codigo']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A37M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>                
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A38; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T102; ?>txt_descripcion" name="<?php echo T102; ?>txt_descripcion" value="<?php echo $data['descripcion']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A38M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>         
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A39; ?></label>
                            <div class="col col-3">
                                <label class="input"> 
                                    <i class="icon-append fa  fa-money"></i>
                                    <input type="text" id="<?php echo T102; ?>txt_precio" name="<?php echo T102; ?>txt_precio" value="<?php echo $data['precio']; ?>"></input>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A39M; ?></b>
                                </label>
                            </div>                        
                            <div class="col col-3">
                                <label class="checkbox">
                                    <input type="checkbox" name="<?php echo T102; ?>chk_iluminado" id="<?php echo T102; ?>chk_iluminado" value="1" <?php echo ($data['iluminado'] == '1')?'checked':'' ?>></input>
                                    <i></i>
                                    <?php echo LABEL_A40; ?>
                                </label>
                        </div>
                    </div>
                </section>                
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_A46; ?></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" <?php echo ($data['multiplecotizacion'] == 'S')?'checked':'' ?> name="<?php echo T102; ?>chk_multi" id="<?php echo T102; ?>chk_multi" value="S" ></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>  
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="<?php echo T102; ?>btnGcara" type="submit" class="<?php echo $editar['theme'];?>">
                    <i class="<?php echo $editar['icono'];?>"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<script>
    simpleScript.noSubmit('#<?php echo T102; ?>formCaratula');
</script>
<script>
    $('#<?php echo T102; ?>formCaratula').validate({
        rules : {
                <?php echo T102; ?>txt_codigo : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T102; ?>txt_descripcion : {
                        required : true,                        
                        minlength: 3
                },
                <?php echo T102; ?>txt_precio : {
                        required : true,
                        number : true                         
                }
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            fichaTecnica.postEditarCaratula();
        }   
    });
</script>
</form>
