<?php
/*
 * Documento   : menuPrincipales
 * Creado      : 14-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$eliminar = Session::getPermiso('FITECDE');

$data = fichaTecnicaController::getCaratulas();

?>

<?php if(sizeof($data)): ?>
<ol id="ol-caratulas" class="lista-redondeada ol">
    <?php 
        foreach ($data as $value): 
            $inactivo = 'text-decoration:line-through;color: red;float:left; margin-top:-20px;';
            if($value['estado'] == 'D'){
                $inactivo = '';
            }
    ?>
        <li id="liCaratula_<?php echo $value['id_caratula']; ?>" >
            <a href="javascript:;" rel="popover-hover" data-placement="top" 
               data-original-title="<?php echo $value['codigo']; ?>" 
               data-content="<div><b>Descripción:</b> <?php echo $value['descripcion']; ?></div>
               <div><b>Precio:</b> <?php echo number_format($value['precio'],2); ?></div>
               <div><b>Iluminado:</b> <?php echo ($value['iluminado']==1)?'SI':'NO'; ?></div>               
               <div><img src='http://localhost/panel/public/img/uploads/paneles.png' style='width:100%;'></div>"
               data-html="true">
                
               <span style="<?php echo $inactivo; ?>">
                   <?php echo $value['codigo'].' - '.$value['descripcion'] ?>
               </span>
                                                                     
               <div class="pull-right btn-group" style="margin-top: -4px;">                    
                   <?php if($value['iluminado'] == '1'): ?>
                    <button class=" btn  btn-xs btn-warning" title="Iluminado">
                        <i class="fa fa-sun-o fa-lg"></i>                                              
                    </button>
                   <?php endif; ?>
                    <button class="btn btn-xs btn-primary" title="Editar" onclick="fichaTecnica.getEditarMenuPrincipal('<?php echo AesCtr::en($value['id_caratula']); ?>');">
                        <i class="fa fa-edit fa-lg"></i>
                    </button>
                    <?php if ($eliminar['permiso']): ?>
                        <button class="btn btn-xs btn-danger" title="<?php echo $eliminar['accion']; ?>" onclick="fichaTecnica.postDeleteMenuPrincipal('<?php echo AesCtr::en($value['id_caratula']); ?>');">
                            <i class="fa fa-ban fa-lg"></i>
                        </button>
                    <?php endif; ?>
                </div>
            </a>
        </li>
    <?php endforeach; ?>
</ol>
<script>      
    // activate popovers with hover states
    $("[rel=popover-hover]").popover({
            trigger : "hover"
    });  
    /*para quitar evento*/
    simpleScript.removeAttr.click({
        container: '#widget_<?php echo T102.'caratulas'; ?>',
        typeElement: 'button'
    });
</script>
<?php else: ?>
<div  class="no-result-menu" style="float:left;margin-top:20px;">
    <div class="alert alert-danger">No se encontraron registros</div>
</div>
<?php endif; ?>