<?php 
$grabar = Session::getPermiso('TIPAGR');
$eliminar = Session::getPermiso('TIPADE');
        
echo Functions::widgetOpen(array(
        'id'=>T101,
        'title'=>LABEL_A8
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T101; ?>btnNew" type="button" onclick="tipoPanel.getNuevoTipoPanel(this,'');" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T101; ?>btnNew" type="button" onclick="tipoPanel.postDeleteTipoPanelAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-ban"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T101; ?>formGridTipoPanel" name="<?php echo T101; ?>formGridTipoPanel">
        <table id="<?php echo T101; ?>gridTipoPanel" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>