<?php 
$nuevo = Session::getPermiso('TIPANEW');
$eliminar = Session::getPermiso('TIPADEL');
        
echo Functions::widgetOpen(array(
        'id'=>T101,
        'title'=>LABEL_A8
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T101; ?>btnNew" type="button" onclick="tipoPanel.getNuevoTipoElemento(this,'');" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T101; ?>btnNew" type="button" onclick="tipoPanel.postDeleteTipoPanelAll(this);" class="<?php echo $eliminar['theme'];?>">
                    <i class="<?php echo $eliminar['icono'];?>"></i> <?php echo $eliminar['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T101; ?>formGridTipoPanel" name="<?php echo T101; ?>formGridTipoPanel" onsubmit="return false;">
        <table id="<?php echo T101; ?>gridTipoPanel" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>