<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-08-2014 02:08:12 
* Descripcion : indexCatalogoPrecio.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("TAB_CATPREGR");
$eliminar = Session::getPermiso("TAB_CATPREDE");
echo Functions::widgetOpen(array(
        "id"=>TAB_CATPRE,
        "title"=>LABEL_A70
    )); 
?>
<button id="<?php echo TAB_CATPRE; ?>btnDowPDF" type="button" class="hide" onclick="window.open('<?php echo 'public/files/fichatecnicacatalogo.pdf'?>','_blank');">Descargar</button>
<button id="<?php echo TAB_CATPRE; ?>btnDowExcel" type="button" class="hide" onclick="window.open('<?php echo 'public/files/fichatecnicacatalogo.xls'?>','_self');">Descargar</button>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
              
            </div>
        </div>

    </div>
    <form id="<?php echo TAB_CATPRE; ?>formGridCatalogoPrecio" name="<?php echo TAB_CATPRE; ?>formGridCatalogoPrecio">
        <table id="<?php echo TAB_CATPRE; ?>gridCatalogoPrecio" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>