<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-08-2014 02:08:12 
* Descripcion : indexCatalogoPrecio.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>TAB_CATPRE,
        "title"=>LABEL_A70
    )); 
?>
<button id="<?php echo TAB_CATPRE; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo TAB_CATPRE; ?>btnDowExcel" type="button" class="hide">Descargar</button>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 400px;top:5px">
        <label class="label col col-7"><?php echo LABEL_A71; ?></label>
        <label class="select pull-left">
           <?php
                $datal = catalogoPreciosController::getListadoTipoPanel();           
                echo Functions::selectHtml(array(
                    'data'=>$datal,
                    'atributes'=>array(
                        'id'=>TAB_CATPRE.'lst_tipopanelsearch',
                        'name'=>TAB_CATPRE.'lst_tipopanelsearch',
                        'onchange'=>'catalogoPrecios.getGridCatalogoPrecios();'
                    ),
                    'etiqueta'=>'descripcion',
                    'value'=>'id_tipopanel',
                    'defaultEtiqueta'=>'',
                    'txtAll'=>true
                ));
            ?>
            <i></i>
        </label>
        
    </div>
</div>    
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
              
            </div>
        </div>

    </div>
<form id="<?php echo TAB_CATPRE; ?>formGridCatalogoPrecio" name="<?php echo TAB_CATPRE; ?>formGridCatalogoPrecio" onsubmit="return false;">
        <table id="<?php echo TAB_CATPRE; ?>gridCatalogoPrecio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>