<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 09-09-2014 04:09:19 
* Descripcion : indexMisCuentas.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("MISPAGR");
$eliminar = Session::getPermiso("MISPADE");
echo Functions::widgetOpen(array(
        "id"=>MISPA,
        "title"=>LABEL_A120
    )); 
?>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 400px;top:5px">
        <label class="label col col-7"><?php echo LABEL_A71; ?></label>
        <label class="select pull-left">
           <?php
               $datal = misCuentasController::getListadoTipoPanelCuenta();           
                echo Functions::selectHtml(array(
                    'data'=>$datal,
                    'atributes'=>array(
                        'id'=>MISPA.'lst_tipopanelsearch',
                        'name'=>MISPA.'lst_tipopanelsearch',
                        'onchange'=>'misCuentas.getGridMisCuentas();'
                    ),
                    'etiqueta'=>'descripcion',
                    'value'=>'id_tipopanel',
                    'defaultEtiqueta'=>'',
                    'txtAll'=>true
                ));
            ?>
            <i></i>
        </label>
        
    </div>
</div>    
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
              
            </div>
        </div>

    </div>
    <form id="<?php echo MISPA; ?>formGridMisCuentas" name="<?php echo MISPA; ?>formGridMisCuentas">
        <table id="<?php echo MISPA; ?>gridMisCuentas" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>