<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 23-08-2014 22:08:31 
* Descripcion : indexPermisoMunicipal.phtml
* 
* ---------------------------------------
*/

echo Functions::widgetOpen(array(
        "id"=>PERMU,
        "title"=>LABEL_A58
    )); 
?>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">      
    </div>
   <form id="<?php echo PERMU; ?>formGridFichaTecnica" name="<?php echo PERMU; ?>formGridFichaTecnica" onsubmit="return false;">       
        <table id="<?php echo PERMU; ?>gridFichaTecnica" class="table table-striped table-hover table-condensed" style="width:100%"></table>
   </form>
<?php echo Functions::widgetClose(); ?>

<?php 
    $obj = array(
        'id'=>PERMU.'pm',
        'title'=>LABEL_A50       
    );
    echo Functions::widgetOpen($obj); 
?>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">      
    </div>      
    <form id="<?php echo PERMU; ?>formGridPermisoMunicipal" name="<?php echo PERMU; ?>formGridPermisoMunicipal" onsubmit="return false;">
    <table id="<?php echo PERMU; ?>gridPermisoMunicipal" class="table table-striped table-hover table-condensed" style="width:100%;"></table>
    </form>
<?php echo Functions::widgetClose(); ?>                 