<?php
/*
 * Documento   : nuevoFichaTecnica
 * Creado      : 15-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('FITECGR');
$nuevo = Session::getPermiso('TIPANEW');
?>
<form id="<?php echo T102; ?>formFichaTecnica" name="<?php echo T102; ?>formFichaTecnica" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php  echo LABEL_A21; ?></h4>
            </div>
            <!-- style="height: 380px;overflow-y: auto;overflow-x: hidden;" -->
            <div class="modal-body smart-form scroll-form" style="height: 440px;"  >
                <ul class="nav nav-tabs bordered">
                    <li class="active">
                        <a href="#s1" data-toggle="tab"><?php echo LABEL_A24; ?></a>
                    </li>
                    <li >
                        <a href="#s2" data-toggle="tab"><?php echo LABEL_A25; ?></a>
                    </li>
                </ul>
                <div class="tab-content padding-10">
                    <div class="tab-pane fade in active" id="s1">
                         <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_RV18; ?></label>
                                <div class="col col-8">
                                    <label class="select"> 
                                        <?php
                                            $data = fichaTecnicaController::getDepartamentos();                                    
                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>T102.'lst_departamento',
                                                    'name'=>T102.'lst_departamento',
                                                    'onchange'=>'fichaTecnica.getProvincias({
                                                                    idDepartamento: $(\'#'.T102.'lst_departamento\').val(),
                                                                    content: \'#'.T102.'cont-provincias\',
                                                                    idElement: \''.T102.'lst_provincia\',
                                                                    nameElement: \''.T102.'lst_provincia\',
                                                                    contentUbigeo: \'#'.T102.'cont-ubigeo\',
                                                                    idUbigeo: \''.T102.'lst_ubigeo\'
                                                                });'
                                                ),
                                                'etiqueta'=>'departamento',
                                                'value'=>'id_departamento',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_RV19; ?></label>
                                <div class="col col-8">
                                    <label class="select" id="<?php echo T102; ?>cont-provincias"> 
                                        <select id="<?php echo T102; ?>lst_provincia" name="<?php echo T102; ?>lst_provincia">
                                            <option value="">Seleccionar</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_RV20; ?></label>
                                <div class="col col-8">
                                    <label class="select" id="<?php echo T102; ?>cont-ubigeo"> 
                                        <select id="<?php echo T102; ?>lst_ubigeo" name="<?php echo T102; ?>lst_ubigeo">
                                            <option value="">Seleccionar</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                                <div class="row">
                                    <label class="label col col-3"><?php echo LABEL_A26; ?></label>
                                    <div class="col col-8">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-map-marker"></i>
                                            <input type="text" id="<?php echo T102; ?>txt_ubicacion" name="<?php echo T102; ?>txt_ubicacion" >
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A26M; ?></b>
                                        </label>
                                    </div>
                                </div>
                        </section>
                        <!-- Tipo Panel -->
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_A27; ?></label>
                                <div class="col col-8">
                                    <label class="select"> 
                                        <?php
                                            $data = fichaTecnicaController::getTPanelFichaTecnica();
                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>T102.'lst_tipopanel',
                                                    'name'=>T102.'lst_tipopanel'
                                                ),
                                                'etiqueta'=>'descripcion',
                                                'value'=>'id_tipopanel',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                    </label>
                                </div>
                                <?php if ($nuevo['permiso']): ?>
                                <button id="<?php echo T102; ?>btnNew" type="button" onclick="tipoPanel.getNuevoTipoPanel(this,'#<?php echo T102; ?>lst_tipopanel');" class="<?php echo $nuevo['theme'];?>" title="<?php echo $nuevo['accion'];?>">
                                        <i class="<?php echo $nuevo['icono'];?> pd8"></i>
                                </button>
                                <?php endif; ?>
                            </div>
                        </section>                        
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_A28; ?></label>
                                    <div class="col col-3">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-thumb-tack "></i>
                                            <input type="text" id="<?php echo T102; ?>txt_ancho" name="<?php echo T102; ?>txt_ancho"></input>
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A28M; ?></b>
                                        </label>
                                    </div>
                                <label class="label col col-2"><?php echo LABEL_A29; ?></label>
                                    <div class="col col-3">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-thumb-tack "></i>
                                            <input type="text" id="<?php echo T102; ?>txt_alto" name="<?php echo T102; ?>txt_alto"></input>
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A29M; ?></b>
                                        </label>
                                </div>
                            </div>
                        </section>
                        <section>
                                <div class="row">
                                    <label class="label col col-3"><?php echo LABEL_A30; ?></label>
                                    <div class="col col-8">
                                        <label class="textarea textarea-resizable"> 
                                             <i class="icon-append fa fa-align-justify"></i>
                                            <textarea id="<?php echo T102; ?>txt_observacion" name="<?php echo T102; ?>txt_observacion" class="custom-scroll" rows="3"></textarea> 
                                             <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_A30M; ?></b>
					</label>
                                        
                                    </div>
                                </div>
                        </section>                        
                   
                    </div>
                    <!-- Segundo Tab-->
                    <div class="tab-pane fade" id="s2">
                    <section>
                        <div class="row">
                            <label class="label col col-3"><?php echo LABEL_A31; ?></label>
                            <div class="col col-8">
                                <label class="input"> 
                                    <i class="icon-append fa fa-map-marker"></i>
                                    <input type="text" id="<?php echo T102; ?>txt_direccion" name="<?php echo T102; ?>txt_direccion" onKeyPress="return fichaTecnicaScript.enter(event)" >
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo LABEL_A31M; ?></b>
                                </label>                               
                            </div>
                            <button id="<?php echo T102; ?>btnBuscar" type="button" class="btn txt-color-white bg-color-blueDark" onclick="fichaTecnicaScript.codeAddress();">
                                    <i class="fa fa-search" style="padding: 8px"></i>
                            </button>
                        </div>
                    </section>   
                    <section>                        
                            <div id="<?php echo T102; ?>map_canvas" style="width:530px;height:300px;"></div>                                                                             
                    </section>    
                     <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo LABEL_A32; ?></label>
                                    <div class="col col-4">
                                        <label class="input">                                             
                                            <input type="text" id="<?php echo T102; ?>txt_latitud" name="<?php echo T102; ?>txt_latitud" readonly="readonly"></input>                                            
                                        </label>
                                    </div>
                                <label class="label col col-2"><?php echo LABEL_A33; ?></label>
                                    <div class="col col-4">
                                        <label class="input">                                             
                                             <input type="text" id="<?php echo T102; ?>txt_longitud" name="<?php echo T102; ?>txt_longitud" readonly="readonly"></input>                                              
                                        </label>
                                </div>
                            </div>
                        </section>    
                        
                        
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?php if ($grabar['permiso']): ?>
                    <button id="<?php echo T102; ?>btnGfitec" type="submit" class="<?php echo $grabar['theme'];?>">
                        <i class="<?php echo $grabar['icono'];?>"></i> <?php echo $grabar['accion']; ?>
                    </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<script>
    simpleScript.noSubmit('#<?php echo T102; ?>formFichaTecnica');
</script>
<script>
           
    $('.xhelp').tooltip({placement: 'right'});
    $('#<?php echo T102; ?>formFichaTecnica').validate({
        rules: {
            <?php echo T102; ?>txt_ubicacion : {
                required: true,
                minlength: 5
            },
            <?php echo T102; ?>txt_ancho : {
                required: true                
            },        
            <?php echo T102; ?>txt_alto : {
                required: true                
            },        
            <?php echo T102; ?>lst_departamento : {
                required : true
            },
            <?php echo T102; ?>lst_provincia : {
                required : true
            },
            <?php echo T102; ?>lst_ubigeo : {
               required : true
            },
            <?php echo T102; ?>lst_tipopanel : {
                required: true
            },
            <?php echo T102; ?>txt_latitud : {
                required: true
            },
            <?php echo T102; ?>txt_longitud : {
                required: true
            } 
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function() {
            
           fichaTecnica.postNuevoFichaTecnica();
              setTimeout(function() {
                $("#<?php echo T102; ?>txt_direccion").val('Chimbote, Perú');
                $("#<?php echo T102; ?>txt_ancho").val('10');
                $("#<?php echo T102; ?>txt_alto").val('5');                    
              }, 1000);                
        }
    });  
    /*para hacer evento invisible*/
    simpleScript.removeAttr.click({
        container: '#<?php echo T102; ?>formFichaTecnica',
        typeElement: 'button'
    });
            
    $('.nav-tabs a').click(function(){
        setTimeout(function() {            
            fichaTecnicaScript.resetMap(map);            
        }, 1000);                                
    });  
    //Por Defecto:
    $("#<?php echo T102; ?>txt_direccion").val('Chimbote, Perú');
    $("#<?php echo T102; ?>txt_ancho").val('10');
    $("#<?php echo T102; ?>txt_alto").val('5');
    fichaTecnicaScript.googleMap(14,1);
    fichaTecnicaScript.codeAddress();  
    
</script>
