<?php
/*
 * Documento   : nuevoFichaTecnica
 * Creado      : 15-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('FITECGR');
?>
<form id="<?php echo T102; ?>formFichaTecnica" name="<?php echo T102; ?>formFichaTecnica" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php  echo LABEL_A21; ?></h4>
            </div>
            <div class="modal-body smart-form">


                <ul class="nav nav-tabs bordered">


                    <li class="active">
                        <a href="#s1" data-toggle="tab"><?php echo LABEL_A24; ?></a>
                    </li>
                    <li>
                        <a href="#s2" data-toggle="tab"><?php echo LABEL_A25; ?></a>
                    </li>
                </ul>

                <div class="tab-content padding-10">
                    <div class="tab-pane fade in active" id="s1">
                         <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_RV18; ?></label>
                                <div class="col col-8">
                                    <label class="select"> 
                                        <?php
                                            $data = fichaTecnicaController::getDepartamentos();                                    
                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>T102.'lst_departamento',
                                                    'name'=>T102.'lst_departamento',
                                                    'onchange'=>'fichaTecnica.getProvincias({
                                                                    idDepartamento: $(\'#'.T102.'lst_departamento\').val(),
                                                                    content: \'#'.T102.'cont-provincias\',
                                                                    idElement: \''.T102.'lst_provincia\',
                                                                    nameElement: \''.T102.'lst_provincia\',
                                                                    contentUbigeo: \'#'.T102.'cont-ubigeo\',
                                                                    idUbigeo: \''.T102.'lst_ubigeo\'
                                                                });'
                                                ),
                                                'etiqueta'=>'departamento',
                                                'value'=>'id_departamento',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_RV19; ?></label>
                                <div class="col col-8">
                                    <label class="select" id="<?php echo T102; ?>cont-provincias"> 
                                        <select id="<?php echo T102; ?>lst_provincia" name="<?php echo T102; ?>lst_provincia">
                                            <option value="">Seleccionar</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_RV20; ?></label>
                                <div class="col col-8">
                                    <label class="select" id="<?php echo T102; ?>cont-ubigeo"> 
                                        <select id="<?php echo T102; ?>lst_ubigeo" name="<?php echo T102; ?>lst_ubigeo">
                                            <option value="">Seleccionar</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                                <div class="row">
                                    <label class="label col col-3"><?php echo LABEL_A26; ?></label>
                                    <div class="col col-8">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-map-marker"></i>
                                            <input type="text" id="<?php echo T102; ?>txt_ubicacion" name="<?php echo T102; ?>txt_ubicacion" >
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-map-marker  txt-color-teal"></i> <?php echo LABEL_A26M; ?></b>
                                        </label>
                                    </div>
                                </div>
                        </section>
                        <!-- Tipo Panel -->
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_A27; ?></label>
                                <div class="col col-8">
                                    <label class="select"> 
                                        <?php
                                            $data = fichaTecnicaController::getTipoPanel();

                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>T102.'lst_tipopanel',
                                                    'name'=>T102.'lst_tipopanel'
                                                ),
                                                'etiqueta'=>'descripcion',
                                                'value'=>'id_tipopanel',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                    </label>
                                </div>
                            </div>
                        </section>                        
                        <section>
                            <div class="row">
                                <label class="label col col-3"><?php echo LABEL_A28; ?></label>
                                    <div class="col col-3">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-thumb-tack "></i>
                                            <input type="text" id="<?php echo T102; ?>txt_clave" name="<?php echo T102; ?>txt_ancho"></input>
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-thumb-tack  txt-color-teal"></i> <?php echo LABEL_A28M; ?></b>
                                        </label>
                                    </div>
                                <label class="label col col-2"><?php echo LABEL_A29; ?></label>
                                    <div class="col col-3">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-thumb-tack "></i>
                                            <input type="text" id="<?php echo T102; ?>txt_clave" name="<?php echo T102; ?>txt_alto"></input>
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-thumb-tack  txt-color-teal"></i> <?php echo LABEL_A29M; ?></b>
                                        </label>
                                </div>
                            </div>
                        </section>
                        <section>
                                <div class="row">
                                    <label class="label col col-3"><?php echo LABEL_A30; ?></label>
                                    <div class="col col-8">
                                        <label class="textarea textarea-resizable"> 
                                             <i class="icon-append fa fa-map-marker"></i>
                                            <textarea id="<?php echo T102; ?>txt_observacion" name="<?php echo T102; ?>txt_observacion" class="custom-scroll" rows="3"></textarea> 
                                             <b class="tooltip tooltip-top-right"><i class="fa fa-map-marker  txt-color-teal"></i> <?php echo LABEL_A30M; ?></b>
					</label>
                                        
                                    </div>
                                </div>
                        </section>                        
                   
                    </div>
                    <div class="tab-pane fade" id="s2">
                     <!--   <?php //$roles = configurarFichaTecnicasController::getRoles(); ?>
                        <ul style="list-style: none">
                            <?php foreach ($roles as $r): ?>
                                <li class="move-cursor">
                                    <label class="checkbox">
                                        <input type="checkbox" value="<?php echo $r['id_rol']; ?>" name="<?php echo T102; ?>chk_roles[]"><i></i>
                                        <?php echo $r['rol']; ?>
                                    </label>
                                </li> 
                            <?php endforeach; ?>
                        </ul>-->
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?php if ($grabar['permiso']): ?>
                    <button id="<?php echo T102; ?>btnGrabaAccion" type="submit" class="btn txt-color-white bg-color-blueDark">
                        <i class="fa fa-save"></i> <?php echo $grabar['accion']; ?>
                    </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$grabar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo T102; ?>formFichaTecnica');
    </script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement: 'right'});
    $('#<?php echo T102; ?>formFichaTecnica').validate({
        // Rules for form validation
        rules: {
            <?php echo T102; ?>txt_empleado: {
                required: true
            },
            <?php echo T102; ?>txt_email: {
                required: true,
                email: true
            },        
            <?php echo T102; ?>txt_clave: {
                required: true,
                regular: true,
                minlength: 2
            },
            <?php echo T102; ?>txt_empleadodesc: {
                required: true,
                regular: true,
                minlength: 2
            },
            <?php echo T102; ?>chk_roles: {
                required: true
            }        
        },
        // Do not change code below
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function() {
            simpleScript.validaCheckBox({
                id: '#s2',
                msn: 'Seleccione al menos un rol.',
                fnCallback: function(){
                    configurarFichaTecnicas.postNuevoFichaTecnica();
                }
            });
        }
    });
    /*para hacer evento invisible*/
simpleScript.removeAttr.click({
    container: '#<?php echo T102; ?>formFichaTecnica',
    typeElement: 'button'
});
</script>
