<?php

/*
 * Documento   : editarTipoConcepto
 * Creado      : 05-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$editar = Session::getPermiso('ASCUACT');
$data = asignarCuentaController::findAsignarCuenta();
?>
<form id="<?php echo ASCU; ?>formEditAsignarCuenta" name="<?php echo ASCU; ?>formEditAsignarCuenta" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" >
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_A110;?></h4>
            </div>
             <div class="modal-body form-horizontal"> 
                <div class="form-group">
                    <label class="control-label col-md-2" for="prepend"><?php echo LABEL_A112; ?></label>
                    <div class="col-md-10">
                        <div class="input-group-sm">            
                            <input class="form-control" type="text" id="<?php echo ASCU; ?>txt_empleadodesc" name="<?php echo ASCU; ?>txt_empleadodesc" value="<?php echo $data['nombrecompleto']; ?>" disabled="disabled" >                                  
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" for="prepend"><?php echo LABEL_A114; ?></label>
                    <div class="col-md-10">
                        <div class="input-group input-group-sm">            
                            <input class="form-control" type="text" id="<?php echo ASCU; ?>txt_codigo" name="<?php echo ASCU; ?>txt_codigo" value="<?php echo $data['codigo']; ?>" disabled="disabled" >                                  
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" for="prepend"><?php echo LABEL_A113; ?></label>
                    <div class="col-md-10">
                        <div class="input-group-sm">            
                            <input class="form-control" type="text" id="<?php echo ASCU; ?>txt_panel" name="<?php echo ASCU; ?>txt_panel" value="<?php echo $data['catalogo']; ?>" disabled="disabled" >                                  
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" for="prepend"><?php echo LABEL_A111; ?></label>
                    <div class="col-md-10">
                        <div class="input-group input-group-sm">
                            <input class="form-control" type="text" id="<?php echo ASCU; ?>txt_comision" name="<?php echo ASCU; ?>txt_comision" value="<?php echo (100*$data['porcentaje_comision']); ?>">
                        </div>
                    </div>
                </div>             
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="<?php echo ASCU; ?>btnGtac" type="submit" class="<?php echo $editar['theme'];?>">
                    <i class="<?php echo $editar['icono'];?>"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
                 <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$editar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo ASCU; ?>formEditAsignarCuenta');
</script>
<?php endif; ?>
<script>
    $('#<?php echo ASCU; ?>formEditAsignarCuenta').validate({
        rules : {
                <?php echo ASCU; ?>txt_comision : {
                        required : true,                        
                        number: true 
                }
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            asignarCuenta.postEditAsignarCuenta();
        }   
    });
</script>
</form>