<?php
/*
 * Documento   : nuevoTipoConcepto
 * Creado      : 05-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('REGVEGR');

?>
<div id="<?php echo T7; ?>formAdjuntar" name="<?php echo T7; ?>formAdjuntar" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RV25;?></h4>
            </div>
            <div class="modal-body smart-form">
                <form action="<?php echo BASE_URL; ?>personal/registrarVendedor/adjuntarDocumento" class="dropzone" id="mydropzone"></form>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo T7; ?>btnGtconc" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-save"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T7; ?>formAdjuntar');
</script>
<?php endif; ?>
<script>
    Dropzone.autoDiscover = false;
    $("#mydropzone").dropzone({
            //url: "/file/post",
            addRemoveLinks : true,
            maxFilesize: 1,
            dictResponseError: 'Error uploading file!',
            dictDefaultMessage: 'Arrastre aquí una imagen'
    });
</script>
</div>
