<?php
$grabar = Session::getPermiso('REGVEGR');
$doc = $data = Obj::run()->registrarVendedorModel->getAdjuntado();
?>
<div id="<?php echo T7; ?>formAdjuntar" name="<?php echo T7; ?>formAdjuntar" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RV25; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <form class="dropzone" id="mydropzone">
                    <input type="hidden" id="_idPersona" name="_idPersona" value="<?php echo $this->idVendedor; ?>">
                </form>
                <?php if(sizeof($doc) && isset($doc['antecedentes'])):?>
                <a id="<?php echo T7; ?>dow" href="javascript:;" onclick="window.open('<?php echo 'public/files/docs/'.$doc['antecedentes']; ?>','_blank');"><?php echo $doc['antecedentes'];?></a>
                <button id="<?php echo T7; ?>btndow" type="button" class="btn btn-danger" style="padding: 5px" onclick="registrarVendedor.deleteAdjuntar(this,'<?php echo $this->idVendedor; ?>','<?php echo 'public/files/docs/'.$doc['antecedentes']; ?>');"><i class="fa fa-trash-o"></i> Eliminar</button>
                <?php else: ?>
                <a id="<?php echo T7; ?>dow" href="javascript:;"></a>
                <button id="<?php echo T7; ?>btndow" type="button" class="btn btn-danger" style="padding: 5px;display: none"><i class="fa fa-trash-o"></i> Eliminar</button>
                <?php endif; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

    <!-- si no tiene permiso se anula submit desde cualquier input -->
    <?php if (!$grabar['permiso']): ?>
        <script>
            simpleScript.noSubmit('#<?php echo T7; ?>formAdjuntar');
        </script>
    <?php endif; ?>
    <script>
        Dropzone.autoDiscover = false;
        $("#mydropzone").dropzone({
            acceptedFiles: ".pdf",
            url: '<?php echo BASE_URL; ?>personal/registrarVendedor/adjuntarDocumento',
            maxFiles: 1, // Number of files at a time
            maxFilesize: 10, //in MB
            addRemoveLinks: true,
            dictResponseError: 'Error uploading file!',
            dictDefaultMessage: 'Arrastre aquí una imagen',
            complete: function(data){
                $('#<?php echo T7; ?>dow').attr('onclick',"window.open('public/files/docs/<?php echo Aes::de($this->idVendedor); ?>_"+data.name+"','_blank');");
                $('#<?php echo T7; ?>dow').html('<?php echo Aes::de($this->idVendedor); ?>'+data.name); 
                $('#<?php echo T7; ?>btndow').attr('onclick',"registrarVendedor.deleteAdjuntar(this,'<?php echo $this->idVendedor; ?>','public/files/docs/<?php echo Aes::de($this->idVendedor); ?>_"+data.name+"');");
                $('#<?php echo T7; ?>btndow').css('display','block');
            }
        });
    </script>
</div>
