<?php
/*
 * Documento   : buscarEmpleado
 * Creado      : 03-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */

$buscar = Session::getPermiso('REGVEBS');
?>
<form id="<?php echo T7; ?>formBuscarProducto" name="<?php echo T7; ?>formBuscarProducto" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_GNC8; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_GNC7; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <input type="text" id="<?php echo T7; ?>txt_search" name="<?php echo T7; ?>txt_search" placeholder="Escriba y presione enter para buscar" onkeypress="simpleScript.triggerPress('<?php echo T7; ?>btnSubSearchEm',event);"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <div class="well">
                    <table id="<?php echo T7; ?>gridProductosFound" class="table table-striped table-bordered table-hover" style="width:100%"></table>
                </div>
            </div>
            <div class="modal-footer">
                <button id="<?php echo T7; ?>btnSubSearchPro" type="submit" class="hide">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$buscar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo T7; ?>formBuscarProducto');
    </script>
<?php endif; ?>
<script>
    $('#<?php echo T7; ?>formBuscarProducto').validate({
            rules : {
                    <?php echo T7; ?>txt_search : {
                            required : true,
                            regular: true,
                            minlength: 3
                    }
            },

            errorPlacement : function(error, element) {
                    error.insertAfter(element.parent());
            },
                    
            submitHandler: function(){
                registrarVendedor.getMisProductos();
            }   
        });
        
</script>