<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-08-2014 07:08:16 
* Descripcion : formNewCliente.phtml
* ---------------------------------------
*/

/*prefijo: REGCL debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("REGCLGR");

?>
<form id="<?php echo REGCL; ?>formNewCliente" name="<?php echo REGCL; ?>formNewCliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RC1;?></h4>
            </div>
            <div class="modal-body smart-form scroll-form">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RC4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_nombres" name="<?php echo REGCL; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section class="hide">
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RC2; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <select id="<?php echo REGCL; ?>lst_tipodoc" name="<?php echo REGCL; ?>lst_tipodoc">
                                    <option value="">Seleccionar</option>
                                    <option value="RU" selected="selected">RUC</option>
                                    <option value="DN">DNI</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV16; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_nrodocumento" name="<?php echo REGCL; ?>txt_nrodocumento">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV17; ?></b>
                            </label>
                            <div class="note">
                                <strong>Note:</strong> <a href="http://www.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias" target="_blank">Validar RUC en SUNAT</a>
                            </div>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV18; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = clienteController::getDepartamentos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>REGCL.'lst_departamento',
                                            'name'=>REGCL.'lst_departamento',
                                            'onchange'=>'registrarVendedor.getProvincias({
                                                            idDepartamento: $(\'#'.REGCL.'lst_departamento\').val(),
                                                            content: \'#'.REGCL.'cont-provincias\',
                                                            idElement: \''.REGCL.'lst_provincia\',
                                                            nameElement: \''.REGCL.'lst_provincia\',
                                                            contentUbigeo: \'#'.REGCL.'cont-ubigeo\',
                                                            idUbigeo: \''.REGCL.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV19; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo REGCL; ?>cont-provincias"> 
                                <select id="<?php echo REGCL; ?>lst_provincia" name="<?php echo REGCL; ?>lst_provincia">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV20; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo REGCL; ?>cont-ubigeo"> 
                                <select id="<?php echo REGCL; ?>lst_ubigeo" name="<?php echo REGCL; ?>lst_ubigeo">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV9; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_direccion" name="<?php echo REGCL; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo REGCL; ?>btnGrCliente" type="submit" class="<?php echo $grabar['theme'];?>">
                    <i class="<?php echo $grabar['icono'];?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo REGCL; ?>formNewCliente');
</script>
<?php endif; ?>
<script>
    $('#<?php echo REGCL; ?>formNewCliente').validate({
        rules : {
                <?php echo REGCL; ?>txt_nombres : {
                        required : true,
                        minlength: 3
                },
                <?php echo REGCL; ?>txt_nrodocumento:{
                        number: true,
                        maxlength: 13
                },
                <?php echo REGCL; ?>lst_departamento : {
                        required : true
                },
                <?php echo REGCL; ?>lst_provincia : {
                        required : true
                },
                <?php echo REGCL; ?>lst_ubigeo : {
                        required : true
                }
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            cliente.postNewCliente();
        }   
    });
</script>
</form>









