<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-08-2014 07:08:16 
* Descripcion : formNewRepresentante.phtml
* ---------------------------------------
*/

/*prefijo: REGCL debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("REGCLGR");
$buscar = Session::getPermiso('REGCLBS');
?>
<form id="<?php echo REGCL; ?>formNewRepresentante" name="<?php echo REGCL; ?>formNewRepresentante" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RC7;?></h4>
            </div>
            <div class="modal-body smart-form scroll-form">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV3; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_nombres" name="<?php echo REGCL; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV6; ?></b>
                            </label>
                        </div>
                         <?php if ($buscar['permiso']): ?>
                            <button id="<?php echo REGCL; ?>btnBuscar" type="button" class="<?php echo $buscar['theme'];?>" onclick="cliente.getFormPersona(this,'<?php echo LABEL_BSPER; ?>');">
                                <i class="<?php echo $buscar['icono'];?>" style="padding: 8px"></i>
                            </button>
                         <?php  endif; ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_apellidopaterno" name="<?php echo REGCL; ?>txt_apellidopaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV7; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV5; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_apellidomaterno" name="<?php echo REGCL; ?>txt_apellidomaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV8; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section class="hide">
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RC2; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <select id="<?php echo REGCL; ?>lst_tipodoc" name="<?php echo REGCL; ?>lst_tipodoc">
                                    <option value="">Seleccionar</option>
                                    <option value="RU">RUC</option>
                                    <option value="DN" selected="selected">DNI</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV22; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_nrodocumento" name="<?php echo REGCL; ?>txt_nrodocumento">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV17; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV18; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = clienteController::getDepartamentos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>REGCL.'lst_departamento',
                                            'name'=>REGCL.'lst_departamento',
                                            'onchange'=>'registrarVendedor.getProvincias({
                                                            idDepartamento: $(\'#'.REGCL.'lst_departamento\').val(),
                                                            content: \'#'.REGCL.'cont-provincias\',
                                                            idElement: \''.REGCL.'lst_provincia\',
                                                            nameElement: \''.REGCL.'lst_provincia\',
                                                            contentUbigeo: \'#'.REGCL.'cont-ubigeo\',
                                                            idUbigeo: \''.REGCL.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV19; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo REGCL; ?>cont-provincias"> 
                                <select id="<?php echo REGCL; ?>lst_provincia" name="<?php echo REGCL; ?>lst_provincia">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV20; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo REGCL; ?>cont-ubigeo"> 
                                <select id="<?php echo REGCL; ?>lst_ubigeo" name="<?php echo REGCL; ?>lst_ubigeo">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV9; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_direccion" name="<?php echo REGCL; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV10; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_email" name="<?php echo REGCL; ?>txt_email">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV12; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV13; ?></label>
                        <div class="inline-group col col-8">
                            <label class="radio"> 
                                <input name="<?php echo REGCL; ?>rd_sexo" id="<?php echo REGCL; ?>rd_sexoH" checked type="radio" value="H">
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo REGCL; ?>rd_sexo" id="<?php echo REGCL; ?>rd_sexoM" type="radio" value="M">
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV14; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_telefonos" name="<?php echo REGCL; ?>txt_telefonos">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV15; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo REGCL; ?>btnGrRep" type="submit" class="<?php echo $grabar['theme'];?>">
                    <i class="<?php echo $grabar['icono'];?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input, para evitar el submit -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo REGCL; ?>formNewRepresentante');
</script>
<?php endif; ?>
<script>
    $('#<?php echo REGCL; ?>formNewRepresentante').validate({
        rules : {
                <?php echo REGCL; ?>txt_nombres : {
                        required : true,
                        minlength: 3
                },               
                <?php echo REGCL; ?>txt_nrodocumento:{
                        number: true,
                        maxlength: 13
                },
                <?php echo REGCL; ?>lst_departamento : {
                        required : true
                },
                <?php echo REGCL; ?>lst_provincia : {
                        required : true
                },
                <?php echo REGCL; ?>lst_ubigeo : {
                        required : true
                },
                <?php echo REGCL; ?>txt_email : {
                        required : true,
                        email: true
                }      
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            cliente.postNewRepresentante();
        }   
    });
</script>
</form>









