<?php
$editar = Session::getPermiso('REGCLACT');

$data = clienteController::findCliente();
?>
<form id="<?php echo REGCL; ?>formEditCliente" name="<?php echo REGCL; ?>formEditCliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RC3;?></h4>
            </div>
            <div class="modal-body smart-form scroll-form">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RC4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_nombres" name="<?php echo REGCL; ?>txt_nombres" value="<?php echo $data['nombrecompleto']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
<!--                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_apellidopaterno" name="<?php echo REGCL; ?>txt_apellidopaterno" value="<?php echo $data['apellidopaterno']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV7; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV5; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_apellidomaterno" name="<?php echo REGCL; ?>txt_apellidomaterno" value="<?php echo $data['apellidomaterno']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV8; ?></b>
                            </label>
                        </div>
                    </div>
                </section>   -->
                <section class="hide">
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RC2; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <select id="<?php echo REGCL; ?>lst_tipodoc" name="<?php echo REGCL; ?>lst_tipodoc">
                                    <option value="">Seleccionar</option>
                                    <option value="RU" <?php echo ($data['tipodocumento'] == 'RU')?'selected="selected"':'';?> >RUC</option>
                                    <option value="DN" <?php echo ($data['tipodocumento'] == 'DN')?'selected="selected"':'';?> >DNI</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV16; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_nrodocumento" name="<?php echo REGCL; ?>txt_nrodocumento" value="<?php echo $data['numerodocumento']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV17; ?></b>
                            </label>
                            <div class="note">
                                <strong>Note:</strong> <a href="http://www.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias" target="_blank">Validar RUC en SUNAT</a>
                            </div>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV18; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php 
                                    $datax = clienteController::getDepartamentos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$datax,
                                        'atributes'=>array(
                                            'id'=>REGCL.'lst_departamento',
                                            'name'=>REGCL.'lst_departamento',
                                            'onchange'=>'registrarVendedor.getProvincias({
                                                            idDepartamento: $(\'#'.REGCL.'lst_departamento\').val(),
                                                            content: \'#'.REGCL.'cont-provincias\',
                                                            idElement: \''.REGCL.'lst_provincia\',
                                                            nameElement: \''.REGCL.'lst_provincia\',
                                                            contentUbigeo: \'#'.REGCL.'cont-ubigeo\',
                                                            idUbigeo: \''.REGCL.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'defaultEtiqueta'=> substr($data['id_ubigeo'], 0,2),
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV19; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo REGCL; ?>cont-provincias"> 
                                <?php 
                                    $datap = clienteController::getProvinciasEst(substr($data['id_ubigeo'], 0,2));
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$datap,
                                        'atributes'=>array(
                                            'id'=>REGCL.'lst_provincia',
                                            'name'=>REGCL.'lst_provincia',
                                            'onchange'=>'registrarVendedor.getUbigeo({                                                                
                                                            idProvincia: $(\'#'.REGCL.'lst_provincia\').val(),
                                                            content: \'#'.REGCL.'cont-ubigeo\',
                                                            idElement: \''.REGCL.'lst_ubigeo\',
                                                            nameElement: \''.REGCL.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'provincia',
                                        'value'=>'id_provincia',
                                        'defaultEtiqueta'=> substr($data['id_ubigeo'], 0,4),
                                        'txtSelect'=>true
                                    ));
                                ?>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV20; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo REGCL; ?>cont-ubigeo"> 
                                <?php 
                                    $datau = clienteController::getUbigeoEst(substr($data['id_ubigeo'], 0,4));
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$datau,
                                        'atributes'=>array(
                                            'id'=>REGCL.'lst_ubigeo',
                                            'name'=>REGCL.'lst_ubigeo'
                                        ),
                                        'etiqueta'=>'distrito',
                                        'value'=>'id_ubigeo',
                                        'defaultEtiqueta'=> $data['id_ubigeo'],
                                        'txtSelect'=>true
                                    ));
                                ?>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV9; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_direccion" name="<?php echo REGCL; ?>txt_direccion" value="<?php echo $data['direccion']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
<!--                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV10; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_email" name="<?php echo REGCL; ?>txt_email" value="<?php echo $data['email']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV12; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV13; ?></label>
                        <div class="inline-group col col-8">
                            <label class="radio"> 
                                <input name="<?php echo REGCL; ?>rd_sexo" id="<?php echo REGCL; ?>rd_sexoH" checked type="radio" value="H" <?php echo ($data['sexo'] == 'H')?'checked':''; ?>>
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo REGCL; ?>rd_sexo" id="<?php echo REGCL; ?>rd_sexoM" type="radio" value="M" <?php echo ($data['sexo'] == 'M')?'checked':''; ?>>
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>-->
<!--                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV14; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo REGCL; ?>txt_telefonos" name="<?php echo REGCL; ?>txt_telefonos" value="<?php echo $data['telefono']; ?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV15; ?></b>
                            </label>
                        </div>
                    </div>
                </section>-->
                
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="<?php echo REGCL; ?>btnEcli" type="submit" class="<?php echo $editar['theme'];?>">
                    <i class="<?php echo $editar['icono'];?>"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$editar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo REGCL; ?>formEditCliente');
</script>
<?php endif; ?>
<script>
    $('#<?php echo REGCL; ?>formEditCliente').validate({
        rules : {
                <?php echo REGCL; ?>txt_nombres : {
                        required : true,
                        minlength: 3
                },
                <?php echo REGCL; ?>txt_nrodocumento:{
                        number: true,
                        maxlength: 13
                },
                <?php echo REGCL; ?>lst_departamento : {
                        required : true
                },
                <?php echo REGCL; ?>lst_provincia : {
                        required : true
                },
                <?php echo REGCL; ?>lst_ubigeo : {
                        required : true
                }
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            cliente.postEditarCliente();
        }   
    });
</script>
</form>
