<?php
/*
 * Documento   : buscarEmpleado
 * Creado      : 03-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$ruta = AesCtr::de(Formulario::getParam('_ruta'));
?>
<form id="<?php echo T7; ?>formViewFoto" name="<?php echo T7; ?>formViewFoto" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 70%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_GNC28; ?></h4>
            </div>
            <div class="modal-body">
                <div class="well center">
                    <img src="<?php echo $ruta ?>" style=" max-width:100%; width: auto; height: auto; " >
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>