<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 03-09-2014 02:09:26 
* Descripcion : indexSocio.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("REGSONEW");
$eliminar = Session::getPermiso("REGSODEL");
echo Functions::widgetOpen(array(
        "id"=>TAB_SOCIO,
        "title"=>LABEL_A80
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo TAB_SOCIO; ?>btnNewSocio" type="button" onclick="socio.getFormNewSocio(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion']; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo TAB_SOCIO; ?>btnDeleteSocio" type="button" onclick="socio.postDeleteSocioAll(this);" class="<?php echo $eliminar['theme'];?>">
                    <i class="<?php echo $eliminar['icono'];?>"></i> <?php echo $eliminar['accion']; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo TAB_SOCIO; ?>formGridSocio" name="<?php echo TAB_SOCIO; ?>formGridSocio" onsubmit="return false;">
        <table id="<?php echo TAB_SOCIO; ?>gridSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>