<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-09-2014 03:09:14 
* Descripcion : indexPersona.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("REPERNEW");
$eliminar = Session::getPermiso("REPERDEL");
echo Functions::widgetOpen(array(
        "id"=>REPER,
        "title"=>LABEL_A160
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo REPER; ?>btnNewPersona" type="button" onclick="persona.getFormNewPersona(this);" class="<?php echo $nuevo['theme'];?>">
                   <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REPER; ?>btnDeletePersona" type="button" onclick="persona.postDeletePersonaAll(this);" class="<?php echo $eliminar['theme'];?>">
                    <i class="<?php echo $eliminar['icono'];?>"></i> <?php echo $eliminar['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REPER; ?>formGridPersona" name="<?php echo REPER; ?>formGridPersona" onsubmit="return false;">
        <table id="<?php echo REPER; ?>gridPersona" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>