<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-08-2014 07:08:16 
* Descripcion : indexCliente.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("REGCLGR");
$eliminar = Session::getPermiso("REGCLDE");
echo Functions::widgetOpen(array(
        "id"=>REGCL,
        "title"=>"Cliente"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row pull-left" style="width: 49%">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo REGCL; ?>btnNewCliente" type="button" onclick="cliente.getFormNewCliente(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REGCL; ?>btnDeleteCliente" type="button" onclick="cliente.postDeleteClienteAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>
        <div id="<?php echo REGCL; ?>tollRepresentante" class="dt-top-row pull-right" style="width: 49%;display: none">
            <button type="button" class="btn btn-warning" style="position:absolute;margin-top:-38px"><?php echo LABEL_RC6; ?> <span id="<?php echo REGCL; ?>cliente-cont"></span></button>
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo REGCL; ?>btnNewRe" type="button" onclick="cliente.getFormNewRepresentante(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo REGCL; ?>btnDeleteRe" type="button" onclick="cliente.postDeleteRepresentanteAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo REGCL; ?>formGridCliente" name="<?php echo T5; ?>formGridCliente">
        <div class="pull-left" style="width: 49%;border-right: 1px solid #ccc">
            <table id="<?php echo REGCL; ?>gridCliente" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
        </div>
        <div id="<?php echo REGCL; ?>cont-gridrepre" class="pull-right" style="width: 49%;border-left: 1px solid #ccc">
            <table id="<?php echo REGCL; ?>gridRepresentantes" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
        </div>
    </form>
<?php echo Functions::widgetClose(); ?>