<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 19-08-2014 06:08:51 
* Descripcion : indexAsignarCuenta.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("ASCUNEW");
$anular = Session::getPermiso("ASCUAN");
echo Functions::widgetOpen(array(
        "id"=>ASCU,
        "title"=>LABEL_ASC1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo ASCU; ?>btnNewAsignarCuenta" type="button" onclick="asignarCuenta.getFormNewAsignarCuenta(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($anular["permiso"]): ?>
                <button id="<?php echo ASCU; ?>btnDeleteAsignarCuenta" type="button" onclick="asignarCuenta.postAnularAsignarCuentaAll(this);" class="<?php echo $anular['theme'];?>">
                    <i class="<?php echo $anular['icono'];?>"></i> <?php echo $anular["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo ASCU; ?>formGridAsignarCuenta" name="<?php echo ASCU; ?>formGridAsignarCuenta">
        <table id="<?php echo ASCU; ?>gridAsignarCuenta" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>