<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 03-09-2014 02:09:26 
* Descripcion : indexSocio.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("REGSOGR");
$eliminar = Session::getPermiso("REGSODE");
echo Functions::widgetOpen(array(
        "id"=>TAB_SOCIO,
        "title"=>LABEL_A80
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo TAB_SOCIO; ?>btnNewSocio" type="button" onclick="socio.getFormNewSocio(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo TAB_SOCIO; ?>btnDeleteSocio" type="button" onclick="socio.postDeleteSocioAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo TAB_SOCIO; ?>formGridSocio" name="<?php echo TAB_SOCIO; ?>formGridSocio">
        <table id="<?php echo TAB_SOCIO; ?>gridSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>