<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 19-08-2014 06:08:51 
* Descripcion : indexAsignarCuenta.phtml
* ---------------------------------------
*/
$grabar   = Session::getPermiso("ASCUGR");
$eliminar = Session::getPermiso("ASCUDE");
echo Functions::widgetOpen(array(
        "id"=>ASCU,
        "title"=>LABEL_ASC1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($grabar["permiso"]): ?>
                <button id="<?php echo ASCU; ?>btnNewAsignarCuenta" type="button" onclick="asignarCuenta.getFormNewAsignarCuenta(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo ASCU; ?>btnDeleteAsignarCuenta" type="button" onclick="asignarCuenta.postDeleteAsignarCuentaAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo ASCU; ?>formGridAsignarCuenta" name="<?php echo T5; ?>formGridAsignarCuenta">
        <table id="<?php echo ASCU; ?>gridAsignarCuenta" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>