<?php 
$nuevo = Session::getPermiso('REGVENEW');
$eliminar = Session::getPermiso('REGVEDEL');
        
echo Functions::widgetOpen(array(
        'id'=>T7,
        'title'=>LABEL_RV1
    ));
?>
<div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T7; ?>btnNew" type="button" onclick="registrarVendedor.getNuevoVendedor(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T7; ?>btnNew" type="button" onclick="registrarVendedor.postDeleteVendedorAll(this);" class="<?php echo $eliminar['theme'];?>">
                    <i class="<?php echo $eliminar['icono'];?>"></i> <?php echo $eliminar['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T7; ?>formGridVendedor" name="<?php echo T7; ?>formGridVendedor">
        <table id="<?php echo T7; ?>getGridVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>