<?php
$grabar = Session::getPermiso('REGVEGR');
$eliminar = Session::getPermiso('REGVEDE');
        
echo Functions::widgetOpen(array(
        'id'=>T7,
        'title'=>LABEL_RV1
    ));
?>
<div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T7; ?>btnNew" type="button" onclick="registrarVendedor.getNuevoVendedor(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T7; ?>btnNew" type="button" onclick="registrarVendedor.postDeleteVendedorAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-ban"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T7; ?>formGridVendedor" name="<?php echo T7; ?>formGridVendedor">
        <table id="<?php echo T7; ?>getGridVendedor" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>