<?php
/*
 * Documento   : lock
 * Creado      : 17-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$v = $this->vendedor;
$n = $this->nombres;
?>
<form id="fromchange_pass" name="fromchange_pass" class="lockscreen animated flipInY" onsubmit="return false;">
    <div class="logo">
        <h1 class="semi-bold"><img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt=""/> Simple ERP</h1>
    </div>
    <div>
        <img src="<?php echo $rutaLayout['_img']; ?>avatars/sunny-big.png" alt="" width="120" height="120" />
        <div>
            <h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile" style="z-index: 0"></i>
                <?php echo $n; ?> <small>
                <i class="fa fa-lock text-muted"></i> &nbsp;Ingrese su nueva clave</small></h1>
<!--            <p class="text-muted">
                el correo
            </p>-->

            <div class="input-group">
                <input type="hidden" name="txtUser" id="txtUser" value="<?php echo $v ?>">
                <input class="form-control" type="password" placeholder="Contraseña" id="txtNewClave" name="txtNewClave">
                <div class="input-group-btn" style="z-index: 1">
                    <button id="btnEntrar" class="btn btn-primary" type="button" onclick="registrarVendedorScript.validaChangePass();">
                        <i class="fa fa-save"></i> Guardar
                    </button>
                </div>
            </div>
            <p class="no-margin margin-top-5">
            </p>
        </div>

    </div>
    <p class="font-xs margin-top-5">
        <?php echo COPY; ?>

    </p>
</form>
<script>
    function noneEvtMenu(){};
</script>
