<?php
/*
 * Documento   : nuevoConcepto
 * Creado      : 06-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('REGVEGR');
?>
<form id="<?php echo T7; ?>formVendedor" name="<?php echo T7; ?>formVendedor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RV2;?></h4>
            </div>
            <div class="modal-body smart-form" style="height: 350px;overflow-y: auto;overflow-x: hidden;">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV3; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo T7; ?>txt_nombres" name="<?php echo T7; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo T7; ?>txt_apellidopaterno" name="<?php echo T7; ?>txt_apellidopaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV7; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV5; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo T7; ?>txt_apellidomaterno" name="<?php echo T7; ?>txt_apellidomaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV8; ?></b>
                            </label>
                        </div>
                    </div>
                </section>   
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV16; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_nrodocumento" name="<?php echo T7; ?>txt_nrodocumento">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV17; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV23; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_dni" name="<?php echo T7; ?>txt_dni">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV24; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV18; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = registrarVendedorController::getDepartamentos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>T7.'lst_departamento',
                                            'name'=>T7.'lst_departamento',
                                            'onchange'=>'registrarVendedor.getProvincias({
                                                            idDepartamento: $(\'#'.T7.'lst_departamento\').val(),
                                                            content: \'#'.T7.'cont-provincias\',
                                                            idElement: \''.T7.'lst_provincia\',
                                                            nameElement: \''.T7.'lst_provincia\',
                                                            contentUbigeo: \'#'.T7.'cont-ubigeo\',
                                                            idUbigeo: \''.T7.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV19; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo T7; ?>cont-provincias"> 
                                <select id="<?php echo T7; ?>lst_provincia" name="<?php echo T7; ?>lst_provincia">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV20; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo T7; ?>cont-ubigeo"> 
                                <select id="<?php echo T7; ?>lst_ubigeo" name="<?php echo T7; ?>lst_ubigeo">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV9; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_direccion" name="<?php echo T7; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV10; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_email" name="<?php echo T7; ?>txt_email">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV12; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV13; ?></label>
                        <div class="inline-group col col-8">
                            <label class="radio"> 
                                <input name="<?php echo T7; ?>rd_sexo" id="<?php echo T7; ?>rd_sexoH" checked type="radio" value="H">
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo T7; ?>rd_sexo" id="<?php echo T7; ?>rd_sexoM" type="radio" value="M">
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV14; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_telefonos" name="<?php echo T7; ?>txt_telefonos">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV15; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                
                
              
                
               
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo T7; ?>btnGvend" type="submit" class="<?php echo $grabar['theme'];?>">
                    <i class="<?php echo $grabar['icono'];?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T7; ?>formVendedor');
</script>
<?php endif; ?>
<script>
    $('#<?php echo T7; ?>formVendedor').validate({
        rules : {
                <?php echo T7; ?>txt_nombres : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T7; ?>txt_apellidopaterno : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T7; ?>txt_apellidomaterno : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T7; ?>txt_nrodocumento:{                        
                        number: true,
                        maxlength: 12
                },
                <?php echo T7; ?>txt_dni:{                        
                        number: true,
                        maxlength: 8
                },        
                <?php echo T7; ?>lst_departamento : {
                        required : true
                },
                <?php echo T7; ?>lst_provincia : {
                        required : true
                },
                <?php echo T7; ?>lst_ubigeo : {
                        required : true
                },              
                <?php echo T7; ?>txt_email : {
                        required : true,
                        email: true
                }     
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            registrarVendedor.postNuevoVendedor();
        }   
    });
</script>
</form>