<?php
/*
 * Documento   : nuevoConcepto
 * Creado      : 06-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('REGVEGR');
?>
<form id="<?php echo T7; ?>formVendedor" name="<?php echo T7; ?>formVendedor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_RV2;?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV3; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo T7; ?>txt_nombres" name="<?php echo T7; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo T7; ?>txt_apellidopaterno" name="<?php echo T7; ?>txt_apellidopaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV7; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV5; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo T7; ?>txt_apellidomaterno" name="<?php echo T7; ?>txt_apellidomaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_RV8; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                
                
                
                
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV9; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_direccion" name="<?php echo T7; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV10; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T7; ?>txt_email" name="<?php echo T7; ?>txt_txt_email">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV12; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_RV13; ?></label>
                        <div class="inline-group">
                            <label class="radio"> 
                                <input name="checkbox-inline" checked="checked" type="radio">
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="checkbox-inline" type="radio">
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>
                
                
                
                
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_6; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = conceptoController::getTipoConceptos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>T7.'lst_tipoconcento',
                                            'name'=>T7.'lst_tipoconcento'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id_tipo',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_13; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-money"></i>
                                <input type="text" id="<?php echo T7; ?>txt_importe" name="<?php echo T7; ?>txt_importe">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-money txt-color-teal"></i> <?php echo LABEL_14; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo T7; ?>btnGvend" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-save"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T7; ?>formVendedor');
</script>
<?php endif; ?>
<script>
    $('#<?php echo T7; ?>formVendedor').validate({
        // Rules for form validation
        rules : {
                <?php echo T7; ?>lst_tipoconcento : {
                        required : true
                },
                <?php echo T7; ?>txt_descripcion : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T7; ?>txt_importe : {
                        required : true,
                        number: true,
                        maxlength: 10
                }        
        },

        // Do not change code below
        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            concepto.postNuevoConcepto();
        }   
    });
</script>
</form>