<?php

/*
 * Documento   : consultar Panel Alquilado
 * Creado      : 17-09-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$codigoOS = Formulario::getParam('_cod');
?>
<form id="<?php echo MOVOS; ?>formMOV" name="<?php echo MOVOS; ?>formMOV" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:60%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo MOVOS_2.$codigoOS;?></h4>
            </div>
            
             <div class="modal-body smart-form scroll-form" style="height: 440px;"  >
                <ul class="nav nav-tabs bordered">
                    <li class="active">
                        <a href="#s1" data-toggle="tab"><?php echo MOVOS_3; ?></a>
                    </li>
                    <li >
                        <a href="#s2" data-toggle="tab"><?php echo MOVOS_4; ?></a>
                    </li>
                    <li >
                        <a href="#s3" data-toggle="tab"><?php echo MOVOS_5; ?></a>
                    </li>
                    <li >
                        <a href="#s4" data-toggle="tab"><?php echo MOVOS_6; ?></a>
                    </li>
                </ul>
                 <div class="tab-content padding-10">
                     <!-- 1er Tab-->
                    <div class="tab-pane fade in active" id="s1">
                        <div style="margin-top:40px"></div>
                        <table id="<?php echo MOVOS; ?>gridMOVOI" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
                    </div>
                    <!-- 2do Tab-->
                    <div class="tab-pane fade" id="s2">
                        <div style="margin-top:40px"></div>
                        <table id="<?php echo MOVOS; ?>gridMOVCV" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
                    </div>
                    <!-- 3er Tab-->
                    <div class="tab-pane fade" id="s3">
                         <div style="margin-top:40px"></div>
                        <table id="<?php echo MOVOS; ?>gridMOVIN" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
                    </div>
                    <!-- 4to Tab-->
                    <div class="tab-pane fade" id="s4">
                        Resumen
                    </div>
                 </div>
             </div>                                                            
            
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>