<?php
/*
 * Documento   : nuevaAccion
 * Creado      : 07-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('ORSERGR');
$norden = Formulario::getParam('_norden');
?>
<form id="<?php echo GNOSE; ?>formCronograma" name="<?php echo GNOSE; ?>formCronograma" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo GNOSE_3.$norden; ?></h4>
            </div>
            <div class="modal-body smart-form">
               
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo GNOSE_4; ?></label>
                        <div class="col col-3">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo GNOSE; ?>txt_monto" name="<?php echo GNOSE; ?>txt_monto">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GNOSE_5; ?></b>
                            </label>
                        </div>
                        
                        
                        <label class="label col col-2"><?php echo GNOSE_6; ?></label>
                        <div class="col col-3">
                            <label class="input"> 
                                <i class="icon-append fa fa-calendar-o "></i>
                                <input type="text" id="<?php echo GNOSE; ?>txt_fechapago" name="<?php echo GNOSE; ?>txt_fechapago">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo GNOSE_7; ?></b>
                            </label>
                        </div>
                        <?php if($grabar['permiso']):?>
                        <button id="<?php echo GNOSE; ?>btnGrCro" type="submit" class="<?php echo $grabar['theme']; ?>" style="padding: 5px">
                            <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo $grabar['accion']; ?>
                        </button>
                        <?php endif; ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <table id="<?php echo GNOSE; ?>gridCuotas" class="table table-striped table-hover table-condensed" style="width:80%"></table>
                    </div>
                </section>
               
            </div>
            <div class="modal-footer">                
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo GNOSE; ?>formCronograma');
</script>
<?php endif; ?>
<script>
    simpleScript.setEvent.date({
      element: '#<?php echo GNOSE; ?>txt_fechapago' 
    });
$("#<?php echo GNOSE; ?>formCronograma").validate({
    rules : {
        <?php echo GNOSE; ?>txt_monto : {
            required : true,
            number: true     
        },<?php echo GNOSE; ?>txt_fechapago : {
            required : true,
            date: true     
        }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        generarOrden.postCuota();
    }   
});

setTimeout(function(){generarOrden.getGridCuotas();},500 );

</script>
