<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-09-2014 20:09:46 
* Descripcion : formTerminarContrato.phtml
* ---------------------------------------
*/

/*prefijo: TERCO debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("TERCOGR");

$numOS = Formulario::getParam('_numOS');
?>
<form id="<?php echo TERCO; ?>formTerminarContrato" name="<?php echo TERCO; ?>formTerminarContrato" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo TERCO_2.$numOS?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo TERCO_3; ?></label>
                        <div class="col col-8">
                            <label class="textarea"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <textarea id="<?php echo TERCO; ?>txt_obs" name="<?php echo TERCO; ?>txt_obs"></textarea>
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo TERCO_4; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo TERCO; ?>btnGrTerminarContrato" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo TERCO; ?>formTerminarContrato");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo TERCO; ?>formTerminarContrato").validate({
    rules : {
        <?php echo TERCO; ?>txt_obs : {
            required : true,
            minlength: 3
        }
    },

    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        terminarContrato.postTerminarContrato();
    }   
});
</script>