<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-09-2014 18:09:08 
* Descripcion : formComisionVendedor.phtml
* ---------------------------------------
*/

/*prefijo: COMVE debe ser alias en tabla men_menuprincipal*/
$generar = Session::getPermiso("COMVEGN");

$vendedor = Formulario::getParam('_vendedor');
?>
<form id="<?php echo COMVE; ?>formComisionVendedor" name="<?php echo COMVE; ?>formComisionVendedor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo COMVE_3.$vendedor?></h4>
            </div>
            <div class="modal-body"> 
                <?php
                $data = Obj::run()->comisionVendedorController->getOrdenesServicio();
                
                foreach ($data as $key => $value):
                    $idOrden = $value['id_ordenservicio'];
                    $porConfirmar = $value['totales'] - $value['confirmados'];
                    $col = 'red';
                    $label = 'label-danger';
                    if($porConfirmar == 0){
                        $col = 'green';
                        $label = 'label-success';
                    }
                ?>
                <div class="pull-left" style="width: 240px;border: 2px solid <?php echo$col?>;margin-left: 20px">
                    <span class="label label-success"><?php echo COMVE_4.$value['confirmados']?></span>
                    <span class="label label-info"><?php echo COMVE_6.$value['orden_numero']?></span>
                    <br>
                    <!--seleccionar imagenes confirmadas-->
                    <?php
                    $dataIm = Obj::run()->comisionVendedorController->getImagenesConfirmadas($idOrden);
                    foreach ($dataIm as $key => $im):
                    ?>
                    <div class="pull-left" style="width: 104px;height: 104px;border: 2px solid <?php echo$col?>;margin: 7px">
                        <img src="<?php echo BASE_URL?>public/img/confirmacion/<?php echo $im['imagen']?>" width="100px" height="100px">
                    </div>
                    <?php endforeach; ?>
                    <div class="clearfix"></div>
                    <span class="label <?php echo $label?>"><?php echo COMVE_5.$porConfirmar?></span>
                    
                    <!--si se confirmaron se activa boton generar comision-->
                    <?php if($porConfirmar == 0): ?>
                    <button type="button" class="<?php echo $generar["theme"]; ?>" onclick="comisionVendedor.postGenerarComisionVendedor(this,'<?php echo AesCtr::en($idOrden)?>');">
                            <i class="<?php echo $generar["icono"]; ?>"></i> <?php echo $generar["accion"]; ?>
                        </button>
                    <?php else:?>
                        <button type="button" class="<?php echo $generar["theme"]; ?> disabled">
                            <i class="<?php echo $generar["icono"]; ?>"></i> <?php echo $generar["accion"]; ?>
                        </button>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>
                <div class="clearfix"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>