<?php

/*
 * Documento   : nuevaAccion
 * Creado      : 07-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('ORSERGR');
?>
<form id="<?php echo GNOSE; ?>formCronograma" name="<?php echo GNOSE; ?>formCronograma" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo GNOSE_3; ?></h4>
            </div>
            <div class="modal-body smart-form">
               
             
               
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="CRDACbtnGrabaAccion" type="submit" class="<?php echo $grabar['theme']; ?>">
                    <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo GNOSE; ?>formCronograma');
</script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement:'right'});
</script>
