<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-09-2014 20:09:46 
* Descripcion : indexTerminarContrato.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>TERCO,
        "title"=>TERCO_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                
            </div>
        </div>

    </div>
    <form id="<?php echo TERCO; ?>formGridTerminarContrato" name="<?php echo TERCO; ?>formGridTerminarContrato" onsubmit="return false;">
        <table id="<?php echo TERCO; ?>gridTerminarContrato" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>