<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-09-2014 05:09:42 
* Descripcion : indexConfirmarInstalacion.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>COINS,
        "title"=>COINS_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                
            </div>
        </div>

    </div>
    <form id="<?php echo COINS; ?>formGridConfirmarInstalacion" name="<?php echo COINS; ?>formGridConfirmarInstalacion" onsubmit="return false;">
        <table id="<?php echo COINS; ?>gridConfirmarInstalacion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>