<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 09-09-2014 06:09:13 
* Descripcion : indexGenerarOrden.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("GNOSEGR");
$eliminar = Session::getPermiso("GNOSEDE");
echo Functions::widgetOpen(array(
        "id"=>GNOSE,
        "title"=>GNOSE_1
    )); 
?>
<button id="<?php echo GNOSE; ?>btnDowPDF" type="button" class="hide">Descargar</button>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo GNOSE; ?>btnNewGenerarOrden" type="button" onclick="generarOrden.getFormNewGenerarOrden(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo GNOSE; ?>formGridGenerarOrden" name="<?php echo T5; ?>formGridGenerarOrden">
        <table id="<?php echo GNOSE; ?>gridGenerarOrden" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>