<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 25-09-2014 23:09:15 
* Descripcion : indexMovimientosOS.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("MOVOSNEW");
$eliminar = Session::getPermiso("MOVOSDE");
echo Functions::widgetOpen(array(
        "id"=>MOVOS,
        "title"=>"MovimientosOS"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo MOVOS; ?>btnNewMovimientosOS" type="button" onclick="movimientosOS.getFormNewMovimientosOS(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo MOVOS; ?>btnDeleteMovimientosOS" type="button" onclick="movimientosOS.postDeleteMovimientosOSAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo MOVOS; ?>formGridMovimientosOS" name="<?php echo MOVOS; ?>formGridMovimientosOS">
        <table id="<?php echo MOVOS; ?>gridMovimientosOS" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>