<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 24-09-2014 00:09:39 
* Descripcion : indexCompromisoPagar.phtml
* ---------------------------------------
*/
$buscar    = Session::getPermiso("COPAGBS");

echo Functions::widgetOpen(array(
        "id"=>COPAG,
        "title"=>LABEL_GNC29
    )); 
?>
<button id="<?php echo COPAG; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo COPAG; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 250px;top:5px">
        <label class="label col col-1"><?php echo COGEN_2; ?></label>        
        <div class="col col-2" style="padding-left:10px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo COPAG;?>txt_f1" name="<?php echo COPAG;?>txt_f1" value ="01/01/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <label class="label col col-1" style="padding-left:30px;">&nbsp;<?php echo COGEN_3; ?></label>        
        <div class="col col-2" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo COPAG;?>txt_f2" name="<?php echo COPAG;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <label class="label col col-1" style="padding-left:30px;"><?php echo SEGCO_9; ?></label>
        <label class="select pull-left" style="padding-left:20px; ">
            <select id="<?php echo COPAG; ?>lst_estadosearch" name="<?php echo COPAG; ?>lst_estadosearch" onchange="compromisoPagar.getGridCompromisoPagar();">
                <option value="T"><?php echo COPAG_2; ?></option>
                <option value="E"><?php echo COPAG_3; ?></option>
                <option value="P"><?php echo COPAG_4; ?></option>                
            </select>
            <i></i>
        </label>
        <div class="col col-1" style="padding-left:15px;">
            <div class=" ">
                <button id="<?php echo COPAG; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="compromisoPagar.getGridCompromisoPagar();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
    </div>
    
    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">                
            </div>
        </div>

    </div>
    <form id="<?php echo COPAG; ?>formGridCompromisoPagar" name="<?php echo COPAG; ?>formGridCompromisoPagar">
        <table id="<?php echo COPAG; ?>gridCompromisoPagar" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>

<script>
     simpleScript.setEvent.dateRange({
        ini: '#<?php echo COPAG; ?>txt_f1',
        fin: '#<?php echo COPAG; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo COPAG; ?>txt_f2',
        fin: '#<?php echo COPAG; ?>txt_f1',
        opt: 'maxDate'
    });
    
</script>