<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-09-2014 18:09:08 
* Descripcion : indexComisionVendedor.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>COMVE,
        "title"=>COMVE_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                
            </div>
        </div>

    </div>
    <form id="<?php echo COMVE; ?>formGridComisionVendedor" name="<?php echo COMVE; ?>formGridComisionVendedor" onsubmit="return false;">
        <table id="<?php echo COMVE; ?>gridComisionVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>