<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-09-2014 22:09:09 
* Descripcion : indexInstalacion.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("ORINSNEW");
$eliminar = Session::getPermiso("ORINSAN");
echo Functions::widgetOpen(array(
        "id"=>ORINS,
        "title"=>ORINS_1
    )); 
?>
<button id="<?php echo ORINS; ?>btnDowPDF" type="button" class="hide">Descargar</button>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo ORINS; ?>btnNewInstalacion" type="button" onclick="instalacion.getFormNewInstalacion(this);" class="<?php echo $nuevo["theme"]; ?>" title="<?php echo ORINS_2; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo ORINS; ?>btnDeleteInstalacion" type="button" onclick="instalacion.postDeleteInstalacionAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo ORINS; ?>formGridInstalacion" name="<?php echo ORINS; ?>formGridInstalacion">
        <table id="<?php echo ORINS; ?>gridInstalacion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>