<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-09-2014 22:09:43 
* Descripcion : indexSeguimientoPago.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("SEGPANEW");
$eliminar = Session::getPermiso("SEGPADE");
echo Functions::widgetOpen(array(
        "id"=>SEGPA,
        "title"=>SEGPA_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo SEGPA; ?>btnNewSeguimientoPago" type="button" onclick="seguimientoPago.getFormNewSeguimientoPago(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo SEGPA; ?>btnDeleteSeguimientoPago" type="button" onclick="seguimientoPago.postDeleteSeguimientoPagoAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo SEGPA; ?>formGridSeguimientoPago" name="<?php echo SEGPA; ?>formGridSeguimientoPago">
        <table id="<?php echo SEGPA; ?>gridSeguimientoPago" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>