<?php 
echo Functions::widgetOpen(array(
        'id'=>T2.'acciones',
        'title'=>'Acciones'
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <button id="CRDACbtnNew" class="btn txt-color-white bg-color-blueDark" onclick="acciones.getNuevaAccion()"><i class="fa fa-file-o"></i> Nuevo</button>
            </div>
        </div>

    </div>

    <table id="gridAcciones" class="table table-striped table-bordered table-hover" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>