<?php 
$nuevo = Session::getPermiso('ACCGR');

echo Functions::widgetOpen(array(
        'id'=>T2.'acciones',
        'title'=>'Acciones'
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="CRDACbtnNew" class="<?php echo $nuevo['theme']; ?>" onclick="acciones.getNuevaAccion()"><i class="<?php echo $nuevo['icono']; ?>"></i> <?php echo BTN_NUEVO; ?></button>
                <?php endif; ?>
            </div>
        </div>

    </div>

    <table id="gridAcciones" class="table table-striped table-hover has-tickbox" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>