<?php
$data = configurarRolesController::getRol($this->key);

$editar = Session::getPermiso('CROED');
?>
<form id="CRDCRformEditRol" name="CRDCRformEditRol" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Editar Rol</h4>
            </div>
            <div class="modal-body smart-form">
                
                
                
                
                <section>
                    <div class="row">
                        <label class="label col col-2">Rol</label>
                        <div class="col col-10">
                            <label class="input"> 
                                <input type="text" id="CRDCRtxt_rol" name="CRDCRtxt_rol" value="<?php echo $data['rol']; ?>"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-10">
                            <label class="checkbox">
                                <input type="checkbox" <?php echo ($data['activo'] == 1)?'checked':''; ?> name="CRDCRchk_activo" id="CRDCRchk_activo" value="1"></input>
                                <i></i>
                                Activo
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="CRDCRbtnEditaRol" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-edit"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> Cerrar
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar['permiso']): ?>
<script>
    simpleScript.noSubmit('#CRDCRformEditRol');
</script>
<?php endif; ?>