<?php

/*
 * Documento   : nuevaAccion
 * Creado      : 07-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('ACCGR');
?>
<form id="CRDACformNuevaAccion" name="CRDACformNuevaAccion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Nueva Acción</h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2">Acción</label>
                        <div class="col col-10">
                            <label class="input"> 
                                <input type="text" id="CRDACtxt_accion" name="CRDACtxt_accion"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Alias</label>
                        <div class="col col-3">
                            <label class="input"> 
                                <input type="text" id="CRDACtxt_alias" name="CRDACtxt_alias"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Alias debe ser entre 2 y 5 caracteres'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Icono</label>
                        <div class="col col-5">
                            <label class="input"> 
                                <input type="text" id="CRDACtxt_icono" name="CRDACtxt_icono"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Css para el icono del botón.'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Theme</label>
                        <div class="col col-5">
                            <label class="input"> 
                                <input type="text" id="CRDACtxt_theme" name="CRDACtxt_theme"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Css para el diseño del botón.'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="CRDACchk_activo" id="CRDACchk_activo" value="1"></input>
                                <i></i>
                                Activo
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="CRDACbtnGrabaAccion" type="submit" class="<?php echo $grabar['theme']; ?>">
                    <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#CRDACformNuevaAccion');
</script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement:'right'});
</script>
