<?php
/*
 * Documento   : nuevoRol
 * Creado      : 09-jun-2014
 * Autor       : ...
 * Descripcion : 
 */
$grabar = Session::getPermiso('CROGR');

?>
<form id="CRDCRformNuevoRol" name="CRDCRformNuevoRol" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Nuevo Rol</h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2">Rol</label>
                        <div class="col col-10">
                            <label class="input"> 
                                <input type="text" id="CRDCRtxt_rol" name="CRDCRtxt_rol"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-10">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="CRDCRchk_activo" id="CRDCRchk_activo" value="1"></input>
                                <i></i>
                                Activo
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="CRDCRbtnGrabaRol" type="submit" class="<?php echo $grabar['theme']; ?>">
                    <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#CRDCRformNuevoRol');
</script>
<?php endif; ?>