        T100: '<?php echo T100; ?>',
        T101: '<?php echo T101; ?>',
        T102: '<?php echo T102; ?>',        
        PERMU: '<?php echo PERMU; ?>',
        TAB_CATPRE: '<?php echo TAB_CATPRE; ?>',
        TAB_CONPER: '<?php echo TAB_CONPER; ?>',
        TAB_SOCIO: '<?php echo TAB_SOCIO; ?>',
        REINV: '<?php echo REINV; ?>',
        REPRO: '<?php echo REPRO; ?>',
        MISPA: '<?php echo MISPA; ?>',
        PAAL: '<?php echo PAAL; ?>',
        CONTR: '<?php echo CONTR; ?>',
        REPER: '<?php echo REPER; ?>',
        MISCO: '<?php echo MISCO; ?>',
        COXVE: '<?php echo COXVE; ?>',
        COGEN: '<?php echo COGEN; ?>',
        COPAG: '<?php echo COPAG; ?>',
        CALCU: '<?php echo CALCU; ?>',
        MOVOS: '<?php echo MOVOS; ?>',
        SACLI: '<?php echo SACLI; ?>',
        SAVEN: '<?php echo SAVEN; ?>',
        SASOC: '<?php echo SASOC; ?>',
        MOVIM: '<?php echo MOVIM; ?>',
        LICL: '<?php echo LICL; ?>'
    }
};
</script>
