<?php

/*
 * Documento   : consultar Pago Socio
 * Creado      : 13-10-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$nombre = Formulario::getParam('_persona');
?>
<form id="<?php echo SASOC; ?>formPagoSocio" name="<?php echo SASOC; ?>formPagoSocio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:50%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo SASOC_2.' | '.$nombre;?></h4>
            </div>
            <br />
            <table id="<?php echo SASOC; ?>gridPagoSocio" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>