<?php

/*
 * Documento   : consultar Pago Vendedor
 * Creado      : 17-09-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$nombre = Formulario::getParam('_persona');
?>
<button id="<?php echo SAVEN; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<form id="<?php echo SAVEN; ?>formPagoVendedor" name="<?php echo SAVEN; ?>formPagoVendedor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:60%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo SAVEN_4.' | '.$nombre;?></h4>
            </div>
            <br />
            <table id="<?php echo SAVEN; ?>gridPagoVendedor" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>