<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-09-2014 22:09:43 
* Descripcion : formPagarOrden.phtml
* ---------------------------------------
*/

/*prefijo: CROPA debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("CROPAPG");
$reprogramar = Session::getPermiso("CROPARPG");

$norden = Formulario::getParam('_norden');
?>
<form id="<?php echo CROPA; ?>formPagarOrden" name="<?php echo CROPA; ?>formPagarOrden" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 60%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo GNOSE_3.$norden?></h4>
            </div>
            <div class="modal-body"> 
                <table class="table table-striped table-hover dataTable">
                    <thead>
                        <tr>
                            <th class="center"><?php echo SEGPA_2 ?></th>
                            <th class="center"><?php echo SEGPA_3 ?></th>
                            <th class="center" style="width: 25%"><?php echo SEGPA_4 ?></th>
                            <th class="center"><?php echo SEGPA_5 ?></th>
                            <th class="center"><?php echo SEGPA_27 ?></th>
                            <th class="center" style="width: 30%"><?php echo ACTIONS ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            $data = Obj::run()->cronogramaPagoController->getCronograma();
                            $key = 0;
                            foreach ($data as $value):
                                $key++;
                        ?>
                        <tr>
                            <td><?php echo $value['numero_cuota'] ?></td>
                            <td class="right"><?php echo number_format($value['monto_pago'],2) ?></td>
                            <td class="center"><?php echo Functions::cambiaf_a_normal($value['fecha_programada']) ?></td>
                            <td>
                                <!--si es pagado o anulado solo se visualizara la fecha de pago-->
                                <?php if($value['estado'] == 'P' || $value['estado'] == 'A'):?>
                                <?php echo Functions::cambiaf_a_normal($value['fecha_pagoreal']) ?>
                                <?php else:?>
                                <div id="<?php echo $key.CROPA; ?>dfecha"></div>
                                <?php endif; ?>
                            </td>
                            <td class="center">
                                <?php
                                switch ($value['estado']) {
                                    case 'E': #emitido
                                        $estado = '<span class="label label-default">'.CROPA_2.'</span>';
                                        break;
                                    case 'P': #pagado
                                        $estado = '<span class="label label-success">'.CROPA_3.'</span>';
                                        break; 
                                    case 'R': #reprogramado
                                        $estado = '<span class="label label-warning">'.CROPA_4.'</span>';
                                        break;
                                    default:
                                        $estado = '';
                                        break;
                                }
                                echo $estado;
                                ?>
                            </td>
                            <td class="center">
                                <?php
                                /*debe ser diferente de anulado y pagado para mostrar boton pagar*/
                                if($value['estado'] != 'P' && $value['estado'] != 'A'):
                                ?>
                                
                                    <?php if($grabar["permiso"]):?>
                                    <button type="button" class="<?php echo $grabar["theme"]; ?>" style="padding: 5px" onclick="cronogramaPago.getFormPagarOrdenParametros(this,'<?php echo $key?>','<?php echo AesCtr::en($value['id_compromisopago']) ?>','<?php echo $value['numero_cuota'] ?>');">
                                        <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                                    </button>
                                    <?php endif; ?>
                                
                                
                                <?php else: ?>
                                
                                    <!--se muestra el boton desactivado y sin onclick-->
                                    <?php if($grabar["permiso"]):?>
                                    <button type="button" class="<?php echo $grabar["theme"]; ?>" style="padding: 5px" disabled="disabled">
                                        <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                                    </button>
                                    <?php endif; ?>
                                
                                
                                <?php endif; ?>
                                <!--boton reprogramar-->
                                <!--solo se reprograma los que estan en estado E y activaReprogramacion = S-->
                                <?php if($value['estado'] == 'E' && $value['activaReprogramacion'] == 'S'):?>
                                    <?php if($reprogramar['permiso']):?>
                                        <button type="button" class="<?php echo $reprogramar["theme"]; ?>" style="padding: 5px" onclick="cronogramaPago.getFormReprogramar(this,'<?php echo $value['id_compromisopago']?>','<?php echo $value['numero_cuota']?>');">
                                            <i class="<?php echo $reprogramar["icono"]; ?>"></i> <?php echo $reprogramar["accion"]; ?>
                                        </button>
                                    <?php endif; ?>
                                <?php else:?>
                                    <button type="button" class="<?php echo $reprogramar["theme"]; ?> disabled" style="padding: 5px">
                                        <i class="<?php echo $reprogramar["icono"]; ?>"></i> <?php echo $reprogramar["accion"]; ?>
                                    </button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">                
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CROPA; ?>formPagarOrden");
</script>
<?php endif; ?>
<script>
//    simpleScript.setEvent.date({
//      element: '.fechapago' 
//    });
    simpleScript.removeAttr.click({
        container: "#<?php echo CROPA; ?>formPagarOrden",
        typeElement: "button"
    });
</script>