<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-09-2014 22:09:43 
* Descripcion : formPagarVendedor.phtml
* ---------------------------------------
*/

/*prefijo: GPAVE debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("GPAVEGR");
$reprogramar = Session::getPermiso("GPAVERPG");

$vendedor = Formulario::getParam('_vendedor');
$saldo = Formulario::getParam('_saldo');

$dataOS = Obj::run()->pagoVendedorController->getValidaImagenes();

$numCaratulas = $dataOS['_numCaratulas'];
$instaladas = $dataOS['_instaladas'];

?>
<form id="<?php echo GPAVE; ?>formPagarVendedor" name="<?php echo GPAVE; ?>formPagarVendedor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo GPAVE_2.$vendedor?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <!--si caratulas de OS se instalaron se procede al pago-->
                <?php if($numCaratulas == $instaladas):?>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo GPAVE_3; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo GPAVE; ?>txt_serie" name="<?php echo GPAVE; ?>txt_serie">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GPAVE_4; ?></b>
                            </label>
                        </div>
                        
                        <label class="label col col-2"><?php echo GPAVE_5; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo GPAVE; ?>txt_numero" name="<?php echo GPAVE; ?>txt_numero">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GPAVE_6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo GPAVE_8; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input class="right" type="text" id="<?php echo GPAVE; ?>txt_monto" name="<?php echo GPAVE; ?>txt_monto" value="<?php echo str_replace(',','', number_format($saldo,3))?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GPAVE_9; ?></b>
                            </label>
                        </div>
                        
                        <label class="label col col-2"><?php echo GPAVE_7; ?></label>
                        <div class="inline-group col col-4">
                            <label class="radio"> 
                                <input name="<?php echo GPAVE; ?>rd_exonerar" id="<?php echo GPAVE; ?>rd_exonerarS" type="radio" value="S">
                                <i></i> <?php echo LABEL_S?>
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo GPAVE; ?>rd_exonerar" id="<?php echo GPAVE; ?>rd_exonerarN" checked type="radio" value="N">
                                <i></i> <?php echo LABEL_N?>
                            </label>
                        </div>
                    </div>
                </section>
                <?php else:?>
                    <div class="alert alert-danger"><i class="fa fa-warning"></i> 
                        <?php echo GNOSE_23?>
                        Se instalaron <?php echo $instaladas?> de <?php echo $numCaratulas?> caratulas
                    </div>
                <?php endif; ?>
            </div>
            <div class="modal-footer">  
                <?php if($grabar["permiso"] && $numCaratulas == $instaladas):?>
                <button id="<?php echo GPAVE; ?>btnGrPag" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo GPAVE; ?>formPagarVendedor");
</script>
<?php endif; ?>
<script>
    simpleScript.removeAttr.click({
        container: "#<?php echo GPAVE; ?>formPagarVendedor",
        typeElement: "button"
    });
    
    $("#<?php echo GPAVE; ?>formPagarVendedor").validate({
        rules: {
                <?php echo GPAVE; ?>txt_serie: {
                        required: true
                    },
                <?php echo GPAVE; ?>txt_numero: {
                        required: true
                    },
                <?php echo GPAVE; ?>txt_monto: {
                        required: true,
                        number: true
                    }
                },
                errorPlacement: function(error, element) {
                    error.insertAfter(element.parent());
                },
                submitHandler: function() {
                    pagoVendedor.postPagoVendedor();
                }
            });

  
</script>