<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-09-2014 22:09:43 
* Descripcion : formReprogramar.phtml
* ---------------------------------------
*/

/*prefijo: CROPA debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("CROPAGR");

$ncuota = Formulario::getParam('_ncuota');
?>
<form id="<?php echo CROPA; ?>formReprogramar" name="<?php echo CROPA; ?>formReprogramar" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 60%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CROPA_5.$ncuota?></h4>
            </div>
            <div class="modal-body"> 
               
                         
            </div>
            <div class="modal-footer"> 
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo CROPA; ?>btnGrep" type="submit" class="<?php echo $grabar["theme"]; ?>" >
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CROPA; ?>formReprogramar");
</script>
<?php endif; ?>
<script>
//    simpleScript.setEvent.date({
//      element: '.fechapago' 
//    });
    simpleScript.removeAttr.click({
        container: "#<?php echo CROPA; ?>formReprogramar",
        typeElement: "button"
    });
</script>