<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 11-10-2014 22:09:43 
* Descripcion : formPagarSocio.phtml
* ---------------------------------------
*/

/*prefijo: GPASO debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("GPASOGR");
$reprogramar = Session::getPermiso("GPASORPG");

$socio = Formulario::getParam('_socio');
$saldo = Formulario::getParam('_saldo');

?>
<form id="<?php echo GPASO; ?>formPagarSocio" name="<?php echo GPASO; ?>formPagarSocio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo GPAVE_2.$socio?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo GPAVE_3; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo GPASO; ?>txt_serie" name="<?php echo GPASO; ?>txt_serie">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GPAVE_4; ?></b>
                            </label>
                        </div>
                        
                        <label class="label col col-2"><?php echo GPAVE_5; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo GPASO; ?>txt_numero" name="<?php echo GPASO; ?>txt_numero">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GPAVE_6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo GPAVE_8; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input class="right" type="text" id="<?php echo GPASO; ?>txt_monto" name="<?php echo GPASO; ?>txt_monto" value="<?php echo str_replace(',','',  number_format($saldo,5))?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo GPAVE_9; ?></b>
                            </label>
                        </div>
                        <!--
                        <label class="label col col-2"><?php echo GPAVE_7; ?></label>
                        <div class="inline-group col col-4">
                            <label class="radio"> 
                                <input name="<?php echo GPASO; ?>rd_exonerar" id="<?php echo GPASO; ?>rd_exonerarS" type="radio" value="S">
                                <i></i> <?php echo LABEL_S?>
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo GPASO; ?>rd_exonerar" id="<?php echo GPASO; ?>rd_exonerarN" checked type="radio" value="N">
                                <i></i> <?php echo LABEL_N?>
                            </label>
                        </div>
                        -->
                    </div>
                </section>
            </div>
            <div class="modal-footer">  
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo GPASO; ?>btnGrPag" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo GPASO; ?>formPagarSocio");
</script>
<?php endif; ?>
<script>
    simpleScript.removeAttr.click({
        container: "#<?php echo GPASO; ?>formPagarSocio",
        typeElement: "button"
    });
    
    $("#<?php echo GPASO; ?>formPagarSocio").validate({
        rules: {
                <?php echo GPASO; ?>txt_serie: {
                        required: true
                    },
                <?php echo GPASO; ?>txt_numero: {
                        required: true
                    },
                <?php echo GPASO; ?>txt_monto: {
                        required: true,
                        number: true
                    }
                },
                errorPlacement: function(error, element) {
                    error.insertAfter(element.parent());
                },
                submitHandler: function() {
                    pagoSocio.postPagoSocio();
                }
            });

      
</script>