<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 26-09-2014 21:09:55 
* Descripcion : indexSaldoVendedor.phtml
* ---------------------------------------
*/

echo Functions::widgetOpen(array(
        "id"=>SAVEN,
        "title"=>SAVEN_1
    )); 
?>
<button id="<?php echo SAVEN; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo SAVEN; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left: 400px;top:5px">
      <label class="label col col-7"><?php echo SEGCO_9; ?></label>
      <label class="select pull-left">
          <select id="<?php echo SAVEN; ?>lst_estadosearch" name="<?php echo SAVEN; ?>lst_estadosearch" onchange="saldoVendedor.getGridSaldoVendedor();">
              <option value="T"><?php echo SEGCO_4; ?></option>
              <option value="S"  selected="selected"><?php echo SAVEN_2; ?></option>
              <option value="P" ><?php echo SAVEN_3; ?></option>
          </select>
      </label>
  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               
            </div>
        </div>

    </div>
    <form id="<?php echo SAVEN; ?>formGridSaldoVendedor" name="<?php echo SAVEN; ?>formGridSaldoVendedor" onsubmit="return false">
        <table id="<?php echo SAVEN; ?>gridSaldoVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>