<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-09-2014 22:09:43 
* Descripcion : indexSeguimientoPago.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>CROPA,
        "title"=>CROPA_1
    )); 
?>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               
            </div>
        </div>

    </div>
        <table id="<?php echo CROPA; ?>getGridOrdenes" class="table table-striped table-hover table-condensed" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>