<?php 
$buscar    = Session::getPermiso("GPAVEBS");
$anular = Session::getPermiso('GPAVEAN');

echo Functions::widgetOpen(array(
        "id"=>GPAVE,
        "title"=>GPAVE_1
    )); 
?>
<button id="<?php echo GPAVE; ?>btnDowPDF" type="button" class="hide">Descargar</button>

<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left: 250px;top:5px">
          <label class="label col col-7"><?php echo SEGCO_9; ?></label>
        <label class="select pull-left">
            <select style="width: 100px;" id="<?php echo GPAVE; ?>lst_estadosearch" name="<?php echo SAVEN; ?>lst_estadosearch" onchange="pagoVendedor.getGridPagosVendedor();">
                <option value="T"><?php echo SEGCO_4; ?></option>
                <option value="S"  selected="selected"><?php echo SAVEN_2; ?></option>
                <option value="P" ><?php echo SAVEN_3; ?></option>
            </select>
            <i></i>
        </label>          
  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               <?php if($anular['permiso']): ?>
<!--                <button id="<?php echo GPAVE; ?>btnAnular" type="button" onclick="pagoVendedor.postAnularPagoAll(this);" class="<?php echo $anular["theme"]; ?>">
                  <i class="<?php echo $anular['icono'];?>"></i> <?php echo $anular["accion"]; ?>
                </button>-->
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo GPAVE; ?>formGridSaldoVendedor" name="<?php echo GPAVE; ?>formGridSaldoVendedor" onsubmit="return false">
        <table id="<?php echo GPAVE; ?>gridPagosVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>

