<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 11-10-2014 05:10:22 
* Descripcion : indexPagoSocio.phtml
* ---------------------------------------
*/
$buscar    = Session::getPermiso("GPASOBS");
$anular = Session::getPermiso('GPASOAN');
echo Functions::widgetOpen(array(
        "id"=>GPASO,
        "title"=>GPASO_1
    )); 
?>

<button id="<?php echo GPASO; ?>btnDowPDF" type="button" class="hide">Descargar</button>  
<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left: 250px;top:5px">
          <label class="label col col-7"><?php echo SEGCO_9; ?></label>
        <label class="select pull-left">
            <select style="width: 100px;" id="<?php echo GPAVE; ?>lst_estadosearch" name="<?php echo SAVEN; ?>lst_estadosearch" onchange="pagoSocio.getGridPagoSocio();">
                <option value="T"><?php echo SEGCO_4; ?></option>
                <option value="S"  selected="selected"><?php echo SAVEN_2; ?></option>
                <option value="P" ><?php echo SAVEN_3; ?></option>
            </select>
            <i></i>
        </label>
      <label class="label col col-1"><?php echo COGEN_2; ?></label>        
        <div class="col col-2" style="padding-left:5px;"> 
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo GPASO;?>txt_f1" name="<?php echo GPASO;?>txt_f1" value ="01/<?php echo date("m"); ?>/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <label class="label col col-1" style="padding-left: 30px"><?php echo COGEN_3; ?></label>        
        <div class="col col-2" >
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo GPASO;?>txt_f2" name="<?php echo GPASO;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <div class="col col-1" style="padding-left:30px;">
            <div class=" ">
                <button id="<?php echo GPASO; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="pagoSocio.getGridPagoSocio();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               <?php if($anular['permiso']): ?>
<!--                <button id="<?php echo GPASO; ?>btnAnular" type="button" onclick="pagoSocio.postAnularPagoAll(this);" class="<?php echo $anular["theme"]; ?>">
                  <i class="<?php echo $anular['icono'];?>"></i> <?php echo $anular["accion"]; ?>
                </button>-->
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo GPASO; ?>formGridPagoSocio" name="<?php echo GPASO; ?>formGridPagoSocio">
        <table id="<?php echo GPASO; ?>gridPagoSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>

<script>
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo GPASO; ?>txt_f1',
        fin: '#<?php echo GPASO; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo GPASO; ?>txt_f2',
        fin: '#<?php echo GPASO; ?>txt_f1',
        opt: 'maxDate'
    });
            
</script>