<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 26-09-2014 15:09:21 
* Descripcion : indexSaldoCliente.phtml
* ---------------------------------------
*/
echo Functions::widgetOpen(array(
        "id"=>SACLI,
        "title"=>SACLI_1
    )); 
?>
<button id="<?php echo SACLI; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo SACLI; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 400px;top:5px">
      <label class="label col col-7"><?php echo SEGCO_9; ?></label>
      <label class="select pull-left">
          <select id="<?php echo SACLI; ?>lst_estadosearch" name="<?php echo SACLI; ?>lst_estadosearch" onchange="saldoCliente.getGridSaldoCliente();">
              <option value="T"><?php echo SEGCO_4; ?></option>
              <option value="P"><?php echo CROPA_3; ?></option>
              <option value="E"><?php echo CROPA_2; ?></option>
          </select>
      </label>

  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">                
            </div>
        </div>

    </div>
    <form id="<?php echo SACLI; ?>formGridSaldoCliente" name="<?php echo SACLI; ?>formGridSaldoCliente">
        <table id="<?php echo SACLI; ?>gridSaldoCliente" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>