<?php 
$buscar    = Session::getPermiso("GPAVEBS");
echo Functions::widgetOpen(array(
        "id"=>GPAVE,
        "title"=>GPAVE_1
    )); 
?>
<button id="<?php echo GPAVE; ?>btnDowPDF" type="button" class="hide">Descargar</button>

<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left: 250px;top:5px">
      <label class="label col col-1"><?php echo COGEN_2; ?></label>        
        <div class="col col-1">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo GPAVE;?>txt_f1" name="<?php echo GPAVE;?>txt_f1" value ="" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <label class="label col col-2" style="padding-left: 110px"><?php echo COGEN_3; ?></label>        
        <div class="col col-2" style="padding-left: 30px">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo GPAVE;?>txt_f2" name="<?php echo GPAVE;?>txt_f2" value ="" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <div class="col col-1" style="padding-left:50px;">
            <div class=" ">
                <button id="<?php echo GPAVE; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="pagoVendedor.getGridPagosVendedor();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               
            </div>
        </div>

    </div>
    <form id="<?php echo GPAVE; ?>formGridSaldoVendedor" name="<?php echo GPAVE; ?>formGridSaldoVendedor" onsubmit="return false">
        <table id="<?php echo GPAVE; ?>gridPagosVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>

<script>
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo GPAVE; ?>txt_f1',
        fin: '#<?php echo GPAVE; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo GPAVE; ?>txt_f2',
        fin: '#<?php echo GPAVE; ?>txt_f1',
        opt: 'maxDate'
    });
        
</script>