<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 29-09-2014 17:09:58 
* Descripcion : indexCronogramaCliente.phtml
* ---------------------------------------
*/

echo Functions::widgetOpen(array(
        "id"=>CRPG,
        "title"=>CRPG_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               
            </div>
        </div>

    </div>
    <form id="<?php echo CRPG; ?>formGridCronogramaCliente" name="<?php echo CRPG; ?>formGridCronogramaCliente" onsubmit="return false">
        <table id="<?php echo CRPG; ?>gridCronogramaCliente" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>