<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 11-10-2014 05:10:22 
* Descripcion : indexPagoSocio.phtml
* ---------------------------------------
*/
$buscar    = Session::getPermiso("GPASOBS");
$anular = Session::getPermiso('GPASOAN');
$generar    = Session::getPermiso("GPASOGN");
echo Functions::widgetOpen(array(
        "id"=>GPASO,
        "title"=>GPASO_1
    )); 
?>

<button id="<?php echo GPASO; ?>btnDowPDF" type="button" class="hide">Descargar</button>  
<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left: 250px;top:5px">
          <label class="label col col-7"><?php echo SEGCO_9; ?></label>
        <label class="select pull-left">
            <select style="width: 100px;" id="<?php echo GPASO; ?>lst_estadosearch" name="<?php echo GPASO; ?>lst_estadosearch" onchange="pagoSocio.getGridPagoSocio();">
                <option value="T"><?php echo SEGCO_4; ?></option>
                <option value="S"  selected="selected"><?php echo SAVEN_2; ?></option>
                <option value="P" ><?php echo SAVEN_3; ?></option>
            </select>
            <i></i>
        </label>          
  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               <?php if($generar['permiso']): ?>
                <button id="<?php echo GPASO; ?>btnNew" type="button" onclick="index.postGenerarUtilidadSocioBtn();" class="btn txt-color-white bg-color-blueDark">
                    <i class="<?php echo $generar['icono']; ?>"></i> <?php echo $generar['accion']; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo GPASO; ?>formGridPagoSocio" name="<?php echo GPASO; ?>formGridPagoSocio" onsubmit="return false;">
        <table id="<?php echo GPASO; ?>gridPagoSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>
