<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 26-09-2014 23:09:38 
* Descripcion : indexSaldoSocio.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("SASOCNEW");
$eliminar = Session::getPermiso("SASOCDE");
echo Functions::widgetOpen(array(
        "id"=>SASOC,
        "title"=>SASOC_1
    )); 
?>

<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left: 400px;top:5px">
      <label class="label col col-7"><?php echo SEGCO_9; ?></label>
      <label class="select pull-left">
          <select id="<?php echo SASOC; ?>lst_estadosearch" name="<?php echo SASOC; ?>lst_estadosearch" onchange="saldoSocio.getGridSaldoSocio();">
              <option value="T"><?php echo SEGCO_4; ?></option>
              <option value="S"  selected="selected"><?php echo SAVEN_2; ?></option>
              <option value="P" ><?php echo SAVEN_3; ?></option>
          </select>
      </label>
  </div>    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
            </div>
        </div>
    </div>
    <form id="<?php echo SASOC; ?>formGridSaldoSocio" name="<?php echo SASOC; ?>formGridSaldoSocio" onsubmit="return false">
        <table id="<?php echo SASOC; ?>gridSaldoSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>