<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 26-09-2014 23:09:38 
* Descripcion : indexSaldoSocio.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("SASOCNEW");
$eliminar = Session::getPermiso("SASOCDE");
echo Functions::widgetOpen(array(
        "id"=>SASOC,
        "title"=>"SaldoSocio"
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo SASOC; ?>btnNewSaldoSocio" type="button" onclick="saldoSocio.getFormNewSaldoSocio(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo SASOC; ?>btnDeleteSaldoSocio" type="button" onclick="saldoSocio.postDeleteSaldoSocioAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo SASOC; ?>formGridSaldoSocio" name="<?php echo SASOC; ?>formGridSaldoSocio">
        <table id="<?php echo SASOC; ?>gridSaldoSocio" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>