<?php 
$nuevo = Session::getPermiso('TICNNEW');
$eliminar = Session::getPermiso('TICNDEL');
        
echo Functions::widgetOpen(array(
        'id'=>T5.'tipoconceptos',
        'title'=>LABEL_6
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T5; ?>btnNew" type="button" onclick="tipoConcepto.getNuevoTipoConcepto(this,'');" class="<?php echo $nuevo['theme']; ?>">
                    <i class="<?php echo $nuevo['icono']; ?>"></i> <?php echo $nuevo['accion']; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T5; ?>btnDelete" type="button" onclick="tipoConcepto.postDeleteTipoConceptoAll(this);" class="<?php echo $eliminar['theme']; ?>">
                    <i class="<?php echo $eliminar['icono']; ?>"></i> <?php echo $eliminar['accion']; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T5; ?>formGridTipoConcepto" name="<?php echo T5; ?>formGridTipoConcepto" onsubmit="return false">
        <table id="<?php echo T5; ?>gridTipoConceptos" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>