<?php
$grabar = Session::getPermiso('CONCGR');
$eliminar = Session::getPermiso('CONCDE');
        
echo Functions::widgetOpen(array(
        'id'=>T6,
        'title'=>LABEL_11
    ));
?>
<div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T6; ?>btnNew" type="button" onclick="concepto.getNuevoConcepto(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T6; ?>btnNew" type="button" onclick="concepto.postDeleteConceptoAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T6; ?>formGridConcepto" name="<?php echo T6; ?>formGridConcepto">
        <table id="<?php echo T6; ?>gridConceptos" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>