<?php 
$grabar = Session::getPermiso('TICNGR');
$eliminar = Session::getPermiso('TICNDE');
        
echo Functions::widgetOpen(array(
        'id'=>T5.'tipoconceptos',
        'title'=>LABEL_6
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T5; ?>btnNew" type="button" onclick="tipoConcepto.getNuevoTipoConcepto(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T5; ?>btnNew" type="button" onclick="tipoConcepto.postDeleteTipoConceptoAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-ban"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T5; ?>formGridTipoConcepto" name="<?php echo T5; ?>formGridTipoConcepto">
        <table id="<?php echo T5; ?>gridTipoConceptos" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>