<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 09-12-2014 17:12:42 
* Descripcion : indexMensajes.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("PMSJNEW");
$eliminar = Session::getPermiso("PMSJDEL");

echo Functions::widgetOpen(array(
        "id"=>PMSJ,
        "title"=>PMSJ_01
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo PMSJ; ?>btnNewMensajes" type="button" onclick="mensajesPlantilla.getFormNewMensajes(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo PMSJ; ?>btnDeleteMensajes" type="button" onclick="mensajesPlantilla.postDeleteMensajesAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo PMSJ; ?>formGridMensajes" name="<?php echo PMSJ; ?>formGridMensajes" onsubmit="return false"  >
        <table id="<?php echo PMSJ; ?>gridMensajes" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
        
<?php echo Functions::widgetClose(); ?>