<?php
$nuevo = Session::getPermiso('CONCNEW');
$eliminar = Session::getPermiso('CONCDEL');
        
echo Functions::widgetOpen(array(
        'id'=>T6,
        'title'=>LABEL_11
    ));
?>
<div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T6; ?>btnNew" type="button" onclick="concepto.getNuevoConcepto(this);" class="<?php echo $nuevo['theme']; ?>">
                    <i class="<?php echo $nuevo['icono']; ?>"></i> <?php echo $nuevo['accion']; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T6; ?>btnNew" type="button" onclick="concepto.postDeleteConceptoAll(this);" class="<?php echo $eliminar['theme']; ?>">
                    <i class="<?php echo $eliminar['icono']; ?>"></i> <?php echo $eliminar['accion']; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
<form id="<?php echo T6; ?>formGridConcepto" name="<?php echo T6; ?>formGridConcepto" onsubmit="return false" >
        <table id="<?php echo T6; ?>gridConceptos" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>