<?php 
$grabar = Session::getPermiso('PARMGR');
$eliminar = Session::getPermiso('PARMDE');
        
echo Functions::widgetOpen(array(
        'id'=>T100,
        'title'=>LABEL_A1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T100; ?>btnNew" type="button" onclick="parametro.getNuevoParametro(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-file-o"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T100; ?>btnNew" type="button" onclick="parametro.postDeleteParametroAll(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-ban"></i> <?php echo BTN_DELETE; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T100; ?>formGridParametro" name="<?php echo T100; ?>formGridParametro">
        <table id="<?php echo T100; ?>gridParametro" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>