<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 12-09-2014 17:09:13 
* Descripcion : indexContrato.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("CONTRNEW");
$eliminar = Session::getPermiso("CONTRDEL");
echo Functions::widgetOpen(array(
        "id"=>CONTR,
        "title"=>LABEL_A150
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo CONTR; ?>btnNewContrato" type="button" onclick="contrato.getFormNewContrato();" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo CONTR; ?>btnDeleteContrato" type="button" onclick="contrato.postDeleteContratoAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo CONTR; ?>formGridContrato" name="<?php echo CONTR; ?>formGridContrato">
        <table id="<?php echo CONTR; ?>gridContrato" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>