<?php 
$nuevo = Session::getPermiso('PARMNEW');
$eliminar = Session::getPermiso('PARMDEL');

echo Functions::widgetOpen(array(
        'id'=>T100,
        'title'=>LABEL_A1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T100; ?>btnNew" type="button" onclick="parametro.getNuevoParametro(this);" class="<?php echo $nuevo['theme']; ?>">
                    <i class="<?php echo $nuevo['icono']; ?>"></i> <?php echo $nuevo['accion']; ?>
                </button>
                <?php endif; ?>
                <?php if($eliminar['permiso']): ?>
                <button id="<?php echo T100; ?>btnNew" type="button" onclick="parametro.postDeleteParametroAll(this);" class="<?php echo $eliminar['theme']; ?>">
                    <i class="<?php echo $eliminar['icono']; ?>"></i> <?php echo $eliminar['accion'];  ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo T100; ?>formGridParametro" name="<?php echo T100; ?>formGridParametro">
        <table id="<?php echo T100; ?>gridParametro" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>