<?php 
/*prefijo: VGEVE debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso('VGEVEACT');
$agregar = Session::getPermiso('VGEVEAG');
$buscar = Session::getPermiso('VGEVEBS');
$nuevo = Session::getPermiso('VRECLNEW');

echo Functions::widgetOpen(array(
    'id' => VGEVE.'_COTIZACION',
    'title' => VGEVE_3,
    'padding' => true,
    'wizard' => true
));

$datac = Obj::run()->generarVentaController->getFindCotizacion();

$datad = Obj::run()->generarVentaController->getFindCotizacionD();
$dataCodigo = generarVentaController::getCodigo();
$codigo = $dataCodigo['cod'];

?>
<div class="row">
    <form id="<?php echo VGEVE; ?>formNewGenerarVenta2" name="<?php echo VGEVE; ?>formNewGenerarVenta2" novalidate="novalidate">
        <div id="<?php echo VGEVE; ?>bootstrap-wizard-1" class="col-sm-12">
            <div class="form-bootstrapWizard">
                <ul class="bootstrapWizard form-wizard">
                   <li class="active" data-target="#step1">
                        <a href="#<?php echo VGEVE; ?>v2tab1" data-toggle="tab"> <span class="step">1</span> <span class="title"><?php echo VGEVETAB1?></span> </a>
                    </li>
                    <li data-target="#step2">
                        <a href="#<?php echo VGEVE; ?>v2tab2" data-toggle="tab"> <span class="step">2</span> <span class="title"><?php echo VGEVETAB2?></span> </a>
                    </li>
                    <li data-target="#step3">
                        <a href="#<?php echo VGEVE; ?>v2tab3" data-toggle="tab"> <span class="step">3</span> <span class="title"><?php echo VGEVETAB3?></span> </a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            
            <!--INI TAB-CONTENT-->
            <div class="tab-content">
                
                
                <!--INICIO TAB1-->
                 <div class="tab-pane active form-horizontal" id="<?php echo VGEVE; ?>v2tab1">
                    <br><br>
                    <h3><strong><?php echo LABEL_GNC19; ?></strong> - <?php echo VGEVETAB1; ?></h3>
  
                    <div class="form-group">
                        <label class="control-label col-md-2" for="prepend"><?php echo LABEL_GNC3; ?></label>
                        <div class="col-md-8">
                            <div class="input-group input-group-sm">
                                <input type="hidden" id="<?php echo VGEVE; ?>txt_idpersona" name="<?php echo VGEVE; ?>txt_idpersona" value="<?php echo Aes::en($datac['id_persona']);?>">
                                <input class="form-control" type="text" id="<?php echo VGEVE; ?>txt_cliente" name="<?php echo VGEVE; ?>txt_cliente" value="<?php echo $datac['cliente'];?>" readonly>
                                <span class="input-group-btn">
                                    <?php if ($buscar['permiso']): ?>
                                        <button class="<?php echo $buscar['theme'];?>" type="button" disabled><i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?></button>
                                    <?php endif; ?>
                                     <?php if($nuevo['permiso']): ?>
                                        <button id="<?php echo VGEVE; ?>newCliente" type="button"  class="<?php echo $nuevo['theme'];?>" title="Nuevo Cliente" disabled>
                                             <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                                        </button>
                                        <?php endif; ?>    
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                       <label class="control-label col-md-2" for="prepend"><?php echo VGEVE_7; ?></label>
                       <div class="col-md-2">
                           <div class="input">
                               <input class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_codImpr" name="<?php echo VGEVE; ?>txt_codImpr" maxlength="7" value="<?php echo $codigo;?>"  >
                           </div>
                       </div>
                    </div>
                    <div class="form-group">                      
                        <label class="control-label col-md-2" for="prepend"><?php echo VGEVE_8; ?></label>
                        <div class="col-md-2">                           
                            <label class="select"> 
                                <?php
                                    $dataDoc = Array (
                                            Array ( 'id' => 'F', 'descripcion' => LABEL_VGEVE1 ),
                                            Array ( 'id' => 'B', 'descripcion' => LABEL_VGEVE2),
                                            Array ( 'id' => 'R', 'descripcion' => LABEL_VGEVE3)
                                    );                                   
                                    echo Functions::selectHtml(array(
                                        'data'=>$dataDoc,
                                        'atributes'=>array(
                                            'id'=>VGEVE.'lst_tipoDoc',
                                            'name'=>VGEVE.'lst_tipoDoc'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>"R",
                                        'txtSelect'=>false
                                    ));
                                ?><i></i>
                            </label>                            
                        </div>
                        <label class="control-label col-md-1" for="prepend"><?php echo VGEVE_5; ?></label>
                        <div class="col-md-3">
                            <label class="select"> 
                                <?php                               
                                    $dataMoneda = vproductoController::getMoneda();                              
                                    echo Functions::selectHtml(array(
                                        'data'=>$dataMoneda,
                                        'atributes'=>array(
                                            'id'=>VGEVE.'lst_moneda',
                                            'name'=>VGEVE.'lst_moneda'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>$datac['id_moneda'],
                                        'txtSelect'=>false
                                    ));
                                ?><i></i>
                            </label> 
                        </div>         
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label col-md-2" for="prepend"><?php echo VGEVE_4; ?></label>
                        <div class="col-md-2">
                            <div class="input">
                                <input class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_fecha" name="<?php echo VGEVE; ?>txt_fecha" value="<?php echo date("d/m/Y");?>" readonly >
                            </div>
                        </div>
                       
                                                   
                    </div>
                </div>
                <!--FIN TAB1-->
                
                <!--INICIO TAB2-->
                <div class="tab-pane" id="<?php echo VGEVE; ?>v2tab2">
                   <br>
                    <h3><strong><?php echo LABEL_GNC21; ?></strong> - <?php echo VGEVETAB2; ?></h3>

                    <div class="form-group">
                        <label class="control-label col-md-2" for="prepend">
                           
                        </label>
                    </div>
                    <br><br>
                    <div style="padding: 10px">
                        <div class="si-access" style="min-height: 200px; max-height: auto;">
                             <table id="<?php echo VGEVE; ?>gridProductos" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">
                                <thead>
                                    <th style="width:39%"><?php echo VGEVE_9?></th>
                                    <th style="width:9%"><?php echo VGEVE_10?></th>
                                    <th style="width:9%"><?php echo VGEVE_11?></th>
                                    <th style="width:8%"><?php echo VGEVE_12?></th>
                                    <th style="width:8%"><?php echo VGEVE_22?></th>
                                    <th style="width:10%"><?php echo VGEVE_13?></th>
                                    <th style="width:10%"><?php echo VGEVE_14?></th>
                                    <th style="width:1%">...</th>
                                </thead>
                                <tbody>
                                    <?php 
                                        $key = 0;
                                        foreach ($datad as $value):
                                            $key++;
                                    ?>
                                    <tr id="<?php echo VGEVE?>tr_<?php echo $value['id_producto']?>">
                                        <td>
                                            <input type="hidden" id="<?php echo VGEVE.$key?>hhddIdProducto" name="<?php echo VGEVE?>hhddIdProducto[]" value="<?php echo AesCtr::en($value['id_producto'])?>">
                                            <input type="hidden" id="<?php echo VGEVE.$key?>hhddIGV" name="<?php echo VGEVE?>hhddIGV[]" value="<?php echo $value['igv']?>">
                                            <input type="hidden" id="<?php echo VGEVE.$key?>hhddIncl" name="<?php echo VGEVE?>hhddIncl[]" value="<?php echo $value['incligv']?>">
                                            <?php echo $value['descripcion']?>
                                        </td>
                                        <td>                                            
                                            <?php echo $value['sigla']?>
                                        </td>
                                        <td class="right">
                                            <label class="input"><input type="text" id="<?php echo VGEVE.$key?>txt_cantidad1" name="<?php echo VGEVE?>txt_cantidad1[]" value="<?php echo number_format($value['cantidad_1'])?>" style="text-align:right" data-index="<?php echo $key?>"></label>
                                        </td>
                                        <td class="right">
                                            <label class="input"><input type="text" id="<?php echo VGEVE.$key?>txt_cantidad2" name="<?php echo VGEVE?>txt_cantidad2[]" value="<?php echo number_format($value['cantidad_2'])?>" style="text-align:right" data-index="<?php echo $key?>"></label>
                                        </td>
                                        <td class="right">
                                           <?php echo number_format( $value['cantidad_real'],2) ?>
                                        </td>
                                        <td class="right">
                                            <label class="input"><input type="text" id="<?php echo VGEVE.$key?>txt_precio" name="<?php echo VGEVE?>txt_precio[]" value="<?php echo number_format($value['precio'],2)?>" data-value="<?php echo $value['precio']?>" data-index="<?php echo $key?>" style="text-align:right"></label>
                                        </td>
                                        <td class="right">
                                            <?php echo number_format($value['total_impuesto'],2)?>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger btn-xs" onclick="generarVentaScript.removeItem('<?php echo AesCtr::en($value['id_producto'])?>');"><i class="fa fa-trash-o"></i></a>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group" style="margin-top:5px">
                            <div class="col-md-2 pull-right">
                                <div class="input">
                                    <input class="form-control right" type="text" id="<?php echo VGEVE; ?>txt_total" name="<?php echo VGEVE; ?>txt_total" readonly>
                                </div>
                            </div>
                            <label class="control-label col-md-2 pull-right" for="prepend"><?php echo LABEL_T; ?></label>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <!--FIN TAB2-->
                
                <!--INICIO TAB3-->
                <div class="tab-pane form-horizontal" id="<?php echo VGEVE; ?>v2tab3">
                    <br>
                    <h3><strong><?php echo LABEL_GNC23; ?></strong><?php echo LABEL_GNC24; ?></h3>
                    <div class="form-group">
                       <label class="control-label col-md-2" for="prepend"><?php echo VGEVE_24; ?></label>
                       <div class="col-md-2">
                           <div class="input">
                               <input style="text-align: right" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_totalPago" name="<?php echo VGEVE; ?>txt_totalPago" readonly  >
                           </div>
                       </div>
                    </div>
                    
                    <div class="form-group">
                       <label class="control-label col-md-2" for="prepend"><?php echo VGEVE_25; ?></label>
                       <div class="col-md-2">
                           <div class="input">
                               <input style="text-align: right" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_pago" name="<?php echo VGEVE; ?>txt_pago"   >
                           </div>
                       </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="prepend"><?php echo LABEL_GNC25; ?></label>
                        <div class="col-md-9">
                            <div class="textarea">
                                <textarea class="form-control" id="<?php echo VGEVE; ?>txt_obs" name="<?php echo VGEVE; ?>txt_obs"><?php echo $datac['observacion']?></textarea>
                            </div>
                        </div>
                    </div>
                    
                    <h4 class="text-center">
                        <button id="<?php echo VGEVE; ?>btnGrVenta2" type="button" class="btn btn-success btn-large" onclick="generarVenta.postNewGenerarVenta2();">    
                            <i class="fa fa-plus-circle fa-lg"></i>
                            <?php echo VGEVE_23; ?>
                        </button>
                    </h4>
                    <br>
                    <br>
                </div>
                <!--FIN TAB3-->
                
                <div class="form-actions">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul class="pager wizard no-margin no-border">
                                <!--<li class="previous first disabled">
                                <a href="javascript:void(0);" class="btn btn-lg btn-default"> First </a>
                                </li>-->
                                <li class="previous disabled">
                                    <a href="javascript:void(0);" class="btn btn-lg btn-default"> <?php echo LABEL_ANT?> </a>
                                </li>
                                <!--<li class="next last">
                                <a href="javascript:void(0);" class="btn btn-lg btn-primary"> Last </a>
                                </li>-->
                                <li class="next">
                                    <a href="javascript:void(0);" class="btn btn-lg txt-color-darken"> <?php echo LABEL_SIG?> </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                
            </div>
            <!--FIN TAB-CONTENT-->
            
        </div>
<script>
     /*   simpleScript.setEvent.date({
            element: '#<?php echo VGEVE; ?>txt_fecha' 
        });*/
        $("#<?php echo VGEVE; ?>formNewGenerarVenta2 select").addClass('form-control');
        
            var $validator = $("#<?php echo VGEVE; ?>formNewGenerarVenta2").validate({
                rules: {
                    <?php echo VGEVE; ?>txt_cliente: {
                        required: true
                    },
                    <?php echo VGEVE; ?>txt_codImpr: {
                        required: true,
                        number:true
                    },  
                    <?php echo VGEVE; ?>lst_tipoDoc: {
                        required: true
                    },  
                    <?php echo VGEVE; ?>lst_moneda: {
                        required: true
                    },                                                                       
                    <?php echo VGEVE; ?>txt_fecha: {
                        required: true,
                        date: true
                    }      
                },
                highlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
                },
                errorElement: 'span',
                errorClass: 'help-block',
                errorPlacement: function(error, element) {
                    if (element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
            
            var baseItemSelector = 'li:has([data-toggle="tab"])';
            
            $('#<?php echo VGEVE; ?>bootstrap-wizard-1').bootstrapWizard({
                tabClass: 'form-wizard',
                onTabClick: function(tab, navigation, index) {
                    //desactivar tabs
                    return false;
                },
                onTabChange: function(tab, navigation, index) {
                    
                },
                onNext: function(tab, navigation, index) {
                    var $valid = $("#<?php echo VGEVE; ?>formNewGenerarVenta2").valid();
                    if(index === 1){
                        if (!$valid) {
                            $validator.focusInvalid();
                            return false;
                        }
                        /*marca el paso como completado*/
                        $('#<?php echo VGEVE; ?>bootstrap-wizard-1').find('.form-wizard').children('li').eq(index - 1).addClass(
                                'complete');
                        $('#<?php echo VGEVE; ?>bootstrap-wizard-1').find('.form-wizard').children('li').eq(index - 1).find('.step')
                                .html('<i class="fa fa-check"></i>');
                    }
                    if(index === 2){
                        var pr = 0;
                        var r = simpleScript.validaTable({
                            id: '#<?php echo VGEVE; ?>formNewGenerarVenta2 #'+diccionario.tabs.VGEVE+'gridProductos',
                            msn: mensajes.MSG_10                                                       
                        });
                        //Validar que precios no sean 0                      
                          $('#<?php echo VGEVE; ?>formNewGenerarVenta2 #'+diccionario.tabs.VGEVE+'gridProductos tbody tr').each(function (index) {
                                var precio;
                                $(this).children("td").each(function (index2) {
                                  switch (index2) {
                                      case 6:
                                          precio = $(this).text();
                                           if(parseFloat(precio) <= 0 || isNaN(parseFloat(precio)) ){   
                                                pr = pr + 1;                                      
                                            }
                                          break;      
                                  }
                              })
                          });
                        if (pr > 0){
                            simpleScript.notify.warning({
                                content: 'El precio que ingreso es menor o igual que CERO (0.00)'
                            }); 
                           return false;
                        }else if(r === false){
                            return false;
                        }else{
                            /*marca el paso como completado*/
                            $('#<?php echo VGEVE; ?>bootstrap-wizard-1').find('.form-wizard').children('li').eq(index - 1).addClass(
                                    'complete');
                            $('#<?php echo VGEVE; ?>bootstrap-wizard-1').find('.form-wizard').children('li').eq(index - 1).find('.step')
                                    .html('<i class="fa fa-check"></i>');
                            //Poner valor total:
                            totalPagado = $('#<?php echo VGEVE; ?>formNewGenerarVenta2 #'+diccionario.tabs.VGEVE+'txt_total').val();
                            $('#<?php echo VGEVE; ?>formNewGenerarVenta2 #'+diccionario.tabs.VGEVE+'txt_totalPago').val(parseFloat(totalPagado).toFixed(2));
                            if (totalPagado > 0){
                                pago = parseFloat(totalPagado) * 0.5;
                                $('#<?php echo VGEVE; ?>formNewGenerarVenta2 #'+diccionario.tabs.VGEVE+'txt_pago').val(parseFloat(pago).toFixed(2));
                            }
                        }
                    }
                    
                }
            });
            
            var wizard = $('.wizard').wizard();

            wizard.on('finished', function(e, data) {
                //$("#fuelux-wizard").submit();
                //console.log("submitted!");
                $.smallBox({
                    title: "Congratulations! Your form was submitted",
                    content: "<i class='fa fa-clock-o'></i> <i>1 seconds ago...</i>",
                    color: "#5F895F",
                    iconSmall: "fa fa-check bounce animated",
                    timeout: 4000
                });
            });
            /*para hacer evento invisible*/
            simpleScript.removeAttr.click({
                container: '#<?php echo VGEVE; ?>formNewGenerarVenta2',
                typeElement: 'button'
            });
            simpleScript.removeAttr.keyup({
                container: '#<?php echo VGEVE; ?>formNewGenerarVenta2',
                typeElement: 'input'
            });
            
            generarVentaScript.calculoTotal();
            generarVentaScript.calculoTotalFilaUp();
</script>
    </form>
</div>