<?php

/*
 * Documento   : consultar Panel Alquilado
 * Creado      : 17-09-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$fecha = Functions::cambiaf_a_normal( Aes::de(Formulario::getParam('_fecha')));
?>
<form id="<?php echo VRPT2; ?>formConsultaVenta" name="<?php echo VRPT2; ?>formConsultaVenta" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:60%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VRPT2_2.' | '.$fecha;?></h4>
            </div>
            <div style="margin-top:40px"></div>
            <form id="<?php echo VRPT2; ?>formGridConsultaVenta" name="<?php echo VRPT2; ?>formGridConsultaVenta" onsubmit="return false"  >
                <table id="<?php echo VRPT2; ?>gridConsultaVenta" class="table table-striped table-hover table-condensed" style="width:98%"></table>    
            </form>
            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>