<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-11-2014 17:11:41 
* Descripcion : formPagarVenta.phtml
* ---------------------------------------
*/

/*prefijo: VSEVE debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("VSEVEGR");
    
$saldo = Formulario::getParam('_saldo');

?>
<form id="<?php echo VSEVE; ?>formPagarVenta" name="<?php echo VSEVE; ?>formPagarVenta" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VSEVE_2; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VSEVE_3; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-calendar-o "></i>
                                <input type="text" id="<?php echo VSEVE; ?>txt_fecha" name="<?php echo VSEVE; ?>txt_fecha" value="<?php echo date("d/m/Y"); ?>" readonly >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo VSEVE_3M; ?></b>
                            </label>
                        </div>   
                        <label class="label col col-2"><?php echo VSEVE_4; ?></label>
                            <div class="col col-4">
                                <label class="input"> 
                                    <i class="icon-append fa  fa-money"></i>
                                    <input type="text" id="<?php echo VSEVE; ?>txt_monto" name="<?php echo VSEVE; ?>txt_monto" value="<?php echo number_format($saldo,2);?>"></input>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle  txt-color-teal"></i> <?php echo VSEVE_4M; ?></b>
                                </label>
                            </div>       
                    </div>
                </section>     
                
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo VSEVE; ?>btnGdVseguimientoventa" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VSEVE; ?>formPagarVenta");
</script>
<?php endif; ?>
<script>
    
   /* simpleScript.setEvent.date({
      element: '#<?php echo VSEVE; ?>txt_fecha'
    });*/
    
    $("#<?php echo VSEVE; ?>formPagarVenta").validate({
        rules : {
            <?php echo VSEVE; ?>txt_fecha : {
                required : true,
                date:true            
            },
            <?php echo VSEVE; ?>txt_monto : {
                required : true,
                number:true            
            }
        },
       
        errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
        },

        submitHandler: function(){
            vseguimientoventa.postPagoVenta();
        }   
});
</script>