<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-11-2014 17:11:18 
* Descripcion : formNewVcliente.phtml
* ---------------------------------------
*/

/*prefijo: VRECL debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("VRECLGR");
?>
<form id="<?php echo VRECL; ?>formNewVcliente" name="<?php echo VRECL; ?>formNewVcliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VRECL_2;?></h4>
            </div>
          <div class="modal-body smart-form" style="height: 350px;overflow-y: auto;overflow-x: hidden;">
              <section>
                    <div class="row">
                       <label class="label col col-3"><?php echo VRECL_4; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $tipoPer = Array (
                                            Array ( 'id' => 'N', 'descripcion' => 'P. Natural' ),
                                            Array ( 'id' => 'J', 'descripcion' => 'P. Juridica' )
                                    );                                   
                                    echo Functions::selectHtml(array(
                                        'data'=>$tipoPer,
                                        'atributes'=>array(
                                            'id'=>VRECL.'lst_tipoPersona',
                                            'name'=>VRECL.'lst_tipoPersona',
                                            'onchange'=>'vclienteScript.validarTipoPersona(this);'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>'N',
                                        'txtSelect'=>false
                                    ));
                                ?><i></i>
                            </label>
                        </div>                         
                    </div>
                </section>  
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A83; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_nombres" name="<?php echo VRECL; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_A83M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section class="frmpn">
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A84; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_apellidopaterno" name="<?php echo VRECL; ?>txt_apellidopaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_A84M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section class="frmpn">
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A85; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_apellidomaterno" name="<?php echo VRECL; ?>txt_apellidomaterno">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> <?php echo LABEL_A85M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>                                           
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo VRECL_6; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_nrodocumento" name="<?php echo VRECL; ?>txt_nrodocumento">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VRECL_6M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
               
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A91; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = personaController::getDepartamentos();                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>VRECL.'lst_departamento',
                                            'name'=>VRECL.'lst_departamento',
                                            'onchange'=>'registrarVendedor.getProvincias({
                                                            idDepartamento: $(\'#'.VRECL.'lst_departamento\').val(),
                                                            content: \'#'.VRECL.'cont-provincias\',
                                                            idElement: \''.VRECL.'lst_provincia\',
                                                            nameElement: \''.VRECL.'lst_provincia\',
                                                            contentUbigeo: \'#'.VRECL.'cont-ubigeo\',
                                                            idUbigeo: \''.VRECL.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A92; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo VRECL; ?>cont-provincias"> 
                                <select id="<?php echo VRECL; ?>lst_provincia" name="<?php echo VRECL; ?>lst_provincia">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A93; ?></label>
                        <div class="col col-8">
                            <label class="select" id="<?php echo VRECL; ?>cont-ubigeo"> 
                                <select id="<?php echo VRECL; ?>lst_ubigeo" name="<?php echo VRECL; ?>lst_ubigeo">
                                    <option value="">Seleccionar</option>
                                </select>
                                <i></i>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A86; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_direccion" name="<?php echo VRECL; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A86M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A87; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_email" name="<?php echo VRECL; ?>txt_email">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A87M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section class="frmpn">
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A88; ?></label>
                        <div class="inline-group col col-8">
                            <label class="radio"> 
                                <input name="<?php echo VRECL; ?>rd_sexo" id="<?php echo VRECL; ?>rd_sexoH" checked type="radio" value="H">
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo VRECL; ?>rd_sexo" id="<?php echo VRECL; ?>rd_sexoM" type="radio" value="M">
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo LABEL_A89; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_telefonos" name="<?php echo VRECL; ?>txt_telefonos">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_A89M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div> 
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo VRECL; ?>btnGrVcliente" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VRECL; ?>formNewVcliente");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/

 if($('#'+diccionario.tabs.VCOTI+'_CONTAINER').length > 0){
    $("#<?php echo VRECL; ?>formNewVcliente").validate({
    rules : {
            <?php echo VRECL; ?>txt_nombres : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo VRECL; ?>txt_apellidopaterno : {                     
                        regular: true,
                        minlength: 3
                },
                <?php echo VRECL; ?>txt_apellidomaterno : {                        
                        regular: true,
                        minlength: 3
                },     
                <?php echo VRECL; ?>txt_email : {
                        required : true,
                        email: true
                },
                <?php echo VRECL; ?>txt_nrodocumento : {                        
                        number: true,
                        maxlength: 13
                }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        vcliente.postNewVcliente();
    }   
   });
 }else{     
    $("#<?php echo VRECL; ?>formNewVcliente").validate({
    rules : {
            <?php echo VRECL; ?>txt_nombres : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo VRECL; ?>txt_apellidopaterno : {                     
                        regular: true,
                        minlength: 3
                },
                <?php echo VRECL; ?>txt_apellidomaterno : {                        
                        regular: true,
                        minlength: 3
                },     
                <?php echo VRECL; ?>txt_email : {
                        email: true
                },
                <?php echo VRECL; ?>txt_nrodocumento : {                        
                        number: true,
                        maxlength: 13
                }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        vcliente.postNewVcliente();
    }        
   });  
 }




</script>