<?php

/*
 * Documento   : consultar Panel Alquilado
 * Creado      : 17-09-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$fecha = Functions::cambiaf_a_normal( Aes::de(Formulario::getParam('_fecha')));
?>
<form id="<?php echo VRPT2; ?>formConsultaVenta" name="<?php echo VRPT2; ?>formConsultaVenta" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:60%">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VRPT2_2.' | '.$fecha;?></h4>
            </div>
                      
            <div class="modal-body smart-form scroll-form" style="height: 440px;"  >
                <ul class="nav nav-tabs bordered">
                    <li class="active">
                        <a id="tab0" href="#s1" data-toggle="tab"><?php echo VRPT2_4; ?></a>
                    </li>
                    <li >
                        <a id="tab1" href="#s2" data-toggle="tab"><?php echo VRPT2_5; ?></a>
                    </li>
                    <li >
                        <a id="tab2" href="#s3" data-toggle="tab"><?php echo VRPT2_6; ?></a>
                    </li>                    
                </ul>
                 <div class="tab-content padding-10"> 
                     <!-- 1er Tab-->
                     <div class="tab-pane fade in active" id="s1" >                        
                        <table id="<?php echo VRPT2; ?>gridConsultaVenta" class="table table-striped table-hover table-condensed" style="width:98%"  ></table>                                                          
                    </div>
                     <!-- 2 Tab-->
                     <div class="tab-pane fade" id="s2" >                        
                        <table id="<?php echo VRPT2; ?>gridConsultaEgresos" class="table table-striped table-hover table-condensed" style="width:98%"  ></table>                                                          
                    </div>
                    <!-- 3 Tab-->
                    <div class="tab-pane fade" id="s3">
                        <table id="<?php echo VRPT2; ?>gridConsultaCaja" class="table table-striped table-hover table-condensed" style="width:98%"></table>          
                    </div>                  
                 </div>
             </div>               

            <div class="modal-footer">              
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>

<script>
 var i0=0, i1=0;   
    
    $('#tab1').click(function(){
        if (i0 < 1){
            setTimeout(function(){reporteVentaFecha.getGridConsultaEgresos();},500);        
            i0++;
        }
    }); 
    $('#tab2').click(function(){
        if (i1 < 1){
            setTimeout(function(){reporteVentaFecha.getGridConsultaCaja();},500);        
            i1++;
        }
    });    
  
</script>