<?php
/*
 * Documento   : buscarCliente de venta
 * Creado      : 17-11-2014
 */

$buscar = Session::getPermiso('VRECLBS');
?>
<form id="<?php echo VCOTI; ?>formBuscarCliente" name="<?php echo VCOTI; ?>formBuscarCliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo LABEL_GNC12; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_2; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <input type="text" id="<?php echo VCOTI; ?>txt_search" name="<?php echo VCOTI; ?>txt_search" placeholder="Escriba y presione enter para buscar" onkeypress="simpleScript.triggerPress('#<?php echo VCOTI; ?>btnSubSearchCL',event);"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <div class="well">
                    <table id="<?php echo VCOTI; ?>gridClientesFound" class="table table-striped table-bordered table-hover" style="width:100%"></table>
                </div>
            </div>
            <div class="modal-footer">
                <button id="<?php echo VCOTI; ?>btnSubSearchCL" type="submit" class="hide">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$buscar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo VCOTI; ?>formBuscarCliente');
    </script>
<?php endif; ?>
<script>
    $('#<?php echo VCOTI; ?>formBuscarCliente').validate({

            errorPlacement : function(error, element) {
                    error.insertAfter(element.parent());
            },
                    
            submitHandler: function(){
                vGenerarCotizacion.getClientes();
            }   
        });
</script>