<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 07-11-2014 00:11:47 
* Descripcion : formNewVproducto.phtml
* ---------------------------------------
*/

/*prefijo: VPROD debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("VPRODGR");
$nuevo = Session::getPermiso('VPRODNEW');
?>
<form id="<?php echo VPROD; ?>formNewVproducto" name="<?php echo VPROD; ?>formNewVproducto" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VPROD2;?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VPROD4; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VPROD; ?>txt_descripcion" name="<?php echo VPROD; ?>txt_descripcion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VPROD4M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <!-- Combo unidad de Medida-->
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VPROD6; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = vproductoController::getUnidadMedida();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>VPROD.'lst_unidadMedida',
                                            'name'=>VPROD.'lst_unidadMedida'
                                        ),
                                        'etiqueta'=>'nombre',
                                        'value'=>'id_unidadmedida',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                            </label>
                        </div>
                        <?php if ($nuevo['permiso']): ?>
                        <button id="<?php echo VPROD; ?>btnNew" type="button" onclick="vunidadMedida.getFormNewVunidadMedida(this,'#<?php echo VPROD; ?>lst_unidadMedida');" class="<?php echo $nuevo['theme'];?>" title="<?php echo $nuevo['accion'];?>">
                                <i class="<?php echo $nuevo['icono'];?> pd8"></i>
                            </button>
                        <?php endif; ?>
                    </div>
               
                </section>                
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VPROD5; ?></label>
                        <div class="col col-5">
                            <label class="input"> 
                                <i class="icon-append fa fa-money"></i>
                                <input type="text" id="<?php echo VPROD; ?>txt_precio" name="<?php echo VPROD; ?>txt_precio">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VPROD5M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo VPROD; ?>btnGrVproducto" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VPROD; ?>formNewVproducto");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo VPROD; ?>formNewVproducto").validate({
    // Rules for form validation
    rules : {
        <?php echo VPROD; ?>txt_descripcion : {
            required : true,
            minlength: 3
        },
         <?php echo VPROD; ?>txt_precio : {
            required : true,
            number : true 
        }
    },  
    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        vproducto.postNewVproducto();
    }   
});
</script>