<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-12-2014 23:12:35 
* Descripcion : indexCajaCierre.phtml
* ---------------------------------------
*/
$generar    = Session::getPermiso("CAJACGN");
$buscar    = Session::getPermiso("CAJACBS");
echo Functions::widgetOpen(array(
        "id"=>CAJAC,
        "title"=>CAJAC_1
    )); 
?>

    <div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:0;top:5px;width: 65% ">               
        <label class="label col col-1"><?php echo VRPT1_2; ?></label>        
        <div class="col col-2" style="padding-left:5px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAC;?>txt_fechaGrid" name="<?php echo CAJAC;?>txt_fechaGrid" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " readonly />
             </div>            
        </div>     
        <div class="col col-1" style="padding-left:30px;">
            <div class=" ">
                <button id="<?php echo CAJAC; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="cajaCierre.getGridCajaCierre();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
    </div>        
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($generar["permiso"]): ?>
                <button id="<?php echo CAJAC; ?>btnNewCajaCierre" type="button" onclick="cajaCierre.postGenerarCierre(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="<?php echo $generar["icono"]; ?>"></i> <?php echo $generar["accion"]; ?>
                </button>
                <?php endif; ?>              
            </div>
        </div>

    </div>
    <form id="<?php echo CAJAC; ?>formGridCajaCierre" name="<?php echo CAJAC; ?>formGridCajaCierre" onsubmit="return false" >
        <table id="<?php echo CAJAC; ?>gridCajaCierre" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>