<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 22-11-2014 20:11:18 
* Descripcion : indexVegresos.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VEGRENEW");
$anular = Session::getPermiso("VEGREAN");
$buscar = Session::getPermiso("VEGREBS");

echo Functions::widgetOpen(array(
        "id"=>VEGRE,
        "title"=>VEGRE_1
    )); 

$validarCaja = vegresosController::getValidarCaja();

?>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:300px;top:5px;width: 65% ">               
        <label class="label col col-1"><?php echo VRPT1_2; ?></label>        
        <div class="col col-2" style="padding-left:5px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VEGRE;?>txt_fechaGrid" name="<?php echo VEGRE;?>txt_fechaGrid" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " readonly />
             </div>            
        </div>     
        <div class="col col-1" style="padding-left:30px;">
            <div class=" ">
                <button id="<?php echo VEGRE; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="vegresos.getGridVegresos();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
    </div>        
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"] && $validarCaja['existe'] > 0): ?>
                <button id="<?php echo VEGRE; ?>btnNewVegresos" type="button" onclick="vegresos.getFormNewVegresos(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                  <?php else: ?>
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" class="<?php echo $nuevo['theme'];?>" disabled>
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>                
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($anular["permiso"] && $validarCaja['existe'] > 0): ?>
                <button id="<?php echo VEGRE; ?>btnDeleteVegresos" type="button" onclick="vegresos.postDeleteVegresosAll(this);" class="<?php echo $anular["theme"]; ?>">
                    <i class="<?php echo $anular["icono"]; ?>"></i> <?php echo $anular["accion"]; ?>
                </button>
                <?php else: ?>
                <button id="<?php echo VEGRE; ?>btnDeleteVegresos" type="button" class="<?php echo $anular["theme"]; ?>" disabled>
                    <i class="<?php echo $anular["icono"]; ?>"></i> <?php echo $anular["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo VEGRE; ?>formGridVegresos" name="<?php echo VEGRE; ?>formGridVegresos" onsubmit="return false" >
        <table id="<?php echo VEGRE; ?>gridVegresos" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>
<script>
  /*  simpleScript.setEvent.date({
        element: '#<?php echo VEGRE; ?>txt_fechaGrid' 
    });*/
</script>