<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-12-2014 21:12:27 
* Descripcion : indexCajaApertura.phtml
* ---------------------------------------
*/
$generar    = Session::getPermiso("CAJAAGN");
$buscar    = Session::getPermiso("CAJAABS");
echo Functions::widgetOpen(array(
        "id"=>CAJAA,
        "title"=>CAJAA_1
    )); 
?>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:0;top:5px;width: 65% ">               
        <label class="label col col-1"><?php echo COGEN_2; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAA;?>txt_f1" name="<?php echo CAJAA;?>txt_f1" value ="01/01/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <label class="label col col-1">&nbsp;<?php echo COGEN_3; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAA;?>txt_f2" name="<?php echo CAJAA;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " />
             </div>            
        </div>
        <div class="col col-1" style="padding-left:30px;">
            <div class=" ">
                <button id="<?php echo CAJAA; ?>btnBuscar" type="button" style="padding:6px 10px;"
                        onclick="cajaApertura.getGridCajaApertura();" 
                        class="<?php echo $buscar['theme'];?> btn-sm"  >
                      <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?>
                </button>
            </div>
        </div>
    </div>        
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($generar["permiso"]): ?>
                <button id="<?php echo CAJAA; ?>btnNewCajaApertura" type="button" onclick="cajaApertura.postGenerarApertura(this);" class="btn txt-color-white bg-color-blueDark">
                    <i class="<?php echo $generar["icono"]; ?>"></i> <?php echo $generar["accion"]; ?> Apertura
                </button>
                <?php endif; ?>              
            </div>
        </div>

    </div>
    <form id="<?php echo CAJAA; ?>formGridCajaApertura" name="<?php echo CAJAA; ?>formGridCajaApertura" onsubmit="return false" >
        <table id="<?php echo CAJAA; ?>gridCajaApertura" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>
<script>

    simpleScript.setEvent.dateRange({
        ini: '#<?php echo CAJAA; ?>txt_f1',
        fin: '#<?php echo CAJAA; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo CAJAA; ?>txt_f2',
        fin: '#<?php echo CAJAA; ?>txt_f1',
        opt: 'maxDate'
    });
    
</script>