<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 19-11-2014 22:11:59 
* Descripcion : indexReporteVentaDia.phtml
* ---------------------------------------
*/
$pdf    = Session::getPermiso("VRPT1EP");
$excel    = Session::getPermiso("VRPT1EX");
$recuperar    = Session::getPermiso("VRPT1RC");
?>   
    
<?php
    $obj = array(
        'id' => VRPT1,
        'title' => VRPT1_1,
        'height' => 'auto',
        'padding' => true
    );
    echo Functions::widgetOpen($obj);
        
    ?>
<button id="<?php echo VRPT1; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VRPT1; ?>btnDowExcel" type="button" class="hide">Descargar</button>
    <div class="widget-body-toolbar" style="margin:0px; padding:10px">  
          <div class="smart-form" style="position: absolute;left:5px;top:15px;width: 65% ">           
            <label class="label col col-1"><?php echo VRPT1_2; ?></label>   
            <label class="label col col-2"><b><?php echo date("d/m/Y"); ?></b></label>   

            <div class="col col-7" style="padding-left:30px;" >        
         
                <button id="<?php echo VRPT2; ?>btnRefresh" type="button" style="padding:6px 7px; margin-top:6px;" 
                        onclick="reporteVentaDia.getGraficoReporteVentaDia();"
                         class="<?php echo $recuperar['theme'];?> btn-sm"  >
                      <i class="<?php echo $recuperar['icono'];?>"></i> <?php echo $recuperar['accion'];?>
                 </button> 
                <button id="<?php echo VRPT2; ?>btnPDF" type="button" style="padding:6px 7px"
                        onclick="reporteVentaDia.postPDF(this,'<?php echo Aes::en(date("Y-m-d"));?>');" 
                        class="<?php echo $pdf['theme'];?> btn-sm"  >
                      <i class="<?php echo $pdf['icono'];?>"></i> <?php echo $pdf['accion'];?>
                </button>  
                 <button id="<?php echo VRPT2; ?>btnExcel" type="button" style="padding:6px 7px"
                        onclick="reporteVentaDia.postExcel(this,'<?php echo Aes::en(date("Y-m-d"));?>');" 
                        class="<?php echo $excel['theme'];?> btn-sm"  >
                      <i class="<?php echo $excel['icono'];?>"></i> <?php echo $excel['accion'];?>
                </button>  
               </div>
          
        </div>
    </div>
        <div id="<?php echo VRPT1; ?>chartdiv" style="width: auto; height: 400px;">
        </div>
   
    
<?php echo Functions::widgetClose(); ?>