<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 14-11-2014 09:50:58 
* Descripcion : indexGenerarVenta.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("VGEVENEW");
$anular = Session::getPermiso("VGEVEAN");
echo Functions::widgetOpen(array(
        "id"=>VGEVE,
        "title"=>VGEVE_1
    )); 

$validarCaja = generarVentaController::getValidarCaja();

?>
<button id="<?php echo VGEVE; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VGEVE; ?>btnDowExcel" type="button" class="hide">Descargar</button>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"] && $validarCaja['existe'] > 0 ): ?>
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" onclick="generarVenta.getFormNewGenerarVenta(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php else: ?>
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" class="<?php echo $nuevo['theme'];?>" disabled>
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>
                <?php if($anular["permiso"] && $validarCaja['existe'] > 0 ): ?>
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" onclick="generarVenta.postAnularGenerarVentaAll(this);" class="<?php echo $anular['theme'];?>">
                    <i class="<?php echo $anular['icono'];?>"></i> <?php echo $anular['accion'];?>
                </button>
                <?php else: ?>
                 <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" class="<?php echo $anular['theme'];?>" disabled>
                    <i class="<?php echo $anular['icono'];?>"></i> <?php echo $anular['accion'];?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo VGEVE; ?>formGridGenerarVenta" name="<?php echo VGEVE; ?>formGridGenerarVenta" onsubmit="return false;">
        <table id="<?php echo VGEVE; ?>gridGenerarVenta" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>