<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-11-2014 16:11:31 
* Descripcion : indexVunidadMedida.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VUNIDNEW");
$eliminar = Session::getPermiso("VUNIDDEL");
echo Functions::widgetOpen(array(
        "id"=>VUNID,
        "title"=>VUNID1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo VUNID; ?>btnNewVunidadMedida" type="button" onclick="vunidadMedida.getFormNewVunidadMedida(this,'');" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo VUNID; ?>btnDeleteVunidadMedida" type="button" onclick="vunidadMedida.postDeleteVunidadMedidaAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo VUNID; ?>formGridVunidadMedida" name="<?php echo VUNID; ?>formGridVunidadMedida" onsubmit="return false">
        <table id="<?php echo VUNID; ?>gridVunidadMedida" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>