<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-11-2014 17:11:18 
* Descripcion : indexVcliente.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VRECLNEW");
$eliminar = Session::getPermiso("VRECLDEL");
echo Functions::widgetOpen(array(
        "id"=>VRECL,
        "title"=>VRECL_1
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo VRECL; ?>btnNewVcliente" type="button" onclick="vcliente.getFormNewVcliente(this,'');" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>
                <!-- verificar permisos -->
                <?php if($eliminar["permiso"]): ?>
                <button id="<?php echo VRECL; ?>btnDeleteVcliente" type="button" onclick="vcliente.postDeleteVclienteAll(this);" class="<?php echo $eliminar["theme"]; ?>">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <form id="<?php echo VRECL; ?>formGridVcliente" name="<?php echo VRECL; ?>formGridVcliente" onsubmit="return false"  >
        <table id="<?php echo VRECL; ?>gridVcliente" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    </form>
<?php echo Functions::widgetClose(); ?>