<?php
/*
 * Documento   : editarOpcion
 * Creado      : 12-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$editar = Session::getPermiso('MNUED');

$data = configurarMenuController::getOpcion($this->_idOpcion);
?>
<form id="<?php echo T3; ?>formEditarOpcion" name="<?php echo T3; ?>formEditarOpcion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true" onclick="configurarMenu.resetKeyOpcion();">
                    &times;
                </button>
                <h4 class="modal-title">Editar Opción</h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2">Opción</label>
                        <div class="col col-10">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_opcion" name="<?php echo T3; ?>txt_opcion" value="<?php echo $data['opcion']; ?>"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Alias</label>
                        <div class="col col-3">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_alias" name="<?php echo T3; ?>txt_alias" value="<?php echo $data['alias']; ?>"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Debe especificar un alias único para la opción'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">URL</label>
                        <div class="col col-6">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_url" name="<?php echo T3; ?>txt_url" value="<?php echo $data['url']; ?>"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Evento único para onclick de la opción'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Orden</label>
                        <div class="col col-2">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_orden" name="<?php echo T3; ?>txt_orden" value="<?php echo $data['orden']; ?>"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Posición de la opción'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo T3; ?>chk_activo" id="<?php echo T3; ?>chk_activo" value="1" <?php echo ($data['activo'] == 1)?'checked':''; ?>></input>
                                <i></i>
                                Activo
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="<?php echo T3; ?>btnEditaOpcion" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-save"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose" onclick="configurarMenu.resetKeyOpcion();">
                    <i class="fa fa-ban"></i> Cerrar
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$editar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T3; ?>formEditarOpcion');
</script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement:'right'});
    $('#<?php echo T3; ?>formEditarOpcion').validate({
        rules : {
                <?php echo T3; ?>txt_opcion : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T3; ?>txt_alias : {
                        required : true,
                        regular: true,
                        minlength: 2,
                        maxlength: 5
                },
                <?php echo T3; ?>txt_url : {
                        required : true,
                        minlength: 5
                },
                <?php echo T3; ?>txt_orden : {
                        required : true,
                        regular: true,
                        maxlength: 3,
                        number: true
                }
        },

        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            configurarMenu.postEditarOpcion();
        }   
    });
</script>
</form>