<?php
/*
 * Documento   : nuevoMenuPrincipal
 * Creado      : 11-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('MNUGR');
?>
<form id="<?php echo T3; ?>formNuevoMenuPrincipal" name="<?php echo T3; ?>formNuevoMenuPrincipal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Nuevo Menú Principal</h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2">Menú</label>
                        <div class="col col-10">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_menu" name="<?php echo T3; ?>txt_menu"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Alias</label>
                        <div class="col col-3">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_alias" name="<?php echo T3; ?>txt_alias"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Debe especificar un alias único para la opción'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">URL</label>
                        <div class="col col-6">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_url" name="<?php echo T3; ?>txt_url"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Evento único para onclick de la opción'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2">Orden</label>
                        <div class="col col-2">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_orden" name="<?php echo T3; ?>txt_orden"></input>
                            </label>
                        </div>
                        <?php echo Functions::help('Posición del menú principal'); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="<?php echo T3; ?>chk_activo" id="<?php echo T3; ?>chk_activo" value="1"></input>
                                <i></i>
                                Activo
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($grabar['permiso']):?>
                <button id="<?php echo T3; ?>btnGrabaMenuPri" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-save"></i> <?php echo $grabar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> Cerrar
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$grabar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T3; ?>formNuevoMenuPrincipal');
</script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement:'right'});
    $('#<?php echo T3; ?>formNuevoMenuPrincipal').validate({
        // Rules for form validation
        rules : {
                <?php echo T3; ?>txt_menu : {
                        required : true,
                        regular: true,
                        minlength: 3
                },
                <?php echo T3; ?>txt_alias : {
                        required : true,
                        regular: true,
                        minlength: 2,
                        maxlength: 5
                },
                <?php echo T3; ?>txt_url : {
                        required : true,
                        minlength: 5
                },
                <?php echo T3; ?>txt_orden : {
                        required : true,
                        regular: true,
                        number: true,
                        maxlength: 3
                }
        },

        // Do not change code below
        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            configurarMenu.postMenuPrincipal();
        }   
    });
</script>
</form>